(function(g){var window=this;'use strict';var Ja=function(t){t.publish("cardstatechange",t.ov()&&t.bM()?1:0)},p_=function(t,r){var x=g.ZB(r);
const Y=x?r:arguments;for(x=x?0:1;x<Y.length;x++){if(t==null)return;t=t[Y[x]]}return t},wy$=function(t){const r=g.St(t);
t=g.rX(t);return new g.Rs(r.x,r.y,t.width,t.height)},ttm=function(t,r,x){let Y;
return Y=g.l0(t,r,function(){g.GF(Y);x.apply(t,arguments)},{})},gh=function(t){t=g.WB(t);
delete QS[t];g.o1(QS)&&Wb&&Wb.stop()},xrt=function(){Wb||(Wb=new g.B7(function(){rFt()},20));
const t=Wb;t.isActive()||t.start()},rFt=function(){var t=g.q4();
g.Qy(QS,function(r){YRm(r,t)});
g.o1(QS)||xrt()},Pb=function(t,r,x,Y){g.my.call(this);
if(!Array.isArray(t)||!Array.isArray(r))throw Error("Start and end parameters must be arrays");if(t.length!=r.length)throw Error("Start and end points must be the same length");this.B=t;this.K=r;this.duration=x;this.J=Y;this.coords=[];this.progress=this.Y=0;this.W=null},YRm=function(t,r){r<t.startTime&&(t.endTime=r+t.endTime-t.startTime,t.startTime=r);
t.progress=(r-t.startTime)/(t.endTime-t.startTime);t.progress>1&&(t.progress=1);t.Y=1E3/(r-t.W);t.W=r;IJX(t,t.progress);t.progress==1?(t.Z=0,gh(t),t.onFinish(),t.Fi()):t.isPlaying()&&t.P$()},IJX=function(t,r){typeof t.J==="function"&&(r=t.J(r));
t.coords=Array(t.B.length);for(let x=0;x<t.B.length;x++)t.coords[x]=(t.K[x]-t.B[x])*r+t.B[x]},mry=function(t,r){g.Yb.call(this,t);
this.coords=r.coords;this.x=r.coords[0];this.y=r.coords[1];this.z=r.coords[2];this.duration=r.duration;this.progress=r.progress;this.fps=r.Y;this.state=r.Z},ql=function(t,r,x,Y,I){Pb.call(this,r,x,Y,I);
this.element=t},sA=function(t,r,x,Y,I){if(r.length!=2||x.length!=2)throw Error("Start and end points must be 2D");
ql.call(this,t,r,x,Y,I)},Fl8=function(t){return Math.pow(t,3)},AFD=function(t){return 3*t*t-2*t*t*t},Dw=function(t){return t.baseUrl||null},XB=function(t,r){return g.vB(g.N4(t,r),x=>!!x)},hV1=function(t,r,x){function Y(JL){var Oc=JL.hovercardButton;
if(!Oc)return null;Oc=Oc.subscribeButtonRenderer;if(!Oc)return null;const BB=m(Oc.unsubscribedButtonText),qZ=m(Oc.subscribedButtonText);let b6,ZN;Oc.subscribed?(b6=m(Oc.subscriberCountWithUnsubscribeText),ZN=m(Oc.subscriberCountText)):(b6=m(Oc.subscriberCountText),ZN=m(Oc.subscriberCountWithSubscribeText));let bJ=null;return JL.signinEndpoint&&((bJ=p_(JL,"signinEndpoint","webNavigationEndpointData","url"))||(bJ=g.b(Oc.signInEndpoint?.commandMetadata,g.gV)?.url),!bJ)?null:BB&&(qZ||bJ)?{subscribed:Oc.subscribed,
subscribeText:BB,subscribeCount:b6,unsubscribeText:qZ,unsubscribeCount:ZN,enabled:Oc.enabled,signinUrl:bJ,classic:JL.useClassicSubscribeButton}:null}
function I(JL){if(JL){var Oc=[],BB=JL.videoId;BB&&Oc.push("v="+BB);(BB=JL.playlistId)&&Oc.push("list="+BB);(JL=JL.startTimeSeconds)&&Oc.push("t="+JL);return"/watch?"+Oc.join("&")}}
function m(JL){if(!JL)return null;const Oc=JL.simpleText;return Oc?Oc:JL.runs?g.N4(JL.runs,BB=>BB.text).join(""):null}
r=r.endscreenElementRenderer;if(!r)return null;const F=r.style,A=r.endpoint||{};let h=null;var E=null,U=!1;let n=null,L=null,M=null,z=null;var p=!1;let q=null,f=null;var X=null;let R=null,O=null,mW=null;if(F==="VIDEO")g.b(A,g.fr)?h=g.b(A,g.fr).url:(mW=g.b(A,g.cQ),h=I(mW)),E=!1,n=t,r.thumbnailOverlays?(U=r.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,L=m(U.text),U=U.style==="LIVE"):L=m(r.videoDuration);else if(F==="PLAYLIST")g.b(A,g.fr)?h=g.b(A,g.fr).url:(mW=g.b(A,g.cQ),h=I(mW)),E=!1,n=
t,M=m(r.playlistLength);else if(F==="CHANNEL"){if(p=p_(A,"browseEndpoint","browseId"))z=p,h=`/channel/${z}`;E=!1;n="new";(p=!!r.isSubscribe)?q=Y(r):f=m(r.subscribersText)}else F==="WEBSITE"?((X=p_(A,"urlEndpoint","url"))&&(h=X),E=!0,n="new",X=r.icon.thumbnails[0].url):F==="CREATOR_MERCHANDISE"&&(r.productPrice&&(R=m(r.productPrice)),r.additionalFeesText&&(O=m(r.additionalFeesText)),(E=p_(A,"urlEndpoint","url"))&&(h=E),E=!0,n="new");t=p_(r,"title","accessibility","accessibilityData","label");const F6=
r.endpoint?r.endpoint.clickTrackingParams:null;let op="";if(r.metadata){const JL=m(r.metadata);JL&&(op=JL)}return{id:`element-${x}`,type:F,title:m(r.title),metadata:op,callToAction:m(r.callToAction),xS:r.image,iconUrl:X,left:Number(r.left),width:Number(r.width),top:Number(r.top),aspectRatio:Number(r.aspectRatio),startMs:Math.floor(Number(r.startMs)),endMs:Math.floor(Number(r.endMs)),videoDuration:L,Dm:U,playlistLength:M,channelId:z,subscribeButton:q,subscribersText:f,isSubscribe:p,targetUrl:h||null,
Cj:E,sessionData:F6?{itct:F6}:null,EF:n,Rc:t?t:null,isPlaceholder:r.isPlaceholder,impressionUrls:XB(r.impressionUrls||[],Dw),eR:XB(r.hovercardShowUrls||[],Dw),clickUrls:XB(A.loggingUrls||[],Dw),visualElement:g.cF(r.trackingParams),productPrice:R,additionalFeesText:O,watchEndpoint:mW||null}},f_=function(t,r){const x={startMs:Math.floor(Number(t.startMs)),
impressionUrls:XB(t.impressionUrls||[],Dw),elements:XB(t.elements||[],(Y,I)=>hV1(r,Y,I))};
t.trackingParams&&(x.visualElement=g.cF(t.trackingParams));return x},kS=function(t){return t.player.X().playerStyle==="creator-endscreen-editor"},Els=function(t){return t.player.getVideoData().uK?"current":t.G?"new":"current"},Rm=function(t,r,x=!0){t.player.Oh("creatorendscreen");
t.D&&(t.D.dispose(),t.D=null,t.J.dispose(),t.J=null);for(var Y of Object.values(t.B))Y.dispose();t.B={};t.Y={};t.L.length>0&&(t.L.forEach(I=>{I.dispose()}),t.L.length=0);
t.Z&&(g.rL(t.Z,"ytp-ce-element-show"),t.Z.setAttribute("aria-hidden","true"));t.K=0;if((t.endscreen=r)&&r.elements){x&&Urm(t);x=[];Y=new g.aK(r.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});x.push(Y);t.player.X().B||(t.D=new g.l({A:"div",O:"ytp-ce-shadow"}),g.$I(t.player,t.D.element,4),t.J=new g.HE(t.D,200));for(Y=0;Y<r.elements.length;++Y){const I=r.elements[Y],m=nlZ(t,I);if(!m){g.u_(new g.zn("buildEndscreenElement null",I));continue}t.B[I.id]=m;t.Y[I.id]=I;g.$I(t.player,
m.element,4);const F=new g.aK(I.startMs,I.endMs,{id:"ytp-ce-element-"+I.id,namespace:"creatorendscreen"});x.push(F);LlL(t,m,I)}t.player.iZ(x);t.cE()}},MtZ=function(t){var r=t.player.getVideoData(),x=r.videoId;
t.W&&t.W.abort();x={method:"POST",onFinish:I=>{var m=t.W=null;I.status===200&&(I=I.responseText,I.substring(0,3)===")]}"&&(I=I.substring(3),m=JSON.parse(I),m=f_(m,Els(t))));Rm(t,m)},
urlParams:{v:x},withCredentials:!0};t.G&&(x.urlParams.ptype="embedded");const Y=r.Cp;Y&&(x.postParams={ad_tracking:Y});if(r=g.x$B(r))if(r=g.$M(r),r=g.XD(r))t.W=g.e_(r,x)},Urm=function(t){const r=g.Zf(),x=g.J1();
x&&r&&t.endscreen.visualElement&&g.hz(g.BF)(void 0,x,r,t.endscreen.visualElement)},nlZ=function(t,r){var x=null;
switch(r.type){case "VIDEO":t={A:"div",K8:["ytp-ce-element","ytp-ce-video"],V:{tabindex:"0","aria-label":r.Rc||"","aria-hidden":"true"},j:[{A:"div",O:"ytp-ce-element-shadow"},{A:"div",O:"ytp-ce-covering-image",V:$S(r)},{A:"div",O:"ytp-ce-covering-shadow-top"},{A:"a",O:"ytp-ce-covering-overlay",V:{href:K_(t,r.targetUrl),tabindex:"-1"},j:[{A:"div",K8:["ytp-ce-video-title","ytp-webkit-ellipsis"],V:{dir:g.M0(r.title||"")},BN:r.title},{A:"div",O:r.Dm?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
BN:r.videoDuration||void 0}]}]};x=new g.l(t);break;case "PLAYLIST":t={A:"div",K8:["ytp-ce-element","ytp-ce-playlist"],V:{tabindex:"0","aria-label":r.Rc||"","aria-hidden":"true"},j:[{A:"div",O:"ytp-ce-element-shadow"},{A:"div",O:"ytp-ce-covering-image",V:$S(r)},{A:"div",O:"ytp-ce-covering-shadow-top"},{A:"a",O:"ytp-ce-covering-overlay",V:{href:K_(t,r.targetUrl),tabindex:"-1"},j:[{A:"div",K8:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],V:{dir:g.M0(r.title||"")},BN:r.title},{A:"div",O:"ytp-ce-playlist-count",
j:[{A:"div",O:"ytp-ce-playlist-icon"},{A:"div",O:"ytp-ce-playlist-count-text",BN:r.playlistLength||void 0}]}]}]};x=new g.l(t);break;case "CHANNEL":x={A:"div",K8:["ytp-ce-element","ytp-ce-channel",r.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],V:{tabindex:"0","aria-label":r.Rc||"","aria-hidden":"true"},j:[{A:"div",O:"ytp-ce-element-shadow"},{A:"div",O:"ytp-ce-expanding-overlay",j:[{A:"div",O:"ytp-ce-expanding-overlay-hider"},{A:"div",O:"ytp-ce-expanding-overlay-background"},{A:"div",O:"ytp-ce-expanding-overlay-content",
j:[{A:"div",O:"ytp-ce-expanding-overlay-body",j:[{A:"div",O:"ytp-ce-expanding-overlay-body-padding",j:[{A:"a",K8:["ytp-ce-channel-title","ytp-ce-link"],V:{href:K_(t,r.targetUrl),target:"_blank",tabindex:"-1",dir:g.M0(r.title||"")},BN:r.title},r.subscribeButton?{A:"div",O:"ytp-ce-subscribe-container",j:[{A:"div",O:"ytp-ce-channel-subscribe"}]}:"",r.subscribersText?{A:"div",O:"ytp-ce-channel-subscribers-text",BN:r.subscribersText}:"",r.metadata?{A:"div",K8:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],BN:r.metadata}:""]}]}]}]},{A:"div",O:"ytp-ce-expanding-image",V:$S(r)}]};x=new g.l(x);const I=g.SQ(document,"div","ytp-ce-channel-subscribe",x.element)[0];if(r.subscribeButton&&r.channelId){g.wn(I,"ytp-ce-subscribe-button");let m;if(t.player.X().B){var Y=null;m=r.sessionData.itct}else Y="endscreen",m=null;Y=new g.up(r.subscribeButton.subscribeText,r.subscribeButton.subscribeCount,r.subscribeButton.unsubscribeText,r.subscribeButton.unsubscribeCount,!!r.subscribeButton.enabled,!!r.subscribeButton.classic,
r.channelId,!!r.subscribeButton.subscribed,Y,m,t.player,!1);I.appendChild(Y.element);t.L.push(Y)}break;case "WEBSITE":t={A:"div",K8:["ytp-ce-element","ytp-ce-website"],V:{tabindex:"0","aria-label":r.Rc||"","aria-hidden":"true"},j:[{A:"div",O:"ytp-ce-element-shadow"},{A:"div",O:"ytp-ce-expanding-overlay",j:[{A:"div",O:"ytp-ce-expanding-overlay-hider"},{A:"div",O:"ytp-ce-expanding-overlay-background"},{A:"div",O:"ytp-ce-expanding-overlay-content",j:[{A:"div",O:"ytp-ce-expanding-overlay-body",j:[{A:"div",
O:"ytp-ce-expanding-overlay-body-padding",j:[{A:"div",O:"ytp-ce-website-title",V:{dir:g.M0(r.title||"")},BN:r.title},{A:"div",O:"ytp-ce-website-metadata",BN:r.metadata},{A:"a",K8:["ytp-ce-website-goto","ytp-ce-link"],V:{href:K_(t,r.targetUrl),target:"_blank",tabindex:"-1"},BN:r.callToAction}]}]}]}]},{A:"div",O:"ytp-ce-expanding-image",V:$S(r)},{A:"div",O:"ytp-ce-expanding-icon",V:CWs(r.iconUrl)}]};x=new g.l(t);break;case "CREATOR_MERCHANDISE":x="",r.productPrice&&(x={A:"div",O:"ytp-ce-merchandise-price-container",
j:[{A:"div",O:"ytp-ce-merchandise-price",BN:r.productPrice}]},r.additionalFeesText&&x.j.push({A:"div",O:"ytp-ce-merchandise-additional-fees",BN:r.additionalFeesText})),t={A:"div",K8:["ytp-ce-element","ytp-ce-merchandise"],V:{tabindex:"0","aria-label":r.Rc||"","aria-hidden":"true"},j:[{A:"div",O:"ytp-ce-element-shadow"},{A:"div",O:"ytp-ce-expanding-overlay",j:[{A:"div",O:"ytp-ce-expanding-overlay-hider"},{A:"div",O:"ytp-ce-expanding-overlay-background"},{A:"div",O:"ytp-ce-expanding-overlay-content",
j:[{A:"div",O:"ytp-ce-expanding-overlay-body",j:[{A:"div",O:"ytp-ce-expanding-overlay-body-padding",j:[{A:"div",O:"ytp-ce-merchandise-title",V:{dir:g.M0(r.title||"")},BN:r.title},x,{A:"div",O:"ytp-ce-merchandise-metadata",BN:r.metadata},{A:"a",K8:["ytp-ce-merchandise-goto","ytp-ce-link"],V:{href:K_(t,r.targetUrl),target:"_blank",tabindex:"-1"},BN:r.callToAction}]}]}]}]},{A:"div",O:"ytp-ce-expanding-image",V:$S(r)},{A:"div",O:"ytp-ce-merchandise-invideo-cta-container",j:[{A:"div",O:"ytp-ce-merchandise-invideo-cta",
BN:r.callToAction||void 0}]}]},x=new g.l(t)}r.isPlaceholder&&g.wn(x.element,"ytp-ce-placeholder");return x},LlL=function(t,r,x){function Y(){F(1)}
function I(){F(-1)}
r.listen("mouseenter",()=>{VS(t,r,x)});
r.listen("mouseleave",()=>{om(t,r,x)});
t.player.X().B||r.listen("click",()=>{g.wn(r.element,"ytp-ce-element-hover")});
r.listen("click",A=>{iDe(t,x,A)});
r.listen("keypress",A=>{iDe(t,x,A)});
r.listen("focus",()=>{VS(t,r,x)});
r.listen("blur",()=>{om(t,r,x)});
r.listen("touchstart",()=>{VS(t,r,x)});
var m=g.Tq("ytp-ce-expanding-overlay-hider",r.element);m&&r.S(m,"touchstart",A=>{A.stopPropagation();g.rL(r.element,"ytp-ce-element-hover");g.rL(r.element,"ytp-ce-force-expand")});
r.listen("keydown",A=>{t.iV=A.keyCode===9&&!A.shiftKey});
const F=A=>{t.K+=A;t.K>0?(g.wn(r.element,"ytp-ce-force-expand"),OA(t,x.id,!0)):(g.rL(r.element,"ytp-ce-force-expand"),g.rL(r.element,"ytp-ce-element-hover"),OA(t,x.id,!1))};
m=A=>{A&&(r.listen("blur",()=>{A.style.display!="none"&&t.iV&&A.focus()}),r.S(A,"focus",Y),r.S(A,"blur",I))};
m(g.Tq("ytp-sb-subscribe",r.element));m(g.Tq("ytp-sb-unsubscribe",r.element));r.listen("focus",Y);r.listen("blur",I)},bw=function(t,r,x){function Y(){m||(I++,I===r.length&&(F.stop(),x&&x()))}
if(!r||r.length===0||kS(t))x&&x();else{r=jsD(t,r);var I=0,m=!1,F=new g.B7(()=>{m=!0;x&&x()},1E3,t);
F.start();for(t=0;t<r.length;t++)g.v0(r[t],Y)}},$S=function(t){let r;
t.xS&&(r=t.xS.thumbnails);return CWs(r?r[r.length-1].url:null)},K_=function(t,r){t=t.player.X();
if(r){if(r.startsWith("//"))return t.protocol+":"+r;if(r.startsWith("/"))return g.fs(t)+r}else return"";return r},CWs=function(t){return t?{style:"background-image: url("+t+")"}:{}},VS=function(t,r,x){g.Gg(r.element,"ytp-ce-element-hover")||(x.type==="VIDEO"||x.type==="PLAYLIST"?g.wn(r.element,"ytp-ce-element-hover"):t.player.X().B?(new g.B7(()=>{g.wn(r.element,"ytp-ce-element-hover")},200)).start():g.wn(r.element,"ytp-ce-element-hover"),bw(t,x.eR),OA(t,x.id,!0))},om=function(t,r,x){g.rL(r.element,
"ytp-ce-element-hover");
g.rL(r.element,"ytp-ce-force-expand");OA(t,x.id,!1)},iDe=function(t,r,x){if(r.targetUrl&&(!x||x.type!=="keypress"||x.keyCode===13)){for(var Y=x.target;Y&&!g.Gg(Y,"ytp-ce-element");){g.Gg(Y,"subscribe-label")&&eB(t,r);
if(g.Gg(Y,"ytp-ce-channel-subscribe"))return;Y=Y.parentElement||null}if(!Y||g.Gg(Y,"ytp-ce-element-hover")){x.preventDefault();x.stopPropagation();if(Y=t.B[r.id])om(t,Y,r),Y.element.blur();if(x.ctrlKey||x.metaKey||r.EF==="new")eB(t,r),t.player.sendVideoStatsEngageEvent(17,void 0),t.player.pauseVideo(),x=g.$M(K_(t,r.targetUrl)),x=g.XD(x),g.x7(x,void 0,r.sessionData);else{const I=g.JW(t.player.X())||t.player.getVideoData().uK,m=()=>{var F=K_(t,r.targetUrl),A=r.sessionData,h=r.watchEndpoint;const E=
g.j_(F);I&&E&&(E.v||E.list)?t.player.CQ(E.v,A,E.list,!1,void 0,h||void 0):g.rq(F,A)};
eB(t,r,()=>{t.player.sendVideoStatsEngageEvent(17,m)})}}}},OA=function(t,r,x){t.D&&(x?t.J.show():t.J.hide());
for(const Y of Object.keys(t.B))Y!==r&&g.D(t.B[Y].element,"ytp-ce-element-shadow-show",x)},eB=function(t,r,x){bw(t,r.clickUrls,x);
(t=g.J1())&&r.Cj&&g.Yd(t,r.visualElement)},jsD=function(t,r){var x=t.player.getVideoData().clientPlaybackNonce;
t=t.player.getCurrentTime().toFixed(2);x={CPN:x,AD_CPN:x,MT:t};t=[];for(let Y=0;Y<r.length;Y++)t.push(drf(r[Y],x));return t},drf=function(t,r){return t.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,x=>{let Y=unescape(x);
Y=Y.substring(1,Y.length-1);return r[Y]?escape(r[Y]):x})},zVN=function(t){return typeof t==="string"?t:""},vb=function(t,r,x){for(const Y in r)if(r[Y]===t)return t;
return x},Nl=function(t){if(!t)return null;
var r=g.$M(zVN(t.value));r=g.XD(r);if(!r)return null;const x=vb(t.target,cFD,"current");if(x==null)t=null;else{var Y=t.show_link_icon;t=new yFD(r,x,Y==="true"||Y==="false"?Y==="true":!0,t.pause_on_navigation!=null?t.pause_on_navigation:!0)}return t},p4s=function(t){if(!t)return null;
const r=vb(t.type,uiy),x=vb(t.trigger,ZDf);t=t.url;t=Array.isArray(t)&&t.length?t[0]:t;t=Nl(t?t:null);return r?new JFD(r,x,t):null},Qse=function(t,r){return g.GT(t.action,r)},Bb=function(t,r){t="background-image: url("+t+");";
const x=[];r&&x.push(r);return{A:"div",O:"iv-card-image",V:{style:t},j:x}},Hb=function(t){return t.customMessage?am("div","iv-card-message",t.customMessage):""},SB=function(t){if(!t.metaInfo||t.metaInfo.length===0)return"";
const r=[];for(const x of t.metaInfo)r.push(am("li","",x));return{A:"ul",O:"iv-card-meta-info",j:r}},T$=function(t,r,x,Y){if(Y)for(const I of r)t.Z(I,Y,x.id,x.sessionData,x.gK.click,5)},am=function(t,r,x){r?typeof r==="string"?r={"class":r}:Array.isArray(r)&&(r={"class":r.join(" ")}):r={};
r.dir=g.M0(x);return{A:t,V:r,BN:x}},Wlt=function(t){if(!t.customMessage)return"";
const r=["iv-card-action","iv-card-primary-link"],x={};t.XY&&(r.push("iv-card-action-icon"),x.style="background-image: url("+t.XY+");");x.dir=g.M0(t.customMessage);const Y=[{A:"span",BN:t.customMessage}];t.showLinkIcon&&(Y.push("\u00a0"),Y.push({A:"span",O:"iv-card-link-icon"}));return{A:"div",K8:r,V:x,j:Y}},gl$=function(t){var r;
(r=t)&&!(r=t.length>1?t.charAt(0)==="/"&&t.charAt(1)!=="/":t==="/")&&(r=t.replace(/^(https?:)?\/\//,"").split("/",1),r=!r||r.length<1||!r[0]?[]:r[0].toLowerCase().split(".").reverse(),r=r[0]==="com"&&r[1]==="youtube"||r[0]==="be"&&r[1]==="youtu");return r?t.indexOf("/redirect?")===-1:!1},PWZ=function(t,r){return r?r:gl$(t)?"current":"new"},lw=function(t,r,x,Y,I,m,F){t.context.Z.listen(r,"click",A=>{t.HN(x,Y,I,m||[],F||0,A)});
t.context.Z.listen(r,"touchstart",()=>{t.QL=!1});
t.context.Z.listen(r,"touchmove",()=>{t.QL=!0})},qRw=function(t){if(g.b(t,g.fr)?.url)return g.b(t,g.fr).url;
if((t=g.b(t,g.cQ))&&t.videoId){let r="/watch?v="+t.videoId;t.playlistId&&(r+="&list="+t.playlistId);t.index&&(r+="&index="+t.index);t.startTimeSeconds&&(r+="&t="+t.startTimeSeconds);return r}return null},G$=function(t,r,x){return{Fp:(t.impressionLoggingUrlsV2s||[]).map(Y=>Y.baseUrl||""),
click:(x.loggingUrls||[]).map(Y=>Y.baseUrl||""),
close:(r.dismissLoggingUrlsV2s||[]).map(Y=>Y.baseUrl||""),
qM:(r.impressionLoggingUrlsV2s||[]).map(Y=>Y.baseUrl||""),
Rd:(r.clickLoggingUrlsV2s||[]).map(Y=>Y.baseUrl||"")}},xw=function(t,r){if(r.onClickCommand&&g.b(r.onClickCommand,g.DlK)?.targetId==="engagement-panel-error-corrections"){t.N=r;
var x=!0}else x=!1;if(!x||ss1(t,r))if(x=DrD(t,r)){var Y={SX:r,By:x.element,aP:!1};if(r.onClickCommand)t.U.C("web_infocards_teaser_show_logging_fix")&&(t.ZG||fJX(t),wh(t,r.id),x=t.findLastIndex(Y),g.i8(t.cards,x,0,Y));else{t.isInitialized||X4D(t);wh(t,r.id);const I=t.findLastIndex(Y);g.i8(t.cards,I,0,Y);x.C8(t.B,I);t.sC()}r.autoOpen?t.addCueRange(r.startMs,0x8000000000000,r.id,()=>{t.D||(t.Z=Y,t2(t),kAw(t,Y),rU(t,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(x=t.context.U.getCurrentTime()*1E3,x<5E3&&x>r.startMs&&
RVe(t,Y),t.addCueRange(r.startMs,r.startMs+1,r.id,()=>{RVe(t,Y)}),t2(t))}},Yw=function(t){t.D&&(t.oO.hide(),t.OC.B(),g.rL(t.context.U.getRootNode(),g.j$.IV_DRAWER_OPEN),t.D=!1,Ja(t.U),t.Y&&t.Y.stop(),t.Y=new g.B7(()=>{t.PN&&(t.PN.focus(),t.PN=null)},330),t.Y.start())},$rf=function(t,r){r=r.data;
r.autoOpenMs&&t.addCueRange(r.autoOpenMs,0x8000000000000,"",()=>{rU(t,"YOUTUBE_DRAWER_AUTO_OPEN")});
r.autoCloseMs&&t.addCueRange(r.autoCloseMs,0x8000000000000,"",()=>{Yw(t)});
const x=r.headerText;g.CD(t.dU,x);t.J&&(t.U.C("player_tooltip_data_title_killswitch")?t.J.setAttribute("title",x):t.J.setAttribute("data-tooltip-title",x));r.eventId&&(t.eventId=r.eventId);t.RO=g.cF(r.trackingParams);t.L=g.cF(r.closeTrackingParams);t.lZ=g.cF(r.iconTrackingParams)},Iu=function(t,r,x){let Y=-1,I=-1;
for(let m=0;m<t.length;m++){if(t[m].height===r||t[m].width===x)return t[m];((t[m].height||0)<r||(t[m].width||0)<x)&&(Y<0||(t[Y].height||0)<(t[m].height||0)||(t[Y].width||0)<(t[m].width||0))?Y=m:((t[m].height||0)>=r||(t[m].width||0)>=x)&&(I<0||(t[I].height||0)>(t[m].height||0)||(t[I].width||0)>(t[m].width||0))&&(I=m)}return t[I>=0?I:Y]},mF=function(t,r,x,Y){return{feature:x.feature?x.feature:"cards",
src_vid:t.context.videoData.videoId,annotation_id:r,ei:t.context.videoData.eventId||"",itct:Y.trackingParams||""}},Kls=function(t,r){const x=r.cardId?r.cardId:`cr:${t.K}`;
var Y=t.U.X().experiments.TX("enable_error_corrections_infocard_web_client");if(!r.content&&r.teaser.simpleCardTeaserRenderer&&Y){Y=r.teaser.simpleCardTeaserRenderer;var I=r.icon?r.icon.infoCardIconRenderer:null;if(Y.channelAvatar&&Y.channelAvatar.thumbnails&&Y.channelAvatar.thumbnails.length>0)var m=Iu(Y.channelAvatar.thumbnails,22,22).url;r={id:x,timestamp:t.K,type:"simple",teaserText:g.nr(Y.message),teaserDurationMs:Number(r.cueRanges[0].teaserDurationMs),startMs:Number(r.cueRanges[0].startCardActiveMs),
autoOpen:!!r.autoOpen,sessionData:{},sponsored:!1,gK:{},wi:null,H5:Y.trackingParams?g.cF(Y.trackingParams):null,lZ:I&&I.trackingParams?g.cF(I.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,XY:null,title:"",customMessage:"",url:null,onClickCommand:Y.onTapCommand||null,Kp:m};xw(t,r)}else if(r.content?.simpleCardContentRenderer){if(!r.cueRanges.length)return;m=r.content?.simpleCardContentRenderer;Y=r.teaser.simpleCardTeaserRenderer;I=r.icon?r.icon.infoCardIconRenderer:null;r={id:x,
timestamp:t.K,type:"simple",teaserText:g.nr(Y.message),teaserDurationMs:Number(r.cueRanges[0].teaserDurationMs),startMs:Number(r.cueRanges[0].startCardActiveMs),autoOpen:!!r.autoOpen,sessionData:mF(t,x,r,m),sponsored:!1,gK:G$(m,Y,m.command),wi:m.trackingParams?g.cF(m.trackingParams):null,H5:Y.trackingParams?g.cF(Y.trackingParams):null,lZ:I&&I.trackingParams?g.cF(I.trackingParams):null,imageUrl:Iu(m.image.thumbnails,290,290).url,displayDomain:m.displayDomain?g.nr(m.displayDomain):null,showLinkIcon:!!m.showLinkIcon,
XY:null,title:m.title?g.nr(m.title):"",customMessage:m.callToAction?g.nr(m.callToAction):"",url:g.b(m.command,g.fr).url?Nl({pause_on_navigation:!t.context.videoData.isLivePlayback,target:"new",value:g.b(m.command,g.fr).url}):null,onClickCommand:null};xw(t,r)}else if(r.content?.collaboratorInfoCardContentRenderer){if(!r.cueRanges.length)return;m=r.content?.collaboratorInfoCardContentRenderer;Y=r.teaser.simpleCardTeaserRenderer;I=r.icon?r.icon.infoCardIconRenderer:null;r={id:x,timestamp:t.K,type:"collaborator",
teaserText:g.nr(Y.message),teaserDurationMs:Number(r.cueRanges[0].teaserDurationMs),startMs:Number(r.cueRanges[0].startCardActiveMs),autoOpen:!!r.autoOpen,sessionData:mF(t,x,r,m),sponsored:!1,gK:G$(m,Y,m.endpoint),wi:m.trackingParams?g.cF(m.trackingParams):null,H5:Y.trackingParams?g.cF(Y.trackingParams):null,lZ:I&&I.trackingParams?g.cF(I.trackingParams):null,channelId:g.b(m.endpoint,g.zM).browseId,customMessage:m.customText?g.nr(m.customText):null,profileImageUrl:Iu(m.channelAvatar.thumbnails,290,
290).url,title:m.channelName?g.nr(m.channelName):"",metaInfo:[m.subscriberCountText?g.nr(m.subscriberCountText):""],url:Nl({pause_on_navigation:!t.context.videoData.isLivePlayback,target:"new",value:g.b(m.endpoint,g.zM).canonicalBaseUrl?g.b(m.endpoint,g.zM).canonicalBaseUrl:`/channel/${g.b(m.endpoint,g.zM).browseId}`}),onClickCommand:null};xw(t,r)}else if(r.content?.playlistInfoCardContentRenderer){if(!r.cueRanges.length)return;m=r.content?.playlistInfoCardContentRenderer;Y=r.teaser.simpleCardTeaserRenderer;
I=r.icon?r.icon.infoCardIconRenderer:null;r={id:x,timestamp:t.K,type:"playlist",teaserText:g.nr(Y.message),teaserDurationMs:Number(r.cueRanges[0].teaserDurationMs),startMs:Number(r.cueRanges[0].startCardActiveMs),autoOpen:!!r.autoOpen,sessionData:mF(t,x,r,m),sponsored:!1,gK:G$(m,Y,m.action),wi:m.trackingParams?g.cF(m.trackingParams):null,H5:Y.trackingParams?g.cF(Y.trackingParams):null,lZ:I&&I.trackingParams?g.cF(I.trackingParams):null,Lp:Iu(m.playlistThumbnail.thumbnails,258,290).url,customMessage:m.customMessage?
g.nr(m.customMessage):null,playlistVideoCount:g.nr(m.playlistVideoCount),title:m.playlistTitle?g.nr(m.playlistTitle):"",metaInfo:[m.channelName?g.nr(m.channelName):"",m.videoCountText?g.nr(m.videoCountText):""],url:Nl({pause_on_navigation:!t.context.videoData.isLivePlayback,target:"new",value:qRw(m.action)}),onClickCommand:null};xw(t,r)}else if(r.content?.videoInfoCardContentRenderer){if(!r.cueRanges.length)return;m=r.content?.videoInfoCardContentRenderer;Y=r.teaser.simpleCardTeaserRenderer;I=r.icon?
r.icon.infoCardIconRenderer:null;r={id:x,timestamp:t.K,type:"video",teaserText:g.nr(Y.message),teaserDurationMs:Number(r.cueRanges[0].teaserDurationMs),startMs:Number(r.cueRanges[0].startCardActiveMs),autoOpen:!!r.autoOpen,sessionData:mF(t,x,r,m),sponsored:!1,gK:G$(m,Y,m.action),wi:m.trackingParams?g.cF(m.trackingParams):null,H5:Y.trackingParams?g.cF(Y.trackingParams):null,lZ:I&&I.trackingParams?g.cF(I.trackingParams):null,Lp:Iu(m.videoThumbnail.thumbnails,258,290).url,videoDuration:m.lengthString?
g.nr(m.lengthString):null,customMessage:m.customMessage?g.nr(m.customMessage):null,title:m.videoTitle?g.nr(m.videoTitle):"",metaInfo:[m.channelName?g.nr(m.channelName):"",m.viewCountText?g.nr(m.viewCountText):""],isLiveNow:!!m.badge,url:Nl({pause_on_navigation:!t.context.videoData.isLivePlayback,target:"new",value:qRw(m.action)}),onClickCommand:null};xw(t,r)}t.K++},VtN=function(t,r){return g.GT(t.cards,x=>x.SX.id===r)},t2=function(t){g.D(t.U.getRootNode(),"ytp-cards-shopping-active",olm(t))},wh=function(t,
r){if(r=VtN(t,r))r===t.Z&&(t.Z=null),t.U.removeCueRange(r.SX.id),g.LD(r.By),g.F$(t.cards,r),t.sC(),t2(t)},rU=function(t,r,x){if(!t.D){t.oO.show();
t.rU=new g.B7(()=>{g.wn(t.context.U.getRootNode(),g.j$.IV_DRAWER_OPEN)},0);
t.rU.start();t.OC.S(t.B,"mousewheel",I=>{t.WN.start();I.preventDefault();I=I||window.event;let m=0;I.type=="MozMousePixelScroll"?m=0==(I.axis==I.HORIZONTAL_AXIS)?I.detail:0:window.opera?m=I.detail:m=I.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?I.wheelDeltaY/-30:I.wheelDeltaY/-1.2:I.wheelDelta/-1.6:I.wheelDeltaY/-3;if(I=m)t.B.scrollTop+=I});
t.D=!0;var Y=g.J1();Y&&t.RO&&t.L&&g.ri(Y,[t.RO,t.L]);r={TRIGGER_TYPE:r};for(const I of t.cards)I.aP||(I.aP=!0,OD8(t.context.logger,I.SX.gK.Fp,r)),Y&&g.ri(Y,[I.SX.wi]);Ja(t.U);x&&(t.Y=new g.B7(()=>{t.PN=t.J;t.hH.focus()},330),t.Y.start())}},X4D=function(t){g.tv(t.WE(),[g.j$.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.$I(t.U,t.W,5);t.v$();t.J=g.Tq("ytp-cards-button",t.U.getRootNode());t.hH=g.Tq("iv-drawer-close-button",t.W);t.isInitialized=!0},fJX=function(t){t.iV.push(g.IO("iv-teaser-shown",t.O$,t));
t.iV.push(g.IO("iv-teaser-hidden",t.gt,t));t.iV.push(g.IO("iv-teaser-clicked",t.RK,t));t.ZG=!0},ss1=function(t,r){t.N=r;
var x=t.U.getVideoData();if(!x)return!1;x=g.xA(x);if(x?.markersMap)for(let I=0;x?.markersMap.length>I;I++){var Y=x?.markersMap[I];if(Y.key==="ERROR_CORRECTION_MARKERS"&&(Y=Y.value?.markers)&&Y.length>0)return r.startMs=g.b(Y[0],g.hM4)?.timeRangeStartMillis||0,t.N=null,!0}return!1},DrD=function(t,r){switch(r.type){case "simple":t=t.uV;
var x=r.displayDomain?{A:"div",O:"iv-card-image-text",BN:r.displayDomain}:void 0;var Y=Wlt(r);x={A:"div",K8:["iv-card"],j:[{A:"a",O:"iv-click-target",V:{href:r.url?r.url.Z()||"":""},j:[Bb(r.imageUrl,x),{A:"div",O:"iv-card-content",j:[am("h2",void 0,r.title),Y]}]}]};x=new g.l(x);T$(t,g.Hy("iv-click-target",x.element),r,r.url);r=x;break;case "collaborator":t=t.uV;x={A:"div",K8:["iv-card","iv-card-channel"],j:[{A:"a",K8:["iv-click-target"],V:{href:r.url.Z()||"","data-ytid":r.channelId},j:[Bb(r.profileImageUrl),
{A:"div",O:"iv-card-content",j:[Hb(r),{A:"h2",O:"iv-card-primary-link",BN:r.title},SB(r)]}]}]};x=new g.l(x);T$(t,g.Hy("iv-click-target",x.element),r,r.url);r=x;break;case "playlist":t=t.uV;x={A:"div",K8:["iv-card","iv-card-playlist"],j:[{A:"a",O:"iv-click-target",V:{href:r.url.Z()||""},j:[Bb(r.Lp,{A:"div",O:"iv-card-image-overlay",j:[{A:"span",O:"iv-card-playlist-video-count",BN:r.playlistVideoCount}]}),{A:"div",O:"iv-card-content",j:[Hb(r),am("h2","iv-card-primary-link",r.title),SB(r)]}]}]};x=new g.l(x);
T$(t,g.Hy("iv-click-target",x.element),r,r.url);r=x;break;case "productListing":t=t.uV;var I=r.offers.length!=0;x=["iv-card"];Y="";var m=Wlt(r);I&&(x.push("iv-card-product-listing"),Y="iv-card-primary-link",m=r.offers[0],I=[],m.price&&I.push({A:"div",O:"iv-card-offer-price",BN:m.price}),m.merchant&&I.push({A:"div",O:"iv-card-offer-merchant",BN:m.merchant}),m={A:"div",j:I});I=r.url?r.url.Z()||"":"";x={A:"div",K8:x,V:{tabindex:"0"},j:[{A:"a",K8:["iv-card-image","iv-click-target"],V:{style:"background-image: url("+
r.imageUrl+");",href:I,"aria-hidden":"true",tabindex:"-1"}},{A:"div",O:"iv-card-content",j:[r.sponsored?{A:"div",O:"iv-card-sponsored",j:["Sponsored",{A:"div",O:"iv-ad-info-container",j:[{A:"div",O:"iv-ad-info",BN:"{{adInfo}}"},{A:"div",O:"iv-ad-info-icon-container",j:[{A:"div",O:"iv-ad-info-icon"},{A:"div",O:"iv-ad-info-callout"}]}]}]}:"",{A:"a",O:"iv-click-target",V:{href:I},j:[am("h2",Y,r.title),m]}]}]};x=new g.l(x);Y=g.AF("span");g.CD(Y,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
x.setContent(Y,"adInfo");T$(t,g.Hy("iv-click-target",x.element),r,r.url);r=x;break;case "video":t=t.uV;x=r.isLiveNow?{A:"span",K8:["yt-badge","yt-badge-live"],BN:"LIVE NOW"}:null;x={A:"div",K8:["iv-card","iv-card-video"],j:[{A:"a",O:"iv-click-target",V:{href:r.url?.Z()||""},j:[Bb(r.Lp,r.videoDuration?{A:"span",O:"iv-card-video-duration",BN:r.videoDuration}:void 0),{A:"div",O:"iv-card-content",j:[Hb(r),am("h2","iv-card-primary-link",r.title),SB(r),x]}]}]};x=new g.l(x);T$(t,g.Hy("iv-click-target",x.element),
r,r.url);r=x;break;default:return null}return r},RVe=function(t,r){if(!g.Gg(t.U.getRootNode(),"ytp-cards-teaser-shown")){if(t.Z!==r){var x=g.J1(),Y=t.Z?t.Z.SX.lZ:t.lZ;
x&&Y&&g.xd(x,[Y]);t.Z=r;t2(t)}(x=t.isInitialized&&t.WE().style.display=="none")||(x=t.context.U.getPlayerState(),Y=x===0&&t.context.U.getCurrentTime()===0,x=!(x===1||x===3||Y));x||r.SX.teaserDurationMs&&t.U.Ae(!0,{teaserText:r.SX.teaserText,durationMs:r.SX.teaserDurationMs,onClickCommand:r.SX.onClickCommand,Kp:r.SX.Kp??null});t.tH.isActive()||((!t.D||!t.WN.isActive()&&t.EC)&&kAw(t,r),t.tH.start(910+r.SX.teaserDurationMs))}},olm=function(t){return t.Z?t.Z.SX.type==="productListing":t.U.C("enable_wn_infocards")?
!!t.cards?.length&&g.TT(t.cards,r=>r.SX.type==="productListing"):g.TT(t.cards,r=>r.SX.type==="productListing")},kAw=function(t,r){t.G.DG?(r=new Pb([0,
t.B.scrollTop],[0,r.By.offsetTop],600,AFD),t.context.D.listen(r,"animate",x=>{t.B.scrollTop=x.y}),t.context.D.listen(r,"finish",x=>{t.B.scrollTop=x.y}),r.play()):(t.G.Gf(!0),t.B.scrollTop=r.By.offsetTop,t.G.Gf(!1))},F1=function(t){return t.Z&&t.Z.SX?t.Z.SX:t.cards[0]&&t.cards[0].SX?t.cards[0].SX:null},bD1=function(t){const r=t.annotation.data;
"start_ms"in r&&"end_ms"in r&&t.addCueRange(Number(r.start_ms),Number(r.end_ms),t.annotation.id,()=>{t.show()},()=>{t.hide()})},eVX=function(t,r){var x=wy$(r).width;
g.as(r,x);x=new sA(r,[x,r.offsetTop],[x-x,r.offsetTop],200,Fl8);g.Q(t,x);t.context.D.listen(x,"begin",()=>{g.x2(r,!0)});
x.play()},A2=function(t,r,x){x.stopPropagation();
vlw(t);No1(t,r);t.Z.focus()},Bot=function(t){const r=t.annotation.data;
if(t.annotation.style==="cta")var x=6;else if(t.annotation.style==="video"||t.annotation.style==="playlist")x=7;t.Y=r.collapsedelay_ms||t.Y;const Y=["iv-promo","iv-promo-inactive"];t.WE().setAttribute("aria-hidden","true");t.WE().setAttribute("aria-label","Promotion");t.WE().tabIndex=0;const I=t.annotation.xJ();let m;var F=r.image_url;F&&(m=t.createElement({A:"div",K8:["iv-promo-img","iv-click-target"]}),F=t.createElement({A:"img",V:{src:F,"aria-hidden":"true"}}),m.appendChild(F),r.video_duration&&
!r.is_live?(F=t.createElement({A:"span",O:"iv-promo-video-duration",BN:r.video_duration}),m.appendChild(F)):r.playlist_length&&(F=t.createElement({A:"span",O:"iv-promo-playlist-length",BN:r.playlist_length.toString()}),m.appendChild(F)),I&&lw(t,m,I,t.annotation.id,r.session_data,void 0,x));I?(F=t.createElement({A:"a",O:"iv-promo-txt"}),g.oa(F,I.Z()),t.Z=F):t.Z=t.createElement({A:"div",O:"iv-promo-txt"});let A,h,E,U;switch(t.annotation.style){case "cta":case "website":A=t.createElement({A:"p",j:[{A:"strong",
BN:r.text_line_1}]});h=t.createElement({A:"p",j:[{A:"span",O:"iv-promo-link",BN:r.text_line_2}]});if(F=r.text_line_3)Y.push("iv-promo-website-card-cta-redesign"),E=t.createElement({A:"button",K8:["iv-promo-round-expand-icon","ytp-button"]}),F=t.createElement({A:"button",K8:["iv-button","iv-promo-button"],j:[{A:"span",O:"iv-button-content",BN:F}]}),U=t.createElement({A:"div",O:"iv-promo-button-container"}),U.appendChild(F),I&&lw(t,t.WE(),I,t.annotation.id,r.session_data,void 0,x);g.wn(t.Z,"iv-click-target");
I&&lw(t,t.Z,I,t.annotation.id,r.session_data,void 0,x);break;case "playlist":case "video":A=t.createElement({A:"p",j:[{A:"span",BN:r.text_line_1}]}),h=t.createElement({A:"p",j:[{A:"strong",BN:r.text_line_2}]}),r.is_live&&(A=h,h=t.createElement({A:"span",K8:["yt-badge","iv-promo-badge-live"],BN:"LIVE NOW"})),g.wn(t.Z,"iv-click-target"),I&&lw(t,t.Z,I,t.annotation.id,r.session_data,void 0,x),Y.push("iv-promo-video")}A&&t.Z.appendChild(A);h&&t.Z.appendChild(h);t.K.appendChild(t.Z);U&&t.K.appendChild(U);
x=t.createElement({A:"div",O:"iv-promo-actions"});t.B=t.createElement({A:"button",K8:["iv-promo-expand","ytp-button"]});t.B.title="Expand";t.context.Z.listen(t.B,"click",n=>{A2(t,5E3,n)});
x.appendChild(t.B);g.x2(t.B,!1);t.context.Z.listen(t.WE(),"mouseover",t.WN,t);t.context.Z.listen(t.WE(),"mouseout",t.uV,t);t.context.Z.listen(t.WE(),"touchend",n=>{A2(t,5E3,n)});
t.D=t.createElement({A:"button",K8:["iv-promo-close","ytp-button"]});t.D.title="Close";t.context.Z.listen(t.D,"click",t.annotation.style==="cta"&&r.text_line_3?t.N:t.iV,t);x.appendChild(t.D);g.tv(t.WE(),Y);m&&(g.ER(t.WE(),m),E&&m.appendChild(E));g.ER(t.WE(),t.K);g.ER(t.WE(),x)},h2=function(t){t.W&&(g.jK.clearTimeout(t.W),t.W=null)},vlw=function(t){t.J.stop();
t.isCollapsed&&(g.xT(t.WE(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),t.isCollapsed=!1,t.Z&&t.Z.removeAttribute("aria-hidden"),g.x2(t.B,!1),g.x2(t.D,!0))},No1=function(t,r){t.W||(t.W=g.rI(function(){h2(this);
aJm(this)},r,t))},aJm=function(t){t.isCollapsed||t.L||t.W||(g.wn(t.WE(),"iv-promo-collapsed"),t.isCollapsed=!0,t.J.start())},OD8=function(t,r,x){r&&(x?EM(t,r.map(Y=>g.QZ(Y,x))):EM(t,r))},EM=function(t,r,x,Y){let I=1,m=void 0,F=-1;
if(x){let A=!1;m=()=>{I--;I||A||(clearTimeout(F),A=!0,x())};
F=setTimeout(()=>{A=!0;x()},1E3)}for(const A of r||[])I++,g.v0(A,m);
Y&&(I++,Y!==0&&t.U.sendVideoStatsEngageEvent(Y,m))},HD$=function(t){return t==="annotation-editor"||t==="live-dashboard"},SRt=function(t){t.W&&(t.player.removeEventListener("videodatachange",t.W),t.W=null)},Tos=function(t){t=t.createElement({A:"div",
K8:["annotation","annotation-type-custom"]});g.x2(t,!1);return t},nE=function(t,r){var x=!1,Y=r.getElementsByTagName("annotations");
if(Y&&!(Y.length<1)&&(Y=Y[0].getAttribute("itct"))){var I=g.J1();if(I){var m=g.Zf();m&&g.hz(g.NF)(void 0,I,m,[g.cF(Y)])}}r=r.getElementsByTagName("annotation");for(Y=0;Y<r.length;Y++){var F=lJL(t,r[Y]);I=null;try{a:{if(!F){I=null;break a}var A=F.id;m=/.+/;const M=typeof A==="string"&&m!=null&&A!=null&&A.match(m)?A:"",z=vb(F.type,GAe),p=vb(F.style,w4w),q=zVN(F.data),f=q.length!==0?JSON.parse(q):{};b:{var h=F.action;m=p4s;if(h==null){var E=null;break b}if(g.ZB(h)){F=[];for(const R of h){const O=m(R);
O&&F.push(O)}E=F;break b}const X=m(h);E=X?[X]:[]}m=E;I=M&&z?new thf(M,z,p,m,f):null}}catch(M){}if(I)if(I.type==="branding"||I.type==="promotion"){m=t;F=I;var U=Tos(m),n=null;switch(F.type){case "branding":if(m.player.X().aK)break;m.player.C("web_player_overlay_positioned_layout")?(U.setAttribute("data-overlay-order","11"),m.player.J7(U,4,!0)):m.B.element.appendChild(U);n=new r4L(U,UM(m),F);break;case "promotion":g.$I(m.player,U,4),n=new xC8(U,UM(m),F)}n&&n.MS();if(m=n)g.Q(t,m),t.Y[I.id]=m}else if(I.type===
"card"||I.type==="drawer"){t.Z||(t.Z=YZZ(t),g.Q(t,t.Z));if(I.type==="card"){U=t.Z;var L=(x=I)&&x.data&&x.data.card_type;I=x.data;if(L)switch(m=I.tracking||{},m={Fp:m.impression,click:m.click,close:m.close,qM:m.teaser_impression,Rd:m.teaser_click},F=I.tracking_params||{},n=null,L){case "collaborator":x={id:x.id,timestamp:I.timestamp||0,type:I.card_type,teaserText:I.teaser_text,teaserDurationMs:I.teaser_duration_ms,startMs:I.start_ms,autoOpen:I.auto_open||!1,sessionData:I.session_data||{},sponsored:I.sponsored||
!1,gK:m,wi:F.card?g.cF(F.card):null,H5:F.teaser?g.cF(F.teaser):null,lZ:F.icon?g.cF(F.icon):null,channelId:I.channel_id,customMessage:I.custom_message?I.custom_message:null,profileImageUrl:I.image_url,title:I.title,metaInfo:I.meta_info,url:Nl({pause_on_navigation:I.pause_on_navigation,target:I.target||"new",value:I.url}),onClickCommand:null};xw(U,x);break;case "playlist":x={id:x.id,timestamp:I.timestamp||0,type:I.card_type,teaserText:I.teaser_text,teaserDurationMs:I.teaser_duration_ms,startMs:I.start_ms,
autoOpen:I.auto_open||!1,sessionData:I.session_data||{},sponsored:I.sponsored||!1,gK:m,wi:F.card?g.cF(F.card):null,H5:F.teaser?g.cF(F.teaser):null,lZ:F.icon?g.cF(F.icon):null,Lp:I.image_url,playlistVideoCount:I.playlist_video_count,customMessage:I.custom_message?I.custom_message:null,title:I.title,metaInfo:I.meta_info,url:Nl({pause_on_navigation:I.pause_on_navigation,target:I.target||"new",value:I.url}),onClickCommand:null};xw(U,x);break;case "productListing":I.signin_url&&(n=Nl({target:"current",
value:I.signin_url}));L=[];const M=I.offers||[];for(let z=0;z<M.length;z++)L.push(new I9L(g.hr(M[z].merchant),g.hr(M[z].price)));x={id:x.id,timestamp:I.timestamp||0,type:I.card_type,teaserText:I.teaser_text,teaserDurationMs:I.teaser_duration_ms,startMs:I.start_ms,autoOpen:I.auto_open||!1,sessionData:I.session_data||{},sponsored:I.sponsored||!1,gK:m,wi:F.card?g.cF(F.card):null,H5:F.teaser?g.cF(F.teaser):null,lZ:F.icon?g.cF(F.icon):null,imageUrl:I.image_url,displayDomain:I.display_domain?I.display_domain:
null,showLinkIcon:!!I.show_link_icon,XY:I.button_icon_url?I.button_icon_url:null,title:I.title,customMessage:I.custom_message?I.custom_message:null,url:Nl({pause_on_navigation:I.pause_on_navigation,target:I.target||"new",value:I.url}),faH:n,LZX:I.signin_title?I.signin_title:void 0,OK8:I.signin_message?I.signin_message:void 0,offers:L,onClickCommand:null};xw(U,x);break;case "simple":x={id:x.id,timestamp:I.timestamp||0,type:I.card_type,teaserText:I.teaser_text,teaserDurationMs:I.teaser_duration_ms,
startMs:I.start_ms,autoOpen:I.auto_open||!1,sessionData:I.session_data||{},sponsored:I.sponsored||!1,gK:m,wi:F.card?g.cF(F.card):null,H5:F.teaser?g.cF(F.teaser):null,lZ:F.icon?g.cF(F.icon):null,imageUrl:I.image_url,displayDomain:I.display_domain?I.display_domain:null,showLinkIcon:!!I.show_link_icon,XY:I.button_icon_url?I.button_icon_url:null,title:I.title,customMessage:I.custom_message?I.custom_message:null,url:Nl({pause_on_navigation:I.pause_on_navigation,target:I.target||"new",value:I.url}),onClickCommand:null};
xw(U,x);break;case "video":x={id:x.id,timestamp:I.timestamp||0,type:I.card_type,teaserText:I.teaser_text,teaserDurationMs:I.teaser_duration_ms,startMs:I.start_ms,autoOpen:I.auto_open||!1,sessionData:I.session_data||{},sponsored:I.sponsored||!1,gK:m,wi:F.card?g.cF(F.card):null,H5:F.teaser?g.cF(F.teaser):null,lZ:F.icon?g.cF(F.icon):null,Lp:I.image_url,videoDuration:I.video_duration||null,customMessage:I.custom_message?I.custom_message:null,title:I.title,metaInfo:I.meta_info,isLiveNow:!!I.is_live_now,
url:Nl({pause_on_navigation:I.pause_on_navigation,target:I.target||"new",value:I.url}),onClickCommand:null},xw(U,x)}}else $rf(t.Z,I);x=!0}}x&&(Ja(t.player),t.G())},mCN=function(t){const r=t.player.X();
t=t.player.getVideoData();return(r.annotationsLoadPolicy||t.annotationsLoadPolicy)===1&&!t.hX||r.RO.get(t.videoId)||t.dH()||g.IK(t)?!0:!1},FRN=function(t,r){r=!r.isCued()&&!r.Z(1024);
t.B.Gf(r);t.D.Gf(r)},UCt=function(t,r){const x=r.videoId;
var Y=m=>{var F=t.loadNumber;t.K=null;t.loaded&&t.loadNumber===F&&t.player.getVideoData().videoId===x&&(m=g.so(m)&&m.responseXML?m.responseXML:null)&&(nE(t,m),g.wn(t.player.getRootNode(),"iv-module-loaded"))};
g.Jy()&&(Y=A48(t,Y));const I={format:"XML",onFinish:Y,onError:()=>{t.K=null},
urlParams:{}};r.isPharma&&(I.urlParams.pharma="1");I.method="POST";I.withCredentials=!0;(Y=t.player.X().RO.get(x))&&hEe(I,Y);Y=Y&&Y.qs;if(!r.hn||Y)t.W=()=>{if(!t.N)t.onVideoDataChange(I);const m=t.player.getVideoData();m?.Oc()&&!t.iV&&E2X(t,m)},t.player.addEventListener("videodatachange",t.W)},LE=function(t,r){var x=!1;
t.Z||(t.Z=YZZ(t),g.Q(t,t.Z));for(var Y of r.cards||[])Y.cardRenderer&&(Kls(t.Z,Y.cardRenderer),x=!0);x&&(t.player.getVideoData()?.Oc()||(x=t.Z,Y=r.headerText?g.nr(r.headerText):"",g.CD(x.dU,Y),x.J&&(x.U.C("player_tooltip_data_title_killswitch")?x.J.setAttribute("title",Y):x.J.setAttribute("data-tooltip-title",Y)),x.context.videoData.eventId&&(x.eventId=x.context.videoData.eventId),x.RO=r.trackingParams?g.cF(r.trackingParams):null,x.L=r.closeButton.infoCardIconRenderer.trackingParams?g.cF(r.closeButton.infoCardIconRenderer.trackingParams):
null,x.lZ=r.icon.infoCardIconRenderer.trackingParams?g.cF(r.icon.infoCardIconRenderer.trackingParams):null,t.G()),Ja(t.player))},E2X=function(t,r){if(r=r.getWatchNextResponse()?.cards?.cardCollectionRenderer)t.iV=!0,LE(t,r),r.headerText&&t.fI&&(r=g.nr(r.headerText),t.player.C("player_tooltip_data_title_killswitch")?t.fI.setAttribute("title",r):t.fI.setAttribute("data-tooltip-title",r))},A48=function(t,r){return(...x)=>{t.f8()||t.MS.push(g.R3.XW(()=>{r(...x)}))}},hEe=function(t,r){t.method="POST";
t.postParams=t.postParams||{};r.qs&&(t.postParams.ic_coll=r.qs);r.L7&&(t.postParams.ic_track=r.L7)},lJL=function(t,r){const x={};
for(var Y of r.attributes)x[Y.name]=Y.nodeValue;for(Y=0;Y<r.childNodes.length;Y++){var I=r.childNodes[Y];if(!g.pn(I)||I.nodeType!=1)continue;var m=void 0;if(x[I.tagName])m=x[I.tagName];else if(I.tagName==="data"){I.childNodes.length>0&&(m=I.childNodes[0].nodeValue,x[I.tagName]=typeof m==="string"?m.trim():m);continue}else m=[],x[I.tagName]=m;I&&I.tagName==="TEXT"?I.childNodes.length===1&&I.childNodes[0].nodeType===3?m.push(I.childNodes[0].nodeValue):m.push(""):I&&m.push(lJL(t,I))}return x},UM=function(t){if(!t.L){const r=
new n2m(t);
g.Q(t,r);const x=new g.I3(t);g.Q(t,x);t.L=new LRL(r,x,t.player.X(),t.player.getVideoData(),t.logger,t.player,t.XI)}return t.L},Mh1=function(t){const r=t.player.getVideoData();
if(r.m5){var x=t.player.X().RO.get(r.videoId);if(x){var Y={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:(I,m,F)=>{I=t.loadNumber;m=r.videoId;t.loaded&&t.loadNumber===I&&t.player.getVideoData().videoId===m&&(F=g.so(F)&&F.responseXML?F.responseXML:null)&&nE(t,F)}};
g.Jy()&&(Y.onFinish=A48(t,Y.onFinish));Y.postParams={ic_only:"1"};hEe(Y,x);t.N=!0;g.e_(r.m5,Y)}}},YZZ=function(t){const r=new g.l({A:"div"});
g.x2(r.element,!1);const x=new Cbt(t.player,r.element,UM(t));g.Q(x,r);r.C8(t.B.element);x.MS();return x},ii8=function(t,r,x,Y,I){if(!t.player.X().aK){var m=[];
r.navigationEndpoint&&g.b(r.navigationEndpoint,g.zM)&&g.b(r.navigationEndpoint,g.zM).browseId&&m.push(new JFD("openUrl","click",new yFD(`/channel/${g.b(r.navigationEndpoint,g.zM).browseId}`,"new",!0,!0)));var F=r.watermark.thumbnails[0];Y={channel_name:r.channelName,end_ms:r.endTimeMs,image_height:F.height,image_type:1,image_url:F.url,image_width:F.width,is_mobile:!1,session_data:{annotation_id:x,ei:I,feature:"iv",itct:r.trackingParams,src_vid:Y},start_ms:r.startTimeMs};if(r.subscribeButton&&g.b(r.subscribeButton,
g.Do)){Y.channel_id=g.b(r.subscribeButton,g.Do).channelId;r=g.b(r.subscribeButton,g.Do);F=I=null;r.subscribed?(r.subscriberCountWithUnsubscribeText&&(I=g.nr(r.subscriberCountWithUnsubscribeText)),r.subscriberCountText&&(F=g.nr(r.subscriberCountText))):(r.subscriberCountText&&(I=g.nr(r.subscriberCountText)),r.subscriberCountWithSubscribeText&&(F=g.nr(r.subscriberCountWithSubscribeText)));const A=g.b(r.signInEndpoint?.commandMetadata,g.gV)?.url||"";r={subscribeText:g.nr(r.unsubscribedButtonText),subscribeCount:I||
"",unsubscribeText:g.nr(r.subscribedButtonText),unsubscribeCount:F||"",enabled:r.enabled||!1,classic:!1,subscribed:r.subscribed||!1,feature:"iv",signInUrl:A};Y.standalone_subscribe_button_data=r}m=new thf(x,"branding","branding",m,Y);Y=Tos(t);t.player.C("web_player_overlay_positioned_layout")?(Y.setAttribute("data-overlay-order","11"),t.player.J7(Y,4,!0)):t.B.element.appendChild(Y);m=new r4L(Y,UM(t),m);m.MS();g.Q(m,m);t.Y[x]=m}};
g.jE.prototype.Ae=g.xh(36,function(t,r){const x=g.HT(this.PE());x&&x.Ae(t,r)});
var QS={},Wb=null;g.X6(Pb,g.my);g.J=Pb.prototype;g.J.getDuration=function(){return this.duration};
g.J.play=function(t){if(t||this.Z==0)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;gh(this);this.startTime=t=g.q4();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.W=this.startTime;this.progress||this.zR();this.rM("play");this.isPaused()&&this.rM("resume");this.Z=1;const r=g.WB(this);r in QS||(QS[r]=this);xrt();YRm(this,t);return!0};
g.J.stop=function(t){gh(this);this.Z=0;t&&(this.progress=1);IJX(this,this.progress);this.onStop();this.Fi()};
g.J.pause=function(){this.isPlaying()&&(gh(this),this.Z=-1,this.rM("pause"))};
g.J.DE=function(){this.Z==0||this.stop(!1);this.rM("destroy");Pb.oi.DE.call(this)};
g.J.destroy=function(){this.dispose()};
g.J.P$=function(){this.rM("animate")};
g.J.rM=function(t){this.dispatchEvent(new mry(t,this))};
g.X6(mry,g.Yb);g.X6(ql,Pb);ql.prototype.D=function(){};
ql.prototype.P$=function(){this.D();ql.oi.P$.call(this)};
ql.prototype.Fi=function(){this.D();ql.oi.Fi.call(this)};
ql.prototype.zR=function(){this.D();ql.oi.zR.call(this)};
g.X6(sA,ql);sA.prototype.D=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var n2m=class extends g.G9{constructor(t){super();this.B=t||window;this.Z=[]}listen(t,r,x,Y){x=(0,g.gS)(x,Y||this.B);t=g.l0(t,r,x);this.Z.push(t);return t}Eb(t,r,x,Y){x=(0,g.gS)(x,Y||this.B);t=ttm(t,r,x);this.Z.push(t);return t}LU(t){g.GF(t);g.F$(this.Z,t)}removeAll(){g.GF(this.Z);this.Z.length=0}DE(){this.removeAll();super.DE()}};var y4L=class extends g.OS{constructor(t){super(t);this.W=this.endscreen=null;this.B={};this.Y={};this.J=this.D=null;this.L=[];this.Z=null;this.iV=!0;this.K=0;t=t.X();this.G=g.MG(t)||g.jm(t);this.events=new g.pG(this);g.Q(this,this.events);this.events.S(this.player,g.DK("creatorendscreen"),this.onCueRangeEnter);this.events.S(this.player,g.Xs("creatorendscreen"),this.onCueRangeExit);this.events.S(this.player,"resize",this.cE);this.events.S(window,"focus",this.N);this.load();const r=g.AF("STYLE");(g.ah("HEAD")[0]||
document.body).appendChild(r);this.addOnDisposeCallback(()=>{g.LD(r)});
r.sheet&&(r.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),r.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))}load(){super.load();if(!kS(this)){var t=g.Y8h(this.player.getVideoData());t?(t=f_(t,Els(this)),Rm(this,t,!1)):MtZ(this)}}unload(){Rm(this,null);this.W&&(this.W.abort(),this.W=null);super.unload()}xN(t,r){return kS(this)?t==="loadCustomEndscreenRenderer"?(t=f_(r,"new"),Rm(this,t),!0):null:null}getOptions(){return kS(this)?["loadCustomEndscreenRenderer"]:[]}cE(){if(this.endscreen&&this.endscreen.elements){var t=this.player.getVideoContentRect();if(t&&t.width!==0&&t.height!==0){var r=this.player.getPlayerSize();
if(r&&r.width!==0&&r.height!==0){var x=t.width/t.height;var Y=0;var I=-1;for(var m=0;m<jbL.length;m++){var F=Math.abs(r.width-jbL[m]);if(I===-1||Y>=F)I=m,Y=F}Y=dC1[I];this.D&&g.Va(this.D.element,"outline-width",Math.max(r.width,r.height)+"px");for(r=0;r<this.endscreen.elements.length;++r){m=this.endscreen.elements[r].id;I=this.B[m];F=this.Y[m];if(!I||!F)continue;const h=F.width*x/F.aspectRatio;var A=Math.round(F.width*t.width);m=Math.round(h*t.height);const E=t.left+Math.round(F.left*t.width),U=t.top+
Math.round(F.top*t.height);g.t4(I.element,A,m);g.as(I.element,E,U);g.xT(I.element,zEt);A>256||m>256?g.wn(I.element,"ytp-ce-large-round"):A>96||m>96?g.wn(I.element,"ytp-ce-medium-round"):g.wn(I.element,"ytp-ce-small-round");g.xT(I.element,c4X);A=F.left+F.width/2;F=F.top+h/2;g.wn(I.element,A<=.5&&F<=.5?"ytp-ce-top-left-quad":A>.5&&F<=.5?"ytp-ce-top-right-quad":A<=.5&&F>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.xT(I.element,dC1);g.wn(I.element,Y);(I=g.SQ(document,"div","ytp-ce-expanding-overlay-body",
I.element)[0])&&g.Va(I,"height",`${m}px`)}}}}}onCueRangeEnter(t){if(this.endscreen)if(t.getId()==="ytp-ce-in-endscreen")bw(this,this.endscreen.impressionUrls),(t=g.J1())&&this.endscreen.visualElement&&g.tN(t,this.endscreen.visualElement),this.Z&&(g.wn(this.Z,"ytp-ce-element-show"),this.Z.removeAttribute("aria-hidden"),this.player.ov()?g.wn(this.Z,"ytp-ce-hide-button-lower"):g.rL(this.Z,"ytp-ce-hide-button-lower"));else{t=t.getId().substring(15);var r=this.B[t],x=this.Y[t];g.wn(r.element,"ytp-ce-element-show");
r.element.removeAttribute("aria-hidden");r=this.player.getRootNode();g.wn(r,"ytp-ce-shown");bw(this,x.impressionUrls);(r=g.J1())&&g.tN(r,x.visualElement);this.player.X().L&&g.iC(this.player,"endscreenelementshown",t)}}onCueRangeExit(t){if(t.getId()==="ytp-ce-in-endscreen")this.Z&&(g.rL(this.Z,"ytp-ce-element-show"),this.Z.setAttribute("aria-hidden","true"));else{t=t.getId().substring(15);var r=this.B[t];g.rL(r.element,"ytp-ce-element-show");r.element.setAttribute("aria-hidden","true");r=this.player.getRootNode();
g.rL(r,"ytp-ce-shown");this.player.X().L&&g.iC(this.player,"endscreenelementhidden",t)}}N(t){t.target===window&&(new g.B7(()=>{for(const r of Object.values(this.B))g.xT(r.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()}Gf(t){for(const r of Object.values(this.B))t?r.element.setAttribute("hidden",""):r.element.removeAttribute("hidden")}F1(t){this.Z&&this.player.getRootNode().removeChild(this.Z);
t&&(g.wn(t,"ytp-ce-hide-button-container"),this.Z=t,g.$I(this.player,this.Z,4))}},jbL=[346,426,470,506,570,640,853,1280,1920],dC1="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),c4X=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],zEt=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var yFD=class{constructor(t,r,x,Y){this.value=t;this.target=r;this.showLinkIcon=x;this.B=Y}Z(){return this.value?this.value:null}},cFD={RW:"current",CL:"new"};var JFD=class{constructor(t,r,x){this.type=t;this.trigger=r;this.url=x}},uiy={CLOSE:"close",z7:"openUrl",SUBSCRIBE:"subscribe"},ZDf={QI:"click",CLOSE:"close",XE:"hidden",xS8:"rollOut",lEX:"rollOver",dS8:"shown"};var thf=class{constructor(t,r,x,Y,I){this.id=t;this.type=r;this.style=x;this.data=I;this.action=Y||[]}xJ(){const t=Qse(this,r=>r.type==="openUrl"&&r.url!=null);
return t?t.url:null}},w4w={Qj:"anchored",P4:"branding",CHANNEL:"channel",UK:"cta",Hk:"highlightText",yg:"label",PLAYLIST:"playlist",POPUP:"popup",WwE:"speech",SUBSCRIBE:"subscribe",ErH:"title",VIDEO:"video",ZUU:"website"},GAe={P4:"branding",jN:"card",z4:"drawer",VK:"highlight",m_:"marker",i88:"promotion",TEXT:"text",wmU:"widget"};var upL=[".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}"],
Zi8=[".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}"];var J4w=class{constructor(t,r){this.context=t;this.Z=r}};var I9L=class{constructor(t,r){this.merchant=t;this.price=r}};var pdm=class extends g.G9{constructor(t,r){super();this.element=t;this.context=r;this.QL=!1;this.zX=new Map;this.GX=new Map;this.context.U.addEventListener(g.DK("annotations_module"),x=>{(x=this.zX.get(x))&&x.apply(this)});
this.context.U.addEventListener(g.Xs("annotations_module"),x=>{(x=this.GX.get(x))&&x.apply(this)})}addCueRange(t,r,x,Y,I){t=new g.aK(t,r,{id:x,
namespace:"annotations_module"});Y&&this.zX.set(t,Y);I&&this.GX.set(t,I);this.context.U.iZ([t],1)}MS(){this.context.B.subscribe("resize",this.sC,this)}WE(){return this.element}HN(t,r,x,Y,I,m){if(this.QL)return!1;m&&(m.stopPropagation(),m.preventDefault());this.navigate(t,x,Y,I);return!1}show(){}hide(){}destroy(){g.LD(this.WE())}sC(){}navigate(t,r,x,Y){const I=t.Z();if(I){var m=PWZ(I,t.target),F=()=>{t.B&&this.context.U.pauseVideo();const A=this.context.videoData.uK||!1,h=g.j_(I||"");A&&h&&(h.v||h.list)?
this.context.U.CQ(h.v,r,h.list,!1):g.x7(I||"",m==="current"?"_top":void 0,r)};
m==="new"&&(F(),F=null);EM(this.context.logger,x,F,Y);gl$(I)||(x=g.J1(),Y=r.itct,x&&Y&&g.Yd(x,g.cF(Y)))}}DE(){this.zX.clear();this.GX.clear();super.DE()}createElement(t){t=new g.l(t);g.Q(this,t);return t.element}};var Cbt=class extends pdm{constructor(t,r,x){super(r,x);this.U=t;this.eventId=null;this.ZG=this.EC=this.zf=this.D=this.isInitialized=!1;this.cards=[];this.hH=this.J=this.PN=this.Y=this.rU=this.Z=null;this.iV=[];this.N=this.L=this.lZ=this.RO=null;this.K=0;this.WN=new g.B7(()=>{},x.e8.TK?4E3:3E3);
g.Q(this,this.WN);this.tH=new g.B7(()=>{});
g.Q(this,this.tH);this.uV=new J4w(x,(Y,I,m,F,A,h)=>{lw(this,Y,I,m,F,A,h)});
this.G=new g.l({A:"div",O:"iv-drawer",V:{id:"iv-drawer"},j:[{A:"div",O:"iv-drawer-header",V:{"aria-role":"heading"},j:[{A:"span",O:"iv-drawer-header-text"},{A:"button",K8:["iv-drawer-close-button","ytp-button"],V:{"aria-label":"Hide cards",tabindex:"0"}}]},{A:"div",O:"iv-drawer-content"}]});g.Q(this,this.G);this.W=this.G.element;this.oO=new g.HE(this.G,330);g.Q(this,this.oO);this.dU=g.Tq("iv-drawer-header-text",this.W);this.B=g.Tq("iv-drawer-content",this.W);this.addCueRange(0,x.videoData.lengthSeconds*
1E3,"",()=>{this.zf&&rU(this,"YOUTUBE_DRAWER_AUTO_OPEN")},()=>{(this.zf=this.D)&&Yw(this)});
this.OC=new g.pG(this);g.Q(this,this.OC);this.U.addEventListener("videodatachange",this.FA.bind(this))}FA(){this.N&&xw(this,this.N)}isAvailable(){var t;if(t=!!this.cards.length)(t=this.U.getRootNode())?(t=g.rX(t),t=173<t.width&&173<t.height):t=!1;return t}sC(){const t=this.isAvailable();g.x2(this.WE(),t);g.D(this.context.U.getRootNode(),g.j$.IV_DRAWER_ENABLED,t);Ja(this.U)}destroy(){this.U.Ae(!1);try{this.U.getRootNode().removeChild(this.W)}catch(t){}g.m7(this.iV);this.OC.B();this.rU&&this.rU.dispose();
this.Y&&this.Y.dispose();super.destroy()}v$(){this.context.Z.listen(g.Tq("iv-drawer-close-button",this.W),"click",this.IK,this);this.context.Z.listen(this.B,"touchend",()=>{this.WN.start()});
this.context.Z.listen(this.B,"scroll",this.oK,this);this.context.B.subscribe("onHideControls",()=>{this.EC=!0});
this.context.B.subscribe("onShowControls",()=>{this.EC=!1});
this.context.B.subscribe("onVideoAreaChange",()=>{this.EC=g.Gg(this.U.getRootNode(),"ytp-autohide")});
this.iV.push(g.IO("iv-button-shown",this.aK,this));this.iV.push(g.IO("iv-button-hidden",this.j0,this));fJX(this)}findLastIndex(t){if(this.cards.length===0)return 0;const r=g.wS(this.cards,x=>t.SX.startMs>x.SX.startMs||t.SX.startMs===x.SX.startMs&&t.SX.timestamp>=x.SX.timestamp?!0:!1);
return r===-1?0:r+1}IK(){if(this.D){EM(this.context.logger,F1(this).gK.close);var t=g.J1();t&&this.L&&g.Yd(t,this.L);Yw(this)}}oK(){g.D(this.W,"iv-drawer-scrolled",this.B.scrollTop>0)}aK(){const t=g.J1();var r=F1(this);r=r?r.lZ:this.lZ;t&&r&&g.ri(t,[r])}j0(){const t=g.J1();var r=F1(this);r=r?r.lZ:this.lZ;t&&r&&g.xd(t,[r])}O$(){const t=F1(this);EM(this.context.logger,t.gK.qM);const r=g.J1();if(r&&t)if(this.U.C("web_infocards_teaser_show_logging_fix")){const x=[];t.H5&&x.push(t.H5);t.lZ&&x.push(t.lZ);
x.length>0&&g.ri(r,x)}else g.ri(r,[t.H5,t.lZ])}gt(){const t=g.J1(),r=F1(this);t&&r&&g.xd(t,[r.H5])}RK(t){const r=F1(this),x=g.J1();this.Z?t?(t=this.context.logger,EM(t,r.gK.Rd),t.U.sendVideoStatsEngageEvent(4,void 0),x&&r.H5&&g.Yd(x,r.H5)):(t=this.context.logger,EM(t,r.gK.Rd),t.U.sendVideoStatsEngageEvent(4,void 0),x&&r.lZ&&g.Yd(x,r.lZ)):(t=this.context.logger,EM(t,r.gK.Rd),t.U.sendVideoStatsEngageEvent(4,void 0),x&&this.lZ&&g.Yd(x,this.lZ))}};var Qbm=class extends pdm{constructor(t,r,x){super(t,r);this.annotation=x;this.isActive=!1}MS(){super.MS();bD1(this)}show(){super.show();const t=g.J1();var r=this.annotation.data;t&&r&&(r=r.session_data)&&g.ri(t,[g.cF(r.itct)])}hide(){super.hide();const t=g.J1();var r=this.annotation.data;t&&r&&(r=r.session_data)&&g.xd(t,[g.cF(r.itct)])}};var r4L=class extends Qbm{constructor(t,r,x){super(t,r,x);this.Z=null;this.D=!1;this.B=null}show(){if(!this.isActive){super.show();if(!this.D){g.wn(this.WE(),"iv-branding");const t=this.annotation.data;this.Z=this.createElement({A:"img",K8:["branding-img","iv-click-target"],V:{"aria-label":"Channel watermark",src:t.image_url,width:t.image_width,height:t.image_height}});g.x2(this.Z,!1);const r=this.createElement({A:"button",K8:["branding-img-container","ytp-button"]});r.appendChild(this.Z);this.WE().appendChild(r);
const x=this.annotation.xJ();x&&lw(this,r,x,this.annotation.id,t.session_data);this.D=!0}g.x2(this.WE(),!0);this.isActive=!0;if(this.Z){try{eVX(this,this.Z)}catch{}g.wn(this.context.U.getRootNode(),"ytp-branding-shown");this.context.U.getRootNode().style.setProperty("--branding-image-width",`${this.Z.getAttribute("width")}px`)}}}hide(){this.isActive&&(super.hide(),g.x2(this.WE(),!1),this.isActive=!1,g.rL(this.context.U.getRootNode(),"ytp-branding-shown"))}destroy(){this.B&&(this.B.dispose(),this.B=
null);g.rL(this.context.U.getRootNode(),"ytp-branding-shown");super.destroy()}};var LRL=class{constructor(t,r,x,Y,I,m,F){this.Z=t;this.D=r;this.e8=x;this.videoData=Y;this.logger=I;this.U=m;this.B=F}};var xC8=class extends Qbm{constructor(t,r,x){super(t,r,x);this.L=this.isCollapsed=this.G=!1;this.Y=5E3;this.B=this.D=this.Z=this.W=null;this.K=this.createElement({A:"div",K8:["iv-promo-contents"]});this.J=new g.B7(()=>{this.Z.setAttribute("aria-hidden","true");g.x2(this.D,!1);g.x2(this.B,!0)},700,this);
g.Q(this,this.J)}show(){this.isActive||(super.show(),this.G||(Bot(this),this.G=!0),g.x2(this.WE(),!0),g.rI(function(){g.rL(this.WE(),"iv-promo-inactive")},100,this),this.WE().removeAttribute("aria-hidden"),this.isActive=!0,h2(this),vlw(this),No1(this,this.Y))}hide(){this.isActive&&(g.wn(this.WE(),"iv-promo-inactive"),this.isActive=!1,this.WE().setAttribute("aria-hidden","true"))}HN(t,r,x,Y,I,m){return this.isCollapsed?!1:super.HN(t,r,x,Y,I,m)}WN(t){this.L=!0;
A2(this,500,t)}uV(){this.L=!1;aJm(this)}iV(t){t.stopPropagation();this.hide()}N(t){t.stopPropagation();h2(this);this.isCollapsed=!0;g.wn(this.WE(),"iv-promo-collapsed-no-delay");this.J.start()}destroy(){this.J.dispose();super.destroy()}};var WR8=class{constructor(t){this.U=t}};g.bd("annotations_module",class extends g.OS{constructor(t){super(t);this.iV=this.N=!1;this.loadNumber=0;this.Y={};this.logger=new WR8(this.player);this.J=new g.pG(this);this.K=this.W=null;this.events=new g.pG(this);this.fI=this.L=this.Z=null;this.MS=[];g.Q(this,this.J);this.J.S(this.player,"onVideoAreaChange",()=>{this.publish("onVideoAreaChange")});
this.J.S(this.player,"onHideControls",()=>{this.publish("onHideControls")});
this.J.S(this.player,"onShowControls",()=>{this.publish("onShowControls")});
this.J.S(this.player,"resize",x=>{this.publish("resize",x)});
this.J.S(this.player,"presentingplayerstatechange",x=>{this.publish("presentingplayerstatechange",x)});
this.subscribe("presentingplayerstatechange",this.WN,this);this.subscribe("resize",this.G,this);this.player.X().RO.subscribe("vast_info_card_add",this.uV,this);g.Q(this,this.events);this.sC=this.createElement({A:"div",O:"video-custom-annotations"});this.B=new g.l({A:"div",K8:["ytp-player-content","ytp-iv-player-content"]});g.Q(this,this.B);g.$I(this.player,this.B.element,4);this.B.hide();this.D=new g.l({A:"div",K8:["ytp-iv-video-content"]});g.Q(this,this.D);t=this.createElement({A:"div",O:"video-annotations"});
t.appendChild(this.sC);this.D.element.appendChild(t);this.Eq()?this.load():this.player.C("web_fix_annotations")&&(this.W=()=>{this.loaded||this.f8()||!this.Eq()||(SRt(this),this.load())},this.player.addEventListener("videodatachange",this.W));
const r=this.createElement({A:"style"});(g.ah("HEAD")[0]||document.body).appendChild(r);this.addOnDisposeCallback(()=>{g.LD(r)});
if(t=r.sheet){for(const x of upL)t.insertRule(x,0);for(const x of Zi8)t.insertRule(x,0)}}xN(t,r){if(!HD$(this.player.X().playerStyle))return null;switch(t){case "loadCustomAnnotationsXml":return(t=g.JK(r))&&nE(this,t),!0;case "removeCustomAnnotationById":return r&&this.Z&&(wh(this.Z,r),Ja(this.player)),!0}return null}getOptions(){return HD$(this.player.X().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]}Eq(){const t=this.player.getVideoData(),r=t.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer;
return t.uK||this.player.isMutedByEmbedsMutedAutoplay()?!1:this.player.C("web_fix_annotations")?mCN(this)?r?.isWatermarkEnforced===!0?!0:r?.isAnnotationsEnabled??!1:!1:mCN(this)}G(){if(this.D){var t=this.player.mf().getVideoContentRect(!0);g.t4(this.D.element,t.width,t.height);g.as(this.D.element,t.left,t.top)}if(this.Z){var r=this.player.mR();t=this.Z;r=r.width;g.D(t.W,"iv-drawer-small",r<=426);g.D(t.W,"iv-drawer-big",r>=1280)}}WN(t){FRN(this,t.state);t.state.Z(2)&&(this.ov()&&this.bM()&&this.player.getPresentingPlayerType()!==
2&&this.P1(!1),this.Ae(!1))}load(){super.load();FRN(this,this.player.getPlayerStateObject());this.loadNumber++;const t=this.player.getVideoData();UCt(this,t);g.$I(this.player,this.D.element,4);this.G();var r=g.IK(t);const x=t.dH();if(this.player.C("web_fix_annotations")){if(r&&(r.featuredChannel&&ii8(this,r.featuredChannel,r.annotationId||"branding",t.videoId||null,t.eventId||null),r=this.player.getVideoData().getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer,r?.isWatermarkEnforced&&!r?.isAnnotationsEnabled))return;
x&&LE(this,x)}else x&&LE(this,x),r&&r.featuredChannel&&ii8(this,r.featuredChannel,r.annotationId||"branding",t.videoId||null,t.eventId||null);this.fI=g.Tq("ytp-cards-button",this.player.getRootNode());t.Oc()&&E2X(this,t)}onVideoDataChange(){}unload(){this.player.Oh("annotations_module");for(const t of Object.keys(this.Y))this.Y[t].destroy();this.L=null;this.Z&&(this.Z.destroy(),this.Z=null,Ja(this.player));this.N=!1;this.K&&(this.K.abort(),this.K=null);this.iV=!1;this.Y={};this.B.hide();super.unload();
this.D.detach();SRt(this)}uV(t){t===this.player.getVideoData().videoId&&(this.loaded?Mh1(this):this.load())}ov(){return this.Z?.isAvailable()||this.iV}bM(){return!!this.Z&&this.Z.D}P1(t,r=!1,x){this.ov();this.Z&&(t?x?rU(this.Z,x,r):rU(this.Z,"YOUTUBE_DRAWER_AUTO_OPEN",r):Yw(this.Z))}Ae(t,r){this.player.publish(t?"cardsteasershow":"cardsteaserhide",r)}DE(){this.player.X().RO.unsubscribe("vast_info_card_add",this.uV,this);g.rL(this.player.getRootNode(),g.j$.IV_DRAWER_OPEN);var t=this.MS,r=g.R3;for(let x=
0,Y=t.length;x<Y;x++)r.T8(t[x]);this.MS.length=0;super.DE()}createElement(t){t=new g.l(t);g.Q(this,t);return t.element}});g.bd("creatorendscreen",y4L);})(_yt_player);
