(function(g){var window=this;'use strict';var PbX=async function(t,r,x){t.B=g.e_(r,x)},Mo=function(t){t.isActive()||t.start()},CE=function(t,r){return r?t.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},qZt=function(t){return g.JW(t)||t.C("web_enable_caption_language_preference_stickiness")},sbw=function(t,r){const x=new g.H5;
x.languageCode=t.languageCode;x.languageName=t.languageName;x.name=t.name;x.displayName=t.displayName;x.kind=t.kind;x.isDefault=!1;x.Z=t.Z;x.isTranslateable=t.isTranslateable;x.vssId=t.vssId;x.url=t.url;x.translationLanguage=r;t.xtags&&(x.xtags=t.xtags);t.captionId&&(x.captionId=t.captionId);return x},DC$=async function(t,r){t=t+"|"+r;
r=await g.Eq();if(!r)throw g.Vc("gct");return(await g.Ad(r)).get("captions",t)},XdL=function(t,r,x){DC$(t,r).then(Y=>{Y&&x(Y.trackData,new g.H5(Y.metadata))})},iy=function(t){if(!f9s.test(t))throw Error("'"+t+"' is not a valid hex color");
t.length==4&&(t=t.replace(kkm,"#$1$1$2$2$3$3"));t=t.toLowerCase();t=parseInt(t.slice(1),16);return[t>>16,t>>8&255,t&255]},REs=function(){var t={};
let r="suggest_correction"in g.fN?g.fN.suggest_correction:"Edit caption";r=r||"";for(let x in t){const Y=()=>String(t[x]);
r=r.replace(new RegExp("\\$\\{"+x+"\\}","gi"),Y);r=r.replace(new RegExp("\\$"+x,"gi"),Y)}return r},jj=function(){return g.mq("yt-player-caption-display-settings")},$Cs=function(t,r){let x=g.cD(t.segments,r);
x>=0||x<0&&(-x-1)%2===1||(x=-x-1,x>0&&r-t.segments[x-1]===1&&x<t.segments.length&&t.segments[x]-r===1?(g.me(t.segments,x),g.me(t.segments,x-1)):x>0&&r-t.segments[x-1]===1?t.segments[x-1]=r:x<t.segments.length&&t.segments[x]-r===1?t.segments[x]=r:(g.i8(t.segments,x,0,r),g.i8(t.segments,x+1,0,r)))},KR1=function(t){return t.Z&&t.Z.J?t.Z.J+t.player.vE()<t.player.getCurrentTime():!1},VhX=function(t,r){if(t.policy.u2&&t.player.GG()){var x=g.Od(r,t.policy,{});
x.set("pot",t.player.GG());x=x.xJ()}else x=g.Od(r,t.policy,{}).xJ();const Y={format:"RAW",withCredentials:!0};if(t.policy.RO){Y.method="POST";const F=r.W;F&&Object.keys(F).length>0?Y.postBody=g.Ht(F,g.s8):Y.postBody=(0,g.y3)([120,0])}t.J&&(Y.responseType="arraybuffer");let I=++t.MS;const m=(0,g.e)();t.B=g.lN(x,Y,3,100,-1,F=>{F.errorCode==="net.timeout"&&t.player.ZE("capnt",{rn:I++})}).then(F=>{if(t.policy.nO&&I%100===1){var A=(0,g.e)();
t.player.ZE("caprsp",{rn:I,ms:A-m,kb:(F.xhr.responseText.length/1024).toFixed()})}a:{F=F.xhr;t.f8();if(t.D){var h=!(t.J?F.response:F.responseText)||F.status>=400;if(A=g.Tih(F)){F=g.Od(t.D,t.policy,{});t.D.eY(F,A);VhX(t,t.D);break a}h?t.player.ZE("capfail",{status:F.status}):(g.Pg("fcb_r",(0,g.e)(),t.player.getVideoData()?.iV||""),A=t.D.Fb[0],h=A.yL,t.L!=null&&t.Y!==h&&(t.J?t.L(F.response,(A.startTime+t.player.vE())*1E3):t.L(F.responseText,(A.startTime+t.player.vE())*1E3),t.Y=h))}t.D=null;t.B=null}}).j5(F=>
{t.D=null;
t.B=null;t.player.ZE("capfail",{rn:I,status:F.xhr?.status})});
t.D=r;$Cs(t.W,t.D.Fb[0].yL)},o2y=function(t,r){return r!=null&&r in t.B.Z?t.B.Z[r]:null},Oi8=function(t,r,x){const Y=[];
for(const I in t.B.Z){if(!t.B.Z.hasOwnProperty(I))continue;const m=t.B.Z[I];if(g.N7(m,x||null)){const F=m.info.captionTrack;F&&F.languageCode===r&&Y.push(m)}}return Y.length?Y[0]:null},eEN=function(t,r){const x=[];
for(const I in t.B.Z){if(!t.B.Z.hasOwnProperty(I))continue;var Y=t.B.Z[I];if(g.N7(Y,r||null)){let m=Y.info.id,F=m,A=`.${m}`,h="",E="";if(Y=Y.info.captionTrack)m=Y.languageCode,F=Y.displayName,A=Y.vssId,h=Y.kind,E=Y.id;else{{Y=m;let U=g.Jsy.get(Y);U==null&&(U=biX[Y]||biX[Y.replace(/-/g,"_")],g.Jsy.set(Y,U));Y=U}F=Y||F}x.push(new g.H5({id:I,languageCode:m,languageName:F,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:A,kind:h,captionId:E}))}}return x},v21=function(t,r,x,Y){let I=r/360*16;
r>=t&&(t=640,Y>x*1.3&&(t=480),I=x/t*16);return I},NX$=function(t){let r=1+.25*(t.fontSizeIncrement||0);
if(t.offset===0||t.offset===2)r*=.8;return r},BXt=function(t,r){let x="vertical-rl";
t.Z.KO===1&&(x="vertical-lr");g.Ub&&(x=x==="vertical-lr"?"tb-lr":"tb-rl");g.Va(r,"-o-writing-mode",x);g.Va(r,"-webkit-writing-mode",x);g.Va(r,"writing-mode",x);g.Va(r,"text-orientation","upright");g.wn(r,"ytp-vertical-caption");t.B.params.Li===3&&(g.Va(r,"text-orientation",""),g.Va(r,"transform","rotate(180deg)"))},a9w=function(t,r){const x={};
var Y=r.background?r.background:t.Z.ZP.background;if(r.backgroundOpacity!=null||r.background){var I=r.backgroundOpacity!=null?r.backgroundOpacity:t.Z.ZP.backgroundOpacity;Y=iy(Y);x.background="rgba("+Y[0]+","+Y[1]+","+Y[2]+","+I+")";t.aK&&(x["box-decoration-break"]="clone",x["border-radius"]=`${t.HN/8}px`)}if(r.fontSizeIncrement!=null||r.offset!=null)x["font-size"]=`${t.zX*NX$(r)}px`;Y=1;I=r.color||t.Z.ZP.color;if(r.color||r.textOpacity!=null)I=iy(I),Y=r.textOpacity==null?t.Z.ZP.textOpacity:r.textOpacity,
I="rgba("+I[0]+","+I[1]+","+I[2]+","+Y+")",x.color=I,x.fill=I;var m=r.charEdgeStyle;m===0&&(m=void 0);if(m){I=`rgba(34, 34, 34, ${Y})`;let h=`rgba(204, 204, 204, ${Y})`;r.Dj&&(h=I=r.Dj);const E=t.zX/16/2,U=Math.max(E,1);var F=Math.max(2*E,1),A=Math.max(3*E,1);const n=Math.max(5*E,1);Y=[];switch(m){case 4:for(;A<=n;A+=E)Y.push(`${F}px ${F}px ${A}px ${I}`);break;case 1:F=window.devicePixelRatio>=2?.5:1;for(m=U;m<=A;m+=F)Y.push(`${m}px ${m}px ${I}`);break;case 2:Y.push(`${U}px ${U}px ${h}`);Y.push(`-${U}px -${U}px ${I}`);
break;case 3:for(A=0;A<5;A++)Y.push(`0 0 ${F}px ${I}`)}x["text-shadow"]=Y.join(", ")}I="";switch(r.fontFamily){case 1:I='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:I='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:I='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:I='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:I='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';
break;case 7:I=g.i0()?'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:I='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}I&&(x["font-family"]=I);I=r.offset;I==null&&(I=t.Z.ZP.offset);switch(I){case 0:x["vertical-align"]="sub";break;case 2:x["vertical-align"]="super"}r.fontFamily===7&&(x["font-variant"]="small-caps");r.bold&&(x["font-weight"]="bold");r.italic&&(x["font-style"]="italic");r.underline&&
(x["text-decoration"]="underline");r.dZ&&(x.visibility="hidden");r.mB===1&&t.W&&(x["text-combine-upright"]="all",x["text-orientation"]="mixed",I=g.sz||g.RY,t.B.params.Li===3?x.transform=I?"rotate(90deg)":"rotate(180deg)":I&&(x.transform="rotate(-90deg)"));if(r.textEmphasis===1||r.textEmphasis===2||r.textEmphasis===3||r.textEmphasis===4||r.textEmphasis===5)if(g.sz)x["font-weight"]="bold";else switch(x["text-emphasis-style"]="filled circle",x["text-emphasis-color"]="currentcolor",x["webkit-text-emphasis"]=
"filled circle",r.textEmphasis){case 4:case 3:x["text-emphasis-position"]="under left";x["webkit-text-emphasis-position"]="under left";break;case 5:case 2:x["text-emphasis-position"]="over right",x["webkit-text-emphasis-position"]="over right"}return x},dU=function(t){t=t.split("px");
return t.length>0?(t=Number(t[0]))?t:0:0},TXf=function(t,r,x){t.RO=t.RO||!!x;
const Y={};Object.assign(Y,t.Z.ZP);Object.assign(Y,x||r.Z);Object.assign(Y,t.Eu.ZP);(x=!t.K)&&Him(t);let I=t.PN&&t.EC&&g.eX(Y,t.EC)?t.PN:SZm(t,Y);const m=typeof r.text==="string",F=m?r.text.split("\n"):[r.text];for(let h=0;h<F.length;h++){var A=h>0||!r.append;const E=F[h];A&&!x?(Him(t),I=SZm(t,Y)):A&&x&&(x=!1);E&&(I.appendChild(m?g.hF(E):E),m||E.tagName!=="RUBY"||E.childElementCount!==4||g.sz||!g.et(E.children[2],"text-emphasis")||(A=t.W?"padding-right":"padding-top",g.et(E.children[2],"text-emphasis-position")&&
(A=t.W?"padding-left":"padding-bottom"),g.xl?g.Va(I,A,"1em"):g.Va(I,A,"0.5em")))}t.EC=Y;t.PN=I;t.Y.push(r)},Him=function(t){t.K=g.AF("SPAN");
g.Va(t.K,{display:"block"});g.wn(t.K,"caption-visual-line");t.D.appendChild(t.K)},SZm=function(t,r){const x=g.AF("SPAN");
g.Va(x,{display:"inline-block","white-space":"pre-wrap"});g.Va(x,a9w(t,r));x.classList.add("ytp-caption-segment");t.K.appendChild(x);x.previousElementSibling&&(g.Va(x.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Va(x,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return x},GkN=function(t,r,x){if(t===255&&r===255||!t&&!r)return{Jg:t,
dY:r,result:0};t=l9N[t];r=l9N[r];if(t&128){var Y;if(Y=!(r&128))Y=r,Y=x.Xc()&&x.dY===Y;if(Y)return{Jg:t,dY:r,result:1}}else if(r&128&&1<=t&&t<=31)return{Jg:t,dY:r,result:2};return{Jg:t,dY:r,result:3}},tvs=function(t,r,x,Y){r===255&&x===255||!r&&!x?(++t.D===45&&t.reset(),t.W.B.clear(),t.J.B.clear()):(t.D=0,wdZ(t.W,r,x,Y))},rU8=function(t,r){t.Z.sort((x,Y)=>{const I=x.time-Y.time;
return I===0?x.order-Y.order:I});
for(const x of t.Z)t.time=x.time,x.type===0?tvs(t,x.A6,x.Pz,r):x.type===1&&t.B&496&&wdZ(t.J,x.A6,x.Pz,r);t.Z.length=0},FVX=function(t,r){switch(t){case 0:return xQm[(r&127)-32];
case 1:return Y_w[r&15];case 2:return IQZ[r&31];case 3:return mQe[r&31]}return 0},zX=function(t,r){if(t.style.type===3){var x=0,Y=0,I=t.J.time+0,m="",F="",A=I;
for(var h=1;h<=15;++h){var E=!1;for(var U=Y?Y:1;U<=32;++U){var n=t.D[h][U];if(n.Z!==0){x===0&&(x=h,Y=U);E=String.fromCharCode(n.Z);var L=n.timestamp;L<I&&(I=L);n.timestamp=A;F&&(m+=F,F="");m+=E;E=!0}if((n.Z===0||U===32)&&E){F="\n";break}else if(Y&&!E)break}if(x&&!E)break}m&&r.W(x,Y,I,A,m)}else for(Y=x=0,m=I=t.J.time+0,F=1;F<=15;++F)for(A="",h=1;h<=32;++h)if(U=t.D[F][h],n=U.Z,n!==0&&(x===0&&(x=F,Y=h),E=String.fromCharCode(n),L=U.timestamp,L<=I&&(I=L),A+=E,U.reset()),h===32||n===0)A&&r.W(x,Y,I,m,A),
I=m,A="",Y=x=0},cC=function(t){return t.D[t.row][t.B]},y$=function(t,r,x){r>=2&&t.B>1&&(--t.B,cC(t).Z=0);
const Y=cC(t);Y.timestamp=t.J.time+0;Y.Z=FVX(r,x);t.B<32&&t.B++},AUL=function(t,r,x,Y){for(let F=0;F<Y;F++)for(let A=0;A<=32;A++){var I=t.D[r+F][A],m=t.D[x+F][A];
I.Z=m.Z;I.timestamp=m.timestamp}},uy=function(t,r,x){for(let Y=0;Y<x;Y++)for(let I=0;I<=32;I++)t.D[r+Y][I].reset()},ZP=function(t){t.row=t.Z>0?t.Z:1;
t.B=1;uy(t,0,15)},hnX=function(t){t.style.set(1);
t.Z=t.W;t.Z.Z=0;t.Z.style=t.style;t.D.mode=1<<t.Z.W},J2=function(t,r,x){const Y=t.B;
let I=!1;switch(t.style.get()){case 4:case 1:case 2:t.style.get()===4&&Y.Z>0||(zX(Y,x),ZP(t.B),ZP(t.W),Y.row=15,Y.Z=r,I=!0)}t.style.set(3);t.Z=Y;t.Z.style=t.style;t.D.mode=1<<Y.W;I?Y.B=1:Y.Z!==r&&(Y.Z>r?(zX(Y,x),uy(Y,Y.row-Y.Z,r)):Y.row<r&&(r=Y.Z),Y.Z=r)},Em8=function(t){t.style.set(4);
t.Z=t.text;t.Z.style=t.style;t.D.mode=1<<t.Z.W},wdZ=function(t,r,x,Y){t.B.update();
r=GkN(r,x,t.B);switch(r.result){case 0:return;case 1:case 2:return}var I=r.Jg;r=r.dY;if(32<=I||!I)t.Z.mode&t.Z.B&&(x=I,x&128&&(x=127),r&128&&(r=127),t=t.W.Z,x&96&&y$(t,0,x),r&96&&y$(t,0,r),x!==0&&r!==0&&t.style.type===3&&zX(t,Y));else if(I&16)a:if(!t.B.matches(I,r)&&(x=t.B,x.Jg=I,x.dY=r,x.state=2,x=I&8?t.Y:t.D,t.W=x,t.Z.mode=1<<(t.J<<2)+(x.J<<1)+(x.style.type===4?1:0),(t.Z.mode|1<<(t.J<<2)+(x.J<<1)+(x.style.type!==4?1:0))&t.Z.B))if(r&64){Y=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(I&7)<<1|r>>5&1];
t=r&16?((r&14)>>1)*4:0;r=x.Z;switch(x.style.get()){case 4:Y=r.row;break;case 3:if(Y!==r.row){if(Y<r.Z&&(Y=r.Z,Y===r.row))break;var m=1+r.row-r.Z;const F=1+Y-r.Z;AUL(r,F,m,r.Z);x=m;I=r.Z;F<m?(m=F+I-m,m>0&&(x+=m,I-=m)):(m=m+I-F,m>0&&(I-=m));uy(r,x,I)}}r.row=Y;r.B=t+1}else switch(I&7){case 1:switch(r&112){case 32:y$(x.Z,0,32);break a;case 48:r===57?(Y=x.Z,cC(Y).Z=0,Y.B<32&&Y.B++):y$(x.Z,1,r&15)}break;case 2:r&32&&y$(x.Z,2,r&31);break;case 3:r&32&&y$(x.Z,3,r&31);break;case 4:case 5:if(32<=r&&r<=47)switch(r){case 32:hnX(x);
break;case 33:Y=x.Z;Y.B>1&&(--Y.B,cC(Y).Z=0);break;case 36:Y=x.Z;t=cC(Y);for(r=0;r<=15;r++)for(x=0;x<=32;x++)if(Y.D[r][x]===t){for(;x<=32;x++)Y.D[r][x].reset();break}break;case 37:J2(x,2,Y);break;case 38:J2(x,3,Y);break;case 39:J2(x,4,Y);break;case 40:y$(x.Z,0,32);break;case 41:Y=x;Y.style.set(2);Y.Z=Y.B;Y.Z.Z=0;Y.Z.style=Y.style;Y.D.mode=1<<Y.Z.W;break;case 42:Y=x;t=Y.text;t.Z=15;t.style.set(4);ZP(t);Em8(Y);break;case 43:Em8(x);break;case 44:t=x;r=t.B;switch(t.style.get()){case 1:case 2:case 3:zX(r,
Y)}uy(r,0,15);break;case 45:b:{r=x;t=r.Z;switch(r.style.get()){default:case 2:case 1:break b;case 4:if(t.row<15){++t.row;t.B=1;break b}break;case 3:}t.Z<2&&(t.Z=2,t.row<t.Z&&(t.row=t.Z));r=t.row-t.Z+1;zX(t,Y);AUL(t,r,r+1,t.Z-1);uy(t,t.row,1)}break;case 46:uy(x.W,0,15);break;case 47:t=x,zX(t.B,Y),t.W.updateTime(t.D.time+0),Y=t.W,t.W=t.B,t.B=Y,hnX(t)}break;case 7:switch(r){case 33:case 34:case 35:Y=x.Z,(Y.B+=r&3)>32&&(Y.B=32)}}},nm$=function(t,r,x,Y,I,m,F){var A=m[0];
let h=F[A.getAttribute("p")];if(h.iW===1){var E=m[1],U=m[2];m=m[3];A.getAttribute("t");E.getAttribute("t");U.getAttribute("t");m.getAttribute("t");A.getAttribute("p");E.getAttribute("p");m.getAttribute("p");F=F[U.getAttribute("p")];A=UQN(A.textContent,E.textContent,U.textContent,m.textContent,F);return new pE(t,r,I,x,A,Y,h)}switch(h.iW){case 9:case 10:h.textEmphasis=1;break;case 11:h.textEmphasis=2;break;case 12:h.textEmphasis=3;break;case 13:h.textEmphasis=4;break;case 14:h.textEmphasis=5}return new pE(t,
r,I,x,A.textContent||"",Y,h)},UQN=function(t,r,x,Y,I){var m=g.i0();
const F=m?g.AF("DIV"):g.AF("RUBY"),A=g.AF("SPAN");A.textContent=t;F.appendChild(A);t=m?g.AF("DIV"):g.AF("RP");t.textContent=r;F.appendChild(t);r=m?g.AF("DIV"):g.AF("RT");r.textContent=x;F.appendChild(r);x=I.iW;if(x===10||x===11||x===12||x===13||x===14)if(g.Va(r,"text-emphasis-style","filled circle"),g.Va(r,"text-emphasis-color","currentcolor"),g.Va(r,"webkit-text-emphasis","filled circle"),I.iW===11||I.iW===13)g.Va(r,"webkit-text-emphasis-position","under left"),g.Va(r,"text-emphasis-position","under left");
x=!0;if(I.iW===4||I.iW===7||I.iW===12||I.iW===14)g.Va(F,"ruby-position","over"),g.Va(F,"-webkit-ruby-position","before");else if(I.iW===5||I.iW===6||I.iW===11||I.iW===13)g.Va(F,"ruby-position","under"),g.Va(F,"-webkit-ruby-position","after"),x=!1;I=m?g.AF("DIV"):g.AF("RP");I.textContent=Y;F.appendChild(I);m&&(Y=x,g.Va(F,{display:"inline-block",position:"relative"}),m=F.firstElementChild.nextElementSibling,g.Va(m,"display","none"),m=m.nextElementSibling,g.Va(m,{"font-size":"0.5em","line-height":"1.2em",
"text-align":"center",position:"absolute",left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Va(F.lastElementChild,"display","none"),Y?(g.Va(F,"padding-top","0.6em"),g.Va(m,"top","0")):(g.Va(F,"padding-bottom","0.6em"),g.Va(m,"bottom","0")));return F},LV$=function(t){const r="_"+Q$++;
return new WC(0,0x8000000000000,0,r,t)},gU=function(t,r){t=t.getAttribute(r);
if(t!=null)return Number(t)},PC=function(t,r){t=t.getAttribute(r);
if(t!=null)return t==="1"},qo=function(t,r){t=gU(t,r);
return t!==void 0?t:null},DP=function(t,r){t=t.getAttribute(r);
if(t!=null)return sM.test(t),t},Mve=function(t,r){const x={},Y=r.getAttribute("ws");
Object.assign(x,Y?t.G[Y]:t.W);t=qo(r,"mh");t!=null&&(x.ra=t);t=qo(r,"ju");t!=null&&(x.textAlign=t);t=qo(r,"pd");t!=null&&(x.Li=t);t=qo(r,"sd");t!=null&&(x.KO=t);t=DP(r,"wfc");t!=null&&(x.windowColor=t);r=gU(r,"wfo");r!==void 0&&(x.windowOpacity=r/255);return x},Cq$=function(t,r){const x={},Y=r.getAttribute("wp");
Y&&Object.assign(x,t.L[Y]);t=qo(r,"ap");t!=null&&(x.Gw=t);t=gU(r,"cc");t!=null&&(x.gg=t);t=gU(r,"ah");t!=null&&(x.uD=t);t=gU(r,"rc");t!=null&&(x.sO=t);r=gU(r,"av");r!=null&&(x.Kc=r);return x},ize=function(t,r,x,Y){let I={};
Object.assign(I,Cq$(t,r));Object.assign(I,Mve(t,r));Y?g.eX(I,t.W)?(Y=t.J,I=t.W):Y="_"+Q$++:Y=r.getAttribute("id")||"_"+Q$++;t=gU(r,"t")+x;r=gU(r,"d")||0x8000000000000;if(I.Li===2||I.Li===3)x=I.sO,I.sO=I.gg,I.gg=x;return new WC(t,r,0,Y,I)},X1=function(t){t=g.Qv(Math.round(t),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-t.length)+t},jRD=function(t,r,x,Y,I){Y===0&&(Y=0x8000000000000);
const m={};r.wpWinPosId&&Object.assign(m,t.W.get(r.wpWinPosId));r.wsWinStyleId&&Object.assign(m,t.J.get(r.wsWinStyleId));t=r.rcRowCount;t!==void 0&&(m.sO=t);r=r.ccColCount;r!==void 0&&(m.gg=r);if(m.Li===2||m.Li===3)r=m.sO,m.sO=m.gg,m.gg=r;return new WC(x,Y,0,I,m)},fE=function(t){const r=t.byteOffset;
t.byteOffset+=1;return t.Z.getUint8(r)},kw=function(t){const r=t.byteOffset;
t.byteOffset+=4;return t.Z.getUint32(r)},cUt=function(t){if(typeof t==="string")return!1;
t=new dQD(t,0);return znt(t)},znt=function(t){if(!(t.byteOffset<t.Z.byteLength)||kw(t)!==1380139777)return!1;
t.version=fE(t);if(t.version>1)return!1;fE(t);fE(t);fE(t);return!0},yUt=function(t,r){if(!r)return"";
t.W&&t.B.params.KO!==1&&(r*=-1);return`translate${t.W?"X":"Y"}(${r}px)`},u4t=function(t){t.WN=Array.from(t.element.getElementsByClassName("caption-visual-line"));
for(var r=t.B.params.sO,x=0,Y=0,I=t.WN.length-1;x<r&&I>-1;){var m=t.WN[I];Y+=t.W?m.offsetWidth:m.offsetHeight;x++;I--}t.N=Y;r=Math;x=r.max;isNaN(t.sC)&&((Y=t.Z.gg)?(I=g.AF("SPAN"),g.CD(I,"\u2013".repeat(Y)),g.Va(I,a9w(t,t.Z.ZP)),t.D.appendChild(I),t.sC=I.offsetWidth,t.D.removeChild(I)):t.sC=0);Y=t.D;t.MS=x.call(r,t.sC,t.IK,(t.W?Y.offsetHeight:Y.offsetWidth)+1)},ZzN=function(t,r){u4t(t);
var x=t.WN.reduce((Y,I)=>(t.W?I.offsetWidth:I.offsetHeight)+Y,0);
x=t.N-x;if(x!==t.OC){const Y=x>0&&t.OC===0,I=x<t.OC;r||isNaN(x)||Y||!I||(g.wn(t.element,"ytp-rollup-mode"),t.S(t.element,"transitionend",t.oO));g.Va(t.D,"transform",yUt(t,x));t.OC=x}u4t(t)},pz$=function(t,r){t.Z=(x,Y)=>{if(x.info.D){var I=x;
if(t.Js.length>0){for(I=t.Js.shift();t.Js.length>0;)I=I.Y(t.Js.shift());I=I.Y(x)}if(I){x=I;try{var m=g.wp(x)*1E3}catch(M){m=x.info.startTime*1E3}try{var F=g.bri(x)*1E3}catch(M){F=x.info.duration*1E3}if(m<0||F<0)m<0&&(m=x.info.startTime*1E3),F<0&&(F=x.info.duration*1E3);x.info.startTime=m/1E3;x.info.W=m/1E3;x.info.duration=F/1E3;x.info.L=F/1E3;const {formatId:A,yL:h,startTimeMs:E,durationMs:U}=t.r4(I);m={formatId:A,startTimeMs:E,durationMs:U,FW:h,tI:h};F=JUf(t.KU,m.startTimeMs);const n=(x=F>=0?t.KU[F]:
null)?x.startTimeMs+x.durationMs:0,L=m.startTimeMs+m.durationMs;!x||m.startTimeMs-n>t.B?t.KU.splice(F+1,0,m):(x.durationMs=Math.max(n,L)-x.startTimeMs,x.tI=Math.max(x.tI,m.tI));Y(t.KU);m=g.Tf(I);Y=t.D;m=m.buffer.slice(m.byteOffset,m.byteLength+m.byteOffset);I=I.info.W;Y.iV?Y.L==null?g.Sl(Y.logger,350058965,"Null loaded track meta data at captions data received"):r.qF(m,Y.L,I*1E3):g.Sl(Y.logger,350058965,"Null Representation at captions data received")}else g.Sl(t.logger,350058965,"Empty slice")}else t.Js.push(x)};
t.U.addEventListener("sabrCaptionsDataLoaded",t.Z)},JUf=function(t,r){t=g.cD(t,{startTimeMs:r},(x,Y)=>x.startTimeMs-Y.startTimeMs);
return t>=0?t:-t-2},QRf=function(t,r){if(!g.FiH(t)||t.Z!=null&&g.vT(r,t.Z)&&t.Z.Z.rawcc!=null)return!1;
r=!!t.Z&&t.Z.isManifestless&&Object.values(t.Z.Z).some(x=>g.N7(x,"386"));
t=!!t.Z&&!t.Z.isManifestless&&g.dqn(t.Z);return r||t},WVw=function(t,r,x){const Y=[];
for(const I in t.B.Z){if(!t.B.Z.hasOwnProperty(I))continue;const m=t.B.Z[I];if(g.N7(m,x||null)){const F=m.info.captionTrack;F&&F.languageCode===r&&Y.push(m)}}return Y.length?Y[0]:null},gmL=function(t,r){const x=[];
for(const I in t.B.Z){if(!t.B.Z.hasOwnProperty(I))continue;var Y=t.B.Z[I];if(g.N7(Y,r||null)){let m=Y.info.id,F=m,A=`.${m}`,h="",E="";if(Y=Y.info.captionTrack)m=Y.languageCode,F=Y.displayName,A=Y.vssId,h=Y.kind,E=Y.id;x.push(new g.H5({id:I,languageCode:m,languageName:F,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:A,kind:h,captionId:E}))}}return x},q_L=function(t){const r=Pq$.length;
if(t.byteLength<r)return!1;t=new Uint8Array(t,0,r);for(let x=0;x<r;x++)if(Pq$[x]!==t[x])return!1;return!0},Ru=function(t){t=t.split(":");
let r=0;for(const x of t)r=r*60+Number(x);return r*1E3},sRX=function(t,r,x,Y){Y=Object.assign({ra:0},Y);
return new WC(t,r,x,"_"+Q$++,Y)},DQf=function(t,r,x,Y,I,m,F,A,h){switch(F.tagName){case "b":A.bold=!0;
break;case "i":A.italic=!0;break;case "u":A.underline=!0}for(let U=0;U<F.childNodes.length;U++){var E=F.childNodes[U];if(E.nodeType===3)E=new pE(r,x,Y,I.id,E.nodeValue,m||U>0,g.o1(A)?void 0:A),h.push(E),I.Z.push(E);else{const n={};Object.assign(n,A);DQf(t,r,x,Y,I,!0,E,n,h)}}},fQ$=function(t,r,x){if(typeof r==="string"||cUt(r))return[{trackData:r,
q2:x}];if(typeof r==="string"&&r.substring(0,6)==="WEBVTT"||typeof r!=="string"&&q_L(r))return[{trackData:r,q2:x}];const Y=new DataView(r);if(Y.byteLength<=8||Y.getUint32(4)!==1718909296)return[];var I=g.sXc(Y);if(t.HE&&I){var m=g.ufi(I),F=g.Z0c(I);I=I.segmentNumber;m&&I&&t.HE.XB(I,m,F)}t=g.wb(Y,1835295092);if(!t||!t.length||!t[0].size)return[];m=[];for(F=0;F<t.length;F++)I=t[F],I=new Uint8Array(r,I.dataOffset,I.size-(I.dataOffset-I.offset)),I=g.sg(I),m.push({trackData:I,q2:x+F*1E3});Xz$(Y,m,x);return m=
m.filter(A=>!!A.trackData)},Rns=function(t,r,x){t.Z||(t.Z=new kDN);
t=t.Z.D(r,x);Math.random()<.01&&g.u_(Error("Deprecated subtitles format in web player: WebVTT"));return t},Xz$=function(t,r,x){var Y=g.S$(t,0,1836476516);
let I=9E4;Y&&(I=g.TV(Y)||9E4);Y=0;const m=g.wb(t,1836019558);for(let A=0;A<m.length;A++){var F=m[A];A<r.length&&(F=g.S$(t,F.dataOffset,1953653094))&&(F=g.S$(t,F.dataOffset,1952867444))&&(F=g.GV(F)/I*1E3,A===0&&(Y=F),r[A].q2=F-Y+x||x*A*1E3)}},$Q8=function(t){const r={};
if(t=g.em(t))r.lang=t,g.B9T.test(t)&&(r.Li=1);return r},KVy=function(t){const r=!!t.U.Th()?.uV();
return t.D==="HLS"&&r?!0:t.rU&&r&&t.D!=="LIVE"&&t.D!=="SABR_LIVE"},KE=function(t,r,x=!1){const Y=$w.ZP;
t.J={};Object.assign(t.J,$w);t.J.ZP={};Object.assign(t.J.ZP,Y);t.Y={ZP:{}};var I=r.backgroundOverride?t.Y:t.J,m=r.background||Y.background;sM.test(m);I.ZP.background=m;I=r.colorOverride?t.Y:t.J;m=r.color||Y.color;sM.test(m);I.ZP.color=m;I=r.windowColorOverride?t.Y:t.J;m=r.windowColor||$w.windowColor;sM.test(m);I.windowColor=m;I=r.backgroundOpacityOverride?t.Y:t.J;m=r.backgroundOpacity;m==null&&(m=Y.backgroundOpacity);I.ZP.backgroundOpacity=m;I=r.fontSizeIncrementOverride?t.Y:t.J;m=r.fontSizeIncrement;
m==null&&(m=Y.fontSizeIncrement);I.ZP.fontSizeIncrement=m;m=r.fontStyleOverride?t.Y:t.J;I=r.fontStyle;I==null&&(I=Y.bold&&Y.italic?3:Y.bold?1:Y.italic?2:0);m=m.ZP;switch(I){case 1:m.bold=!0;delete m.italic;break;case 2:delete m.bold;m.italic=!0;break;case 3:m.bold=!0;m.italic=!0;break;default:delete m.bold,delete m.italic}I=r.textOpacityOverride?t.Y:t.J;m=r.textOpacity;m==null&&(m=Y.textOpacity);I.ZP.textOpacity=m;I=r.windowOpacityOverride?t.Y:t.J;m=r.windowOpacity;m==null&&(m=$w.windowOpacity);I.windowOpacity=
m;I=r.charEdgeStyleOverride?t.Y:t.J;m=r.charEdgeStyle;m==null&&(m=Y.charEdgeStyle);I.ZP.charEdgeStyle=m;I=r.fontFamilyOverride?t.Y:t.J;m=r.fontFamily;m==null&&(m=Y.fontFamily);I.ZP.fontFamily=m;t.loaded&&t.hH();x&&g.IY("yt-player-caption-display-settings",r,2592E3)},V$=function(t,r,x){r&&!t.iV?(r=LV$({Li:0,
lang:"en"}),t.iV=[r,new pE(r.start,r.end-r.start,0,r.id,x??"Captions look like this")],t.player.iZ(t.iV)):!r&&t.iV&&(Vvt(t,t.iV),t.iV=null)},omf=function(t){if(!t.U.isInline())return g.mq("yt-player-sticky-caption")},ou=function(t){let r=void 0;
const x=g.nY().cN(65);if(g.JW(t.e8)&&x!=null){if(omf(t)!=null)return!1;r=!x}return r},Ozs=function(t){if(t.e8.G8===1||t.videoData.e3===1||g.GM(t.videoData,"yt:cc")==="alwayson")return!0;
let r;t.videoData.captionTracks.length&&(r=t.getAudioTrack().B);if(t.e8.G8===2){if(g.JW(t.e8))var x=omf(t);else if(t.storage)try{x=t.storage.get("module-enabled")}catch(I){t.storage.remove("module-enabled")}else x=null;if(x!=null)return!!x}x=CE(t.player.getAudioTrack(),g.JW(t.e8));const Y=g.GM(t.videoData,"yt:cc");if(ou(t)===void 0){if(x==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return Y?Y==="on":!0;if(x==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return Y==="on"}else return Y==="on";return r==="ON"||
g.GM(t.videoData,"yt:cc")==="on"},OM=function(t,r=!1){if(t.Z&&!r||!t.videoData.captionTracks.length)return!1;
t=t.getAudioTrack();return!!t.Z||t.B==="FORCED_ON"},bzt=function(t,r){if(t.Z){var x=t.U.Th().WE().textTracks,Y=null;
t.D==="HLS"?Y=t.Z.getId():Y=t.Z.toString();for(let m=0;m<x.length;m++){var I=x[m];I.id===Y&&(r?I.mode!=="showing"&&(I.mode="showing",I=t.Z,t.BJ(I,!!I,by(t)?"g":t.K?"m":"s")):I.mode==="showing"&&(I.mode="disabled"))}}},by=function(t){const r=ej(t);
return!!r&&t.Z===r},ens=function(t,r){if(t.D==="HLS")return!1;
g.FA(t.videoData)&&(r=!0);r||(r=t.D==="TTS"?!1:t.D==="INNERTUBE"?!1:!0);return r||t.e8.C("web_deprecate_always_includes_asr_setting")&&g.JW(t.e8)?!0:!!g.nY().cN(66)},ej=function(t){return t.G&&t.G.Z},vC=function(t,r){if(!t.B)return null;
if(t.G&&t.G.W)return t.G.W;r=ens(t,r);r=g.ZX(t.B.Z,r);let x=null;if(qZt(t.e8)){var Y=t.U.isInline()?void 0:g.mq("yt-player-caption-sticky-language");var I=[Y,t.videoData.captionsLanguagePreference,t.e8.captionsLanguagePreference,g.GM(t.videoData,"yt:cc_default_lang")];let A=!1;for(let h=0;h<I.length;h++){const E=I[h];if(E){A=!0;for(var m=0;m<r.length;m++)if(g.em(r[m])===E)return r[m];for(m=0;m<r.length;m++)if(g.em(r[m]).split("-")[0]===E.split("-")[0])return r[m]}}if(A&&t.B&&(I=t.B.G,I.length))for(var F of I)if(F.languageCode===
Y){x=F;break}}else for(F=[t.videoData.captionsLanguagePreference,t.e8.captionsLanguagePreference,g.GM(t.videoData,"yt:cc_default_lang")],Y=0;Y<F.length;Y++)for(I=0;I<r.length;I++)if(g.em(r[I])===F[Y])return r[I];F=null;t.G&&t.G.D&&(F=t.G.D);F||(F=r.find(A=>A.isDefault)||null);
F||(F=r[0]||ej(t));F&&x&&g.em(F).split("-")[0]!==x.languageCode.split("-")[0]&&(F=sbw(F,x));return F},HC=function(t,r,x){t.loaded&&t.unload();
x!=null&&(t.K=x,t.K&&(g.JW(t.e8)?No(t,!!r):BC(t,!!r)));r!==null||OM(t,!0)||t.BJ(r,!!r,t.K?"m":"s");t.Z=r;OM(t)&&(t.Z=ej(t));au(t,t.Z??void 0);t.load()},No=function(t,r){t.U.isInline()||g.IY("yt-player-sticky-caption",r,2592E3)},BC=function(t,r){if(t.storage)try{t.storage.set("module-enabled",r)}catch(x){}},au=function(t,r){t.e8.C("html5_modify_caption_vss_logging")&&(t.videoData.BP=r)},NYL=function(t,r){var x=t.MS[r.id];
x&&x.B!==r&&(x.dispose(),delete t.MS[r.id],x=null);x||(x=vms(t,r))&&(t.MS[r.id]=x)},BYN=function(t,r){const x=r.windowId;
t.OC[x]||(t.OC[x]=[]);t.OC[x].push(r)},vms=function(t,r){const x=aQe(t);
if(!x)return null;var Y=t.Z?g.em(t.Z):null;Y&&g.B9T.test(Y)&&(r.params.Li=1);var I=t.tH.getPlayerSize();Y=I.height*t.N.height;I=I.width*t.N.width;t.e8.playerStyle!=="google-live"||t.J.isDefault||Object.assign(r.params,t.J);switch(r.params.ra!=null?r.params.ra:r.Z.length>1?1:0){case 1:return new Hzs(r,t.J,t.Y,x.width,x.height,I,Y,t.e8.experiments,t.zX.bind(t),t.U);case 2:return new S_D(r,t.J,t.Y,x.width,x.height,I,Y,t.e8.experiments,t.zX.bind(t),t.U);default:return new Sj(r,t.J,t.Y,x.width,x.height,
I,Y,t.e8.experiments,t.zX.bind(t),t.U)}},aQe=function(t){let r=t.tH.getVideoContentRect(!0).height,x=t.tH.getVideoContentRect(!0).width;
if(!r||!x)return null;r*=t.N.height;x*=t.N.width;return{width:x,height:r}},Vvt=function(t,r){t.player.z8(r);
for(const x of r)g.F$(t.sC,x);Mo(t.RO)},TYs=function(t,r){if(!t.B)return{};
if(r){g.o1(r)||t.Xy(r.vss_id,"m");if(t.W&&t.D!=="HLS"||!g.pn(r))return;if(g.o1(r)){HC(t,null,!0);return}let Y;var x=g.ZX(t.B.Z,!0);for(let I=0;I<x.length;I++){const m=x[I];m.languageCode!==r.languageCode||Y&&(m.languageName!==r.languageName||(m.captionId||"")!==(r.captionId||"")||g.Oz(m)!==r.displayName)||(Y=r.translationLanguage?sbw(m,r.translationLanguage):m)}t.y5(r.position);!Y||Y===t.Z&&t.loaded||(r=g.p5(),x=g.em(Y),r.length&&x===r[r.length-1]||(r.push(x),g.IY("yt-player-caption-language-preferences",
r)),qZt(t.e8)&&!t.U.isInline()&&g.IY("yt-player-caption-sticky-language",x,2592E3),HC(t,Y,!0))}else return t.loaded&&t.Z&&!by(t)?g.bP(t.Z):{};return""};
g.rh.prototype.XB=g.xh(65,function(t,r,x){this.B.set(t,{LS:r,YR:x})});
g.xS.prototype.XB=g.xh(64,function(t,r,x){this.iV.XB(t,r,x)});
g.bI.prototype.N=g.xh(63,function(){return!1});
g.bI.prototype.W=g.xh(62,function(){});
g.eE.prototype.W=g.xh(61,function(t,r,x){this.f8();r=this.Y(t,r);const Y=this.VL.X().C("html5_report_captions_ctmp_qoe"),I=(0,g.e)();this.D();PbX(this,r,{format:"RAW",onSuccess:m=>{this.B=null;if(Y){var F=(m.responseText.length/1024).toFixed();const A=(0,g.e)();this.videoData.ZE("capresp",{ms:A-I,kb:F})}F=m.getResponseHeader&&m.getResponseHeader("Content-Length")?Number(m.getResponseHeader("Content-Length")):0;x.qF(m.responseText,t,void 0,void 0,F)},
onError:Y?m=>{this.videoData.ZE("capfail",{status:m?.status??0})}:void 0,
withCredentials:!0})});
g.vG.prototype.W=g.xh(60,function(t,r,x){this.f8();r=this.Y(t,r);this.D();this.B=g.e_(r,{format:"RAW",onSuccess:Y=>{this.B=null;const I=Y.getResponseHeader&&Y.getResponseHeader("Content-Length")?Number(Y.getResponseHeader("Content-Length")):0;x.qF(Y.responseText,t,void 0,void 0,I)},
withCredentials:!0})});
g.t3.prototype.K=g.xh(59,function(){const t=g.SQ(document,"track",void 0,this.Z);for(let r=0;r<t.length;r++)g.LD(t[r])});
g.YY.prototype.K=g.xh(58,function(){this.mediaElement.K()});
g.t3.prototype.WN=g.xh(57,function(){return!(!this.Z.textTracks||!this.Z.textTracks.addEventListener)});
g.YY.prototype.WN=g.xh(56,function(){return this.mediaElement.WN()});
g.t3.prototype.uV=g.xh(55,function(){return!!this.Z.textTracks});
g.YY.prototype.uV=g.xh(54,function(){return this.mediaElement.uV()});
g.t3.prototype.iV=g.xh(53,function(t){for(let r=0;r<t.length;r++)this.Z.appendChild(t[r])});
g.YY.prototype.iV=g.xh(52,function(t){this.mediaElement.iV(t)});
g.jE.prototype.BX=g.xh(40,function(t){return this.app.E$({playerType:void 0}).BX(t)});
g.uX.prototype.BX=g.xh(39,function(t){return this.gU.Nc.BX(t)});
g.Xu.prototype.BX=g.xh(38,function(t){return this.Ac().some(r=>r.namespace===t)});
g.lI.prototype.BX=g.xh(37,function(){return!1});
g.jE.prototype.Xy=g.xh(35,function(t,r){this.app.aO().Xy(t,r)});
g.uX.prototype.Xy=g.xh(34,function(t,r){this.gU.Xy(t,r)});
g.PG.prototype.Xy=g.xh(33,function(t,r){t=[t,r];g.T8(this,g.wD(this.provider),"cfi",t)});
g.DC.prototype.Xy=g.xh(32,function(t,r){this.qoe&&this.qoe.Xy(t,r)});
g.Pj.prototype.Xy=g.xh(31,function(t,r){this.lF.Xy(t,r)});
g.lI.prototype.Xy=g.xh(30,function(){});
g.jE.prototype.BJ=g.xh(29,function(t,r,x){this.app.aO().BJ(t,r,x)});
g.uX.prototype.BJ=g.xh(28,function(t,r,x){this.gU.BJ(t,r,x)});
g.PG.prototype.BJ=g.xh(27,function(t,r,x){if(this.RO!==t||this.dU!==r)r=r==="rawcc"?"":r,x=[t,r,this.RO,x],g.T8(this,g.wD(this.provider),"cfs",x),this.RO=t,this.dU=r});
g.DC.prototype.BJ=g.xh(26,function(t,r,x){this.qoe&&this.qoe.BJ(t,r,x)});
g.Pj.prototype.BJ=g.xh(25,function(t,r,x){this.lF.BJ(t,r,x)});
g.lI.prototype.BJ=g.xh(24,function(){});
g.m$.prototype.RN=g.xh(3,function(t){return(t=this.D(t))?t.Z:0});
g.A0.prototype.RN=g.xh(2,function(){return 0});
var kkm=/#(.)(.)(.)/,f9s=/^#(?:[0-9a-f]{3}){1,2}$/i,biX={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Arab:"Kazakh (Arabic)",kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",ku_Latn:"Kurdish (Latin)",kum:"Kumyk",kut:"Kutenai",kv:"Komi",
kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",
maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",
mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",
nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pms:"Piedmontese",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",
pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",
sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",
sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelauan",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",
tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",
vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",
zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"},lQ$={en:"English"},GDt=class extends g.bI{constructor(t){super(t);this.B=new Set}J(t){var r=this.VL.Th();if(r&&r.WE()){r=r.WE().textTracks;for(const x of r)x.kind==="subtitles"&&!this.B.has(x.language)&&x.language&&(g.ed(this.Z,new g.H5({languageCode:x.language,languageName:x.language,kind:x.kind,id:x.id,displayName:lQ$[x.label]||x.label,vss_id:`.${x.language}`})),this.B.add(x.language))}g.ZX(this.Z).length>
0&&t.mZ()}},wzw=class{constructor(){this.segments=[]}contains(t){t=g.cD(this.segments,t);return t>=0||t<0&&(-t-1)%2===1}length(){return this.segments.length/2}},tr1=class extends g.G9{constructor(t,r,x,Y,I,m){super();this.policy=t;this.player=r;this.qS=x;this.L=Y;this.J=I;this.N=m;this.W=new wzw;this.Y=-1;this.B=this.D=this.Z=null;this.MS=0;this.K=new g.B7(this.iV,1E3,this);this.events=new g.pG(this);g.Q(this,this.K);g.Q(this,this.events);this.events.S(r,"SEEK_COMPLETE",this.G);this.G();this.iV()}DE(){super.DE();
this.B&&this.B.cancel()}G(){this.seekTo(this.player.getCurrentTime())}seekTo(t){t-=this.player.vE();const r=this.Z;this.Z=g.VH(this.qS.Y(t).Fb);r!==this.Z&&this.N&&this.N()}reset(){this.W=new wzw;this.Y=-1;this.B&&(this.B.cancel(),this.B=null)}iV(){this.f8();var t;if(t=this.Z!=null)t=this.Z,t=t.qS.W(t);if(t&&!this.B&&!(this.Z&&this.Z.startTime-this.player.getCurrentTime()>30)){t=this.Z;t=t.qS.RO(t);const I=t.Fb[0];if(this.player.getVideoData()?.enableServerStitchedDai){var r=this.player.bl();if(r){var x=
I.qS.info.id;const m=I.yL;var Y=t.Fb[0].W;if(this.policy.RO){if(r=g.pZc(r,Y,m,x,3))t.W=r}else if(x=r.eF(Y,m,x,3))if(Y=2,r.Ij.has(m)?Y=0:g.p8(r,m)&&(Y=1),r=Y,r===0)x&&(t.Z=new g.oA(x));else if(r===2){this.K.start();KR1(this)&&this.seekTo(this.player.getCurrentTime());return}}}I.qS.index.NV(I.yL)?(this.W.contains(t.Fb[0].yL)||VhX(this,t),this.Z=g.VH(t.Fb)):KR1(this)&&this.seekTo(this.player.getCurrentTime())}this.K.start()}},rTy=class extends g.bI{constructor(t,r){super(r);this.B=t;this.U=r;this.L=
null;this.iV=!1;this.logger=new g.H6("caps");this.MS=g.vT(this.U,this.B)}W(t,r,x){this.D();r=o2y(this,t.getId());r||(r=t.languageCode,r=this.B.isManifestless?Oi8(this,r,"386"):Oi8(this,r));if(r){var Y=(r.index.RN(r.index.b1())-r.index.getStartTime(r.index.b1()))*1E3,I=new g.MI6(this.U.X());this.L=new tr1(I,this.U,r,(m,F)=>{x.qF(m,t,F,Y)},this.MS||g.ak(r.info),()=>{this.L&&this.L.reset();
this.iV=!0})}}N(){const t=this.iV;
this.iV=!1;return t}J(t){var r=this.U.X().C("html5_fallback_if_rawcc_missing");const x=this.B.Z.rawcc!=null;if(!this.MS||!x&&r)r=this.B.isManifestless?eEN(this,"386"):eEN(this);else{if(!x){g.Sl(this.logger,386248249,"rawcc used but unavailable");return}r=[new g.H5({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.H5({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}for(const Y of r)g.ed(this.Z,
Y);t.mZ()}D(){this.L&&(this.L.dispose(),this.L=null)}Y(){return""}},sM=/^#(?:[0-9a-f]{3}){1,2}$/i;var xjy=["left","right","center","justify"];var Sj=class extends g.l{constructor(t,r,x,Y,I,m,F,A,h,E){const U=E.isInline()&&!0,n={};Object.assign(n,r);Object.assign(n,t.params);Object.assign(n,x);const L={};Object.assign(L,r.ZP);t.params.ZP&&Object.assign(L,t.params.ZP);Object.assign(L,x.ZP);U&&(n.windowOpacity=.6,L.backgroundOpacity=0);n.ZP=L;const M=n.Li===1,z=[{A:"span",O:"captions-text",V:{style:"word-wrap: normal; display: block;"}}],p=A.TX("caption_edit_on_hover")&&E.getVideoData().getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;
p&&z.unshift({A:"button",O:"caption-edit",V:{tabindex:"0","aria-label":REs()},j:[{A:"svg",V:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},j:[{A:"path",V:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});super({A:"div",O:"caption-window",V:{id:`${"caption-window"}-${t.id}`,dir:M?"rtl":"ltr",tabindex:"0",lang:n.lang},j:z});this.Y=
[];this.RO=!1;this.B=t;this.EC=this.PN=null;this.q0=m;this.dt=F;this.K=null;this.maxWidth=m*.96;this.maxHeight=F*.96;this.Z=n;this.Eu=x;this.uV=r;this.D=this.JH("captions-text");this.aK=this.D.style.getPropertyValue("box-decoration-break")!==""||this.D.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.zX=v21(Y,I,m,F);this.Az=h;p&&(this.J=this.JH("caption-edit"),this.S(this.J,"click",()=>{this.Az()}));
this.type=0;this.HN=this.zX*NX$(L);this.ZG=U;this.GX=A.TX("enable_centered_caption_for_tvfilm_video")&&E.getVideoData().isTvfilmVideo;this.G=E.X().BE().Z.cN(g.mJT);t=new g.p6(this.element,!0);g.Q(this,t);t.subscribe("dragstart",this.VR,this);t.subscribe("dragmove",this.XI,this);t.subscribe("dragend",this.yR,this);this.QL=this.tH=this.dU=this.hH=0;t="";this.Z.windowOpacity&&(t=iy(this.Z.windowColor),t="rgba("+t[0]+","+t[1]+","+t[2]+","+this.Z.windowOpacity+")");r={"background-color":t,display:this.Z.isVisible===
!1?"none":"","text-align":xjy[this.Z.textAlign]};this.aK&&(r["border-radius"]=t?`${this.HN/8}px`:"");(this.W=this.B.params.Li===2||this.B.params.Li===3)&&BXt(this,this.element);g.Va(this.element,r);U&&this.element.parentElement?.style.setProperty("--caption-window-color",t);switch(this.Z.Gw){case 0:case 1:case 2:g.wn(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.wn(this.element,"ytp-caption-window-bottom")}}VR(t,r){this.tH=t;this.QL=r;const x=g.wo(this.element,this.element.parentElement);
this.hH=t-x.x;this.dU=r-x.y}XI(t,r){if(t!==this.tH||r!==this.QL){g.Gg(this.element,"ytp-dragging")||g.wn(this.element,"ytp-dragging");var x=g.rX(this.element);t=t-this.hH-.02*this.q0;var Y=r-this.dU-.02*this.dt,I=(t+x.width/2)/this.maxWidth*3;I=Math.floor(g.Qv(I,0,2));var m=(Y+x.height/2)/this.maxHeight*3;m=Math.floor(g.Qv(m,0,2));r=I+m*3;t=(t+I/2*x.width)/this.maxWidth;t=g.Qv(t,0,1)*100;x=(Y+m/2*x.height)/this.maxHeight;x=g.Qv(x,0,1)*100;this.B.params.Gw=r;this.B.params.Kc=x;this.B.params.uD=t;this.B.params.isDefault=
!1;this.Z.Gw=r;this.Z.Kc=x;this.Z.uD=t;this.Z.isDefault=!1;this.uV.Gw=r;this.uV.Kc=x;this.uV.uD=t;this.uV.isDefault=!1;this.oK()}}yR(){g.rL(this.element,"ytp-dragging")}oK(){this.L(this.Y)}L(t){var r=this.ZG?0:Math.min(this.O$(),this.maxWidth),x=this.RK(),Y=this.ZG;if(Y){var I=getComputedStyle(this.D.parentNode);I=dU(I.borderLeftWidth)+dU(I.borderRightWidth)+dU(I.paddingLeft)+dU(I.paddingRight)}else I=0;const m=I;I="";this.B.params.Li===3&&(I="rotate(180deg)");var F=Y?`calc(${"96%"} - ${m}px)`:"96%";
g.Va(this.element,{top:0,left:0,right:"",bottom:"",width:r?`${r}px`:"",height:x?`${x}px`:"","max-width":F,"max-height":F,margin:"",transform:""});this.rU(t);I={transform:I,top:"",left:"",width:r?`${r}px`:"",height:x?`${x}px`:"","max-width":"","max-height":""};F=this.Z.Gw;var A=this.Z.uD;const h=this.Z.Kc;this.GX&&F!=null&&(A=50,F=Math.floor(F/3)*3+1);A=A*.96+2;switch(F){case 0:case 3:case 6:(Y=this.Z.ZP.fontSizeIncrement)&&Y>0&&this.Z.Li!==2&&this.Z.Li!==3&&(A=Math.max(A/(1+Y*2),2));I.left=`${A}%`;
break;case 1:case 4:case 7:I.left=`${A}%`;A=0;this.G||(A=this.D.offsetWidth);r||A?(r=r||A+1,I.width=`${r}px`,I["margin-left"]=Y?`${r/-2-m/2}px`:`${r/-2}px`):(this.G&&(I.width="max-content"),I.transform+=" translateX(-50%)");break;case 2:case 5:case 8:I.right=`${100-A}%`}Y=h*.96+2;switch(F){case 0:case 1:case 2:I.top=`${Y}%`;break;case 3:case 4:case 5:I.top=`${Y}%`;Y=0;this.G||(Y=this.element.clientHeight);(x=x||Y)?(I.height=`${x}px`,I["margin-top"]=`${x/-2}px`):I.transform+=" translateY(-50%)";break;
case 6:case 7:case 8:I.bottom=`${100-Y}%`}g.Va(this.element,I);if(this.J){if(this.G)x=this.HN;else{if(this.GX&&t.length===0)t=0;else{x=1;for(Y=0;Y<t.length;Y++)I=t[Y],typeof I.text==="string"&&(x+=I.text.split("\n").length-1,I.append||Y===0||x++);t=x}x=this.GX?t>0?this.D.offsetHeight/t:0:this.D.offsetHeight/t}this.J.style.height=`${x}px`;this.J.style.width=`${x}px`;this.element.style.paddingLeft=`${x+5}px`;this.element.style.paddingRight=`${x+5}px`;this.G||(t=Number(this.element.style.marginLeft.replace("px",
""))-x-5,x=Number(this.element.style.marginRight.replace("px",""))-x-5,this.element.style.marginLeft=`${t}px`,this.element.style.marginRight=`${x}px`)}}rU(t){let r;for(r=0;r<t.length&&t[r]===this.Y[r];r++);if(this.RO||this.Y.length>r)r=0,this.RO=!1,this.Y=[],this.K=this.EC=this.PN=null,g.UR(this.D);for(;r<t.length;r++)TXf(this,t[r])}O$(){return 0}RK(){return 0}toString(){return super.toString()}};var IdL=class{constructor(){this.D=this.time=this.mode=this.B=0;this.W=new Y9e(this);this.J=new Y9e(this);this.Z=[];this.clear()}clear(){this.D=this.time=this.mode=0;this.Z=[];this.reset()}reset(){this.mode=0;this.W.reset(0);this.J.reset(1)}},l9N=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,
74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,
215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255],mjt=class{constructor(){this.type=0}set(t){this.type=t}get(){return this.type}},Fgt=class{constructor(){this.state=this.dY=this.Jg=0}clear(){this.state=0}update(){this.state=this.state===2?1:0}Xc(){return this.state!==0}matches(t,r){return this.Xc()&&t===this.Jg&&r===this.dY}},ATD=class{constructor(){this.timestamp=this.Z=0}reset(){this.timestamp=
this.Z=0}},TX=class{constructor(t){this.J=t;this.D=[];this.Z=this.B=this.row=0;this.style=new mjt;this.W=0;for(t=0;t<=15;t++){this.D[t]=[];for(let r=0;r<=32;r++)this.D[t][r]=new ATD}}updateTime(t){for(let r=1;r<=15;++r)for(let x=1;x<=32;++x)this.D[r][x].timestamp=t}debugString(){let t="\n";for(let r=1;r<=15;++r){for(let x=1;x<=32;++x){const Y=this.D[r][x];t=Y.Z===0?t+"_":t+String.fromCharCode(Y.Z)}t+="\n"}return t}reset(t){for(let r=0;r<=15;r++)for(let x=0;x<=32;x++)this.D[r][x].reset();this.W=t;
this.Z=0;this.B=this.row=1}},xQm=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Y_w=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],IQZ=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,
194,199,200,202,203,235,206,207,239,212,217,249,219,171,187],mQe=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499],hNt=class{constructor(t){this.D=t;this.J=0;this.style=new mjt;this.Y=new TX(this.D);this.K=new TX(this.D);this.text=new TX(this.D);this.B=this.Y;this.W=this.K;this.Z=this.B}reset(t,r){this.J=r;this.style.set(2);this.B=this.Y;this.W=this.K;this.Z=this.B;const x=(t<<2)+(r<<1);this.Y.reset(x);this.K.reset(x);
this.text.reset((t<<2)+(r<<1)+1)}},Y9e=class{constructor(t){this.Z=t;this.J=0;this.D=new hNt(this.Z);this.Y=new hNt(this.Z);this.B=new Fgt;this.W=this.D}reset(t){this.J=t;this.B.clear();this.W=this.D;this.D.reset(t,0);this.Y.reset(t,1)}};var EoN=class{W(){}};var pE=class extends g.aK{constructor(t,r,x,Y,I,m=!1,F=null){super(t,t+r,{priority:x,namespace:"captions"});this.windowId=Y;this.text=I;this.append=m;this.Z=F}toString(){return super.toString()}};var ly=class extends g.G9{reset(){}};var WC=class extends g.aK{constructor(t,r,x,Y,I){super(t,t+r,{priority:x,namespace:"captions"});this.id=Y;this.params=I;this.Z=[]}toString(){return super.toString()}},Q$=0;var Ujm=class extends ly{constructor(t){super();this.W=t;this.pens={};this.L={};this.G={};this.J="_"+Q$++;this.K={};this.B=this.Z=null;this.Y=!0}reset(){this.K={};this.B=this.Z=null;this.Y=!0}D(t,r){t=t.firstChild;t.getAttribute("format");r=r||0;Number.isFinite(r);t=Array.from(t.childNodes);for(var x of t)if(x.nodeType===1)switch(x.tagName){case "head":var Y=x;break;case "body":var I=x}if(Y){Y=Array.from(Y.childNodes);for(var m of Y)if(m.nodeType===1)switch(m.tagName){case "pen":x=m.getAttribute("id");
Y=this.pens;t={};var F=m.getAttribute("p");F&&Object.assign(t,this.pens[F]);F=PC(m,"b");F!=null&&(t.bold=F);F=PC(m,"i");F!=null&&(t.italic=F);F=PC(m,"u");F!=null&&(t.underline=F);F=qo(m,"et");F!=null&&(t.charEdgeStyle=F);F=qo(m,"of");F!=null&&(t.offset=F);F=DP(m,"bc");F!=null&&(t.background=F);F=DP(m,"ec");F!=null&&(t.Dj=F);F=DP(m,"fc");F!=null&&(t.color=F);F=qo(m,"fs");F!=null&&F!==0&&(t.fontFamily=F);F=gU(m,"sz");F!==void 0&&(t.fontSizeIncrement=F/100-1);F=gU(m,"bo");F!==void 0&&(t.backgroundOpacity=
F/255);F=gU(m,"fo");F!==void 0&&(t.textOpacity=F/255);F=qo(m,"rb");F!=null&&F!==10&&F!==0&&(t.iW=F>10?F-1:F);F=qo(m,"hg");F!=null&&(t.mB=F);Y[x]=t;break;case "ws":Y=m.getAttribute("id");this.G[Y]=Mve(this,m);break;case "wp":Y=m.getAttribute("id"),this.L[Y]=Cq$(this,m)}}if(I){m=[];I=Array.from(I.childNodes);for(p of I)if(p.nodeType===1)switch(p.tagName){case "w":this.Z=ize(this,p,r,!1);(I=this.K[this.Z.id])&&I.end>this.Z.start&&(I.end=this.Z.start);this.K[this.Z.id]=this.Z;m.push(this.Z);break;case "p":var A=
p;t=r;I=[];Y=A.getAttribute("w")||this.J;x=!!PC(A,"a");t=(gU(A,"t")||0)+t;F=gU(A,"d")||5E3;x||(!this.Y&&this.B&&this.B.windowId===Y&&this.B.end>t&&(this.B.end=t),this.B&&this.B.text==="\n"&&(this.B.text=""));const q=x?6:5;var h=A.getAttribute("p");h=h?this.pens[h]:null;const f=Array.from(A.childNodes);f.length&&(this.Y=A.getAttribute("d")!=null);for(A=0;A<f.length;A++){var E=f[A],U=void 0;A>0&&(x=!0);let X;E.nodeType===1&&(X=E);if(X&&X.tagName==="s"){if((E=(E=X.getAttribute("p"))?this.pens[E]:null)&&
E.iW&&(E.iW===1?(E=f.slice(A,A+4),E.length===4&&(U=nm$(t,F,Y,x,q,E,this.pens),A+=3)):U=nm$(t,F,Y,x,q,[X],this.pens)),!U){var n=X;U=t;E=F;var L=Y,M=x;const R=n.textContent?n.textContent:"";var z=n.getAttribute("p");z=z?this.pens[z]:null;n=gU(n,"t")||0;U=new pE(U+n,E-n,q,L,R,M,z)}}else U=new pE(t,F,q,Y,E.textContent||"",x,h);I.push(U);this.B=U}if(I.length>0){I[0].windowId===this.J&&(this.Z=ize(this,p,r,!0),m.push(this.Z));for(const X of I)X.windowId=this.Z.id,this.Z.Z.push(X),m.push(X)}}var p=m}else p=
[];return p}};var now=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]),Lgm=class extends ly{constructor(t){super();this.Y=t;this.Z=new Map;this.W=new Map;this.J=new Map;this.B=new Map}reset(){this.B.clear()}D(t,r){t=JSON.parse(t);if(!t)return[];if(t.pens){var x=t.pens,Y=0;for(var I of x){x={};var m=I.pParentId;m&&Object.assign(x,this.Z.get(m));I.bAttr&&(x.bold=!0);I.iAttr&&(x.italic=!0);I.uAttr&&(x.underline=!0);m=I.ofOffset;m!=null&&(x.offset=m);I.szPenSize!==void 0&&(x.fontSizeIncrement=I.szPenSize/100-1);
m=I.etEdgeType;m!=null&&(x.charEdgeStyle=m);I.ecEdgeColor!==void 0&&(x.Dj=X1(I.ecEdgeColor));m=I.fsFontStyle;m!=null&&m!==0&&(x.fontFamily=m);I.fcForeColor!==void 0&&(x.color=X1(I.fcForeColor));I.foForeAlpha!==void 0&&(x.textOpacity=I.foForeAlpha/255);I.bcBackColor!==void 0&&(x.background=X1(I.bcBackColor));I.boBackAlpha!==void 0&&(x.backgroundOpacity=I.boBackAlpha/255);(m=I.rbRuby)&&m!==10&&(x.iW=m>10?m-1:m,x.textEmphasis=now.get(x.iW));I.hgHorizGroup&&(x.mB=I.hgHorizGroup);this.Z.set(Y++,x)}}if(t.wsWinStyles){Y=
t.wsWinStyles;I=0;for(var F of Y)Y={},(x=F.wsParentId)?Object.assign(Y,this.J.get(x)):Object.assign(Y,this.Y),F.mhModeHint!==void 0&&(Y.ra=F.mhModeHint),F.juJustifCode!==void 0&&(Y.textAlign=F.juJustifCode),F.pdPrintDir!==void 0&&(Y.Li=F.pdPrintDir),F.sdScrollDir!==void 0&&(Y.KO=F.sdScrollDir),F.wfcWinFillColor!==void 0&&(Y.windowColor=X1(F.wfcWinFillColor)),F.wfoWinFillAlpha!==void 0&&(Y.windowOpacity=F.wfoWinFillAlpha/255),this.J.set(I++,Y)}if(t.wpWinPositions){I=t.wpWinPositions;F=0;for(var A of I)I=
{},(Y=A.wpParentId)&&Object.assign(I,this.W.get(Y)),A.ahHorPos!==void 0&&(I.uD=A.ahHorPos),A.apPoint!==void 0&&(I.Gw=A.apPoint),A.avVerPos!==void 0&&(I.Kc=A.avVerPos),A.ccCols!==void 0&&(I.gg=A.ccCols),A.rcRows!==void 0&&(I.sO=A.rcRows),this.W.set(F++,I)}if(t.events){t=t.events;A=[];for(const O of t)if(F=(O.tStartMs||0)+r,I=O.dDurationMs||0,O.id)Y=String(O.id),t=jRD(this,O,F,I,Y),A.push(t),this.B.set(Y,t);else{O.wWinId?Y=O.wWinId.toString():(Y="_"+Q$++,t=jRD(this,O,F,I,Y),A.push(t),this.B.set(Y,t));
t=A;var h=O;I===0&&(I=5E3);x=this.B.get(Y);const mW=(m=!!h.aAppend)?6:5,F6=h.segs;let op=null;h.pPenId&&(op=this.Z.get(h.pPenId));for(h=0;h<F6.length;h++){var E=F6[h],U=E.utf8;if(U){var n=E.tOffsetMs||0;let JL=null;E.pPenId&&(JL=this.Z.get(E.pPenId));if((x.params.ra!=null?x.params.ra:x.Z.length>1?1:0)===2&&m&&U==="\n")continue;E=null;var L=[],M;if(M=JL&&JL.iW===1)a:{M=F6;var z=h;if(z+3>=M.length||!M[z+1].pPenId||!M[z+2].pPenId||!M[z+3].pPenId){M=!1;break a}var p=M[z+1].pPenId;(p=this.Z.get(p))&&p.iW&&
p.iW===2?(p=M[z+2].pPenId,p=this.Z.get(p),!p||!p.iW||p.iW<3?M=!1:(p=M[z+3].pPenId,M=(p=this.Z.get(p))&&p.iW&&p.iW===2?!0:!1)):M=!1}if(M)n=F6[h+1].utf8,E=F6[h+3].utf8,M=F6[h+2].utf8,z=this.Z.get(F6[h+2].pPenId),U=UQN(U,n,M,E,z),E=new pE(F,I,mW,Y,U,m,JL),h+=3;else{if(U.indexOf("<")>-1){L=JL;M=op;z=F;p=I;var q=n,f=mW,X=m;const Oc=[];var R=g.JK(`<html>${U}</html>`);if(!R.getElementsByTagName("parsererror").length&&R.firstChild?.childNodes.length)for(const BB of R.firstChild.childNodes){R=BB.textContent?.replace(/\n/g,
"")??"";if(BB.nodeType===3&&(!R||R.match(/^ *$/)!=null))continue;const qZ={};Object.assign(qZ,L||M);switch(BB?.tagName){case "b":qZ.bold=!0;break;case "i":qZ.italic=!0;break;case "u":qZ.underline=!0}Oc.push(new pE(z+q,p-q,f,x.id,R,X,qZ))}L=Oc}L.length||(L=[new pE(F+n,I-n,mW,x.id,U,m,JL||op)])}if(L.length)for(const Oc of L)t.push(Oc),x.Z.push(Oc);else E&&(t.push(E),x.Z.push(E))}m=!0}}r=A}else r=[];return r}};var MrN=class extends g.bI{constructor(t,r,x){super(t);this.videoData=r;this.audioTrack=x;this.G=r.JC}W(t,r,x){XdL(this.videoData.videoId,t.vssId,x.qF)}J(t){if(this.audioTrack)for(const r of this.audioTrack.captionTracks)g.ed(this.Z,r);t.mZ()}};var Hzs=class extends Sj{constructor(t,r,x,Y,I,m,F,A,h,E){super(t,r,x,Y,I,m,F,A,h,E);this.type=1}rU(t){const r=this.B.Z;super.rU(t);let x,Y;for(t=t.length;t<r.length;t++){const I=r[t];let m;Y&&I.Z===x?m=Y:(m={},Object.assign(m,I.Z),Object.assign(m,Cv8),x=I.Z,Y=m);TXf(this,I,m)}}},Cv8={dZ:!0};var dQD=class extends EoN{constructor(t,r){super();this.trackData=t;this.Y=r;this.version=this.J=this.D=this.byteOffset=0;this.B=[];this.Z=new DataView(this.trackData)}W(t,r,x,Y,I){if(x<Y){const m="_"+Q$++;x=x/1E3-this.Y;Y=Y/1E3-this.Y;t=new WC(x,Y-x,5,m,{textAlign:0,Gw:0,uD:r*2.5,Kc:t*5.33});I=new pE(x,Y-x,5,m,I);this.B.push(t);this.B.push(I)}}},iof=class extends ly{constructor(t,r){super();this.B=t;this.W=r;this.track=this.W.languageName==="CC3"?4:0;this.Z=new IdL;this.Z.B=1<<this.track}D(t){t=
new dQD(t,this.B);if(znt(t)){for(;t.byteOffset<t.Z.byteLength;)for(t.version===0?t.D=kw(t)*(1E3/45):t.version===1&&(t.D=kw(t)*4294967296+kw(t)),t.J=fE(t);t.J>0;t.J--){var r=fE(t);const x=fE(t),Y=fE(t);r&4&&(r&3)===this.track&&(this.track===0||this.track===1)&&(r=this.Z,r.Z.push({time:t.D,type:this.track,A6:x,Pz:Y,order:r.Z.length}))}rU8(this.Z,t);return t.B}return[]}reset(){this.Z.clear()}};var S_D=class extends Sj{constructor(t,r,x,Y,I,m,F,A,h,E){super(t,r,x,Y,I,m,F,A,h,E);this.type=2;this.WN=[];this.MS=this.N=this.OC=0;this.sC=NaN;this.IK=0;this.gt=null;this.j0=new g.B7(this.oO,433,this);this.J&&(E.createClientVe(this.J,this,167342),this.S(this.J,"click",()=>{E.logClick(this.J)}),t=new g.p6(this.element,!0),g.Q(this,t),t.subscribe("hoverstart",()=>{E.logVisibility(this.J,!0)},this));
g.wn(this.element,"ytp-caption-window-rollup");g.Q(this,this.j0);g.Va(this.element,"overflow","hidden")}oK(){g.a3(this.j0)}oO(){this.element.removeEventListener("transitionend",this.oO,!1);g.rL(this.element,"ytp-rollup-mode");this.L(this.gt,!0)}RK(){return this.W?this.MS:this.N}O$(){return this.W?this.N:this.MS}L(t,r){this.gt=t;if(this.B.params.sO){var x=0;for(let Y=0;Y<this.Y.length&&x<t.length;Y++)this.Y[Y]===t[x]&&x++;x>0&&x<t.length&&(t=this.Y.concat(t.slice(x)));this.IK=this.MS;this.N=this.MS=
0;super.L(t);ZzN(this,r)}super.L(t)}};var j8L=class{constructor(t,r,x,Y){this.U=t;this.D=r;this.logger=x;this.Ce=Y;this.KU=[];this.Js=[];this.Z=null;this.Tf={fPA:()=>this.Z,
c_:()=>this.KU};
t=g.M2(this.U.X().experiments,"html5_override_micro_discontinuities_threshold_ms");this.B=t>0?t:10}unload(){this.Z!=null&&(this.U.removeEventListener("sabrCaptionsDataLoaded",this.Z),this.Z=null);this.KU=[];this.U.publish("sabrCaptionsBufferedRangesUpdated",this.KU)}r4(t){return{formatId:g.SD(t.info.qS.info,this.Ce),yL:t.info.yL+(this.Ce?0:1),startTimeMs:t.info.W*1E3,durationMs:t.info.L*1E3}}};var djw=class extends g.bI{constructor(t,r){super(r);this.B=t;this.U=r;this.logger=new g.H6("caps");this.L=this.iV=null;this.MS=new j8L(this.U,this,this.logger,this.B.Ce)}W(t,r,x){this.D();r=t.getId();r=r!=null&&r in this.B.Z?this.B.Z[r]:null;r||(r=t.languageCode,r=this.B.isManifestless?WVw(this,r,"386"):WVw(this,r));r&&(this.L=t,this.iV=r,pz$(this.MS,x),this.U.publish("sabrCaptionsTrackChanged",g.SD(r.info,this.B.Ce)))}J(t){var r=this.B.isManifestless?gmL(this,"386"):gmL(this);for(const x of r)g.ed(this.Z,
x);t.mZ()}D(){this.L&&(this.L=this.iV=null,this.MS.unload(),this.U.publish("sabrCaptionsTrackChanged",null))}Y(){return""}};var Pq$="WEBVTT".split("").map(t=>t.charCodeAt(0)),kDN=class extends ly{constructor(){super()}D(t,r){t instanceof ArrayBuffer&&(t=g.sg(new Uint8Array(t)));
const x=[];t=t.split(zNt);for(let z=1;z<t.length;z++){var Y=t[z],I=r;if(Y!==""&&!cTL.test(Y)){var m=GX.exec(Y);if(m&&m.length>=4){var F=Ru(m[1]),A=Ru(m[2])-F;F+=I;var h=(m=m[3])?m.split(" "):[];m={};var E=null;var U="";var n=null,L="";for(const p of h){h=p.split(":");if(h.length!==2)continue;var M=h[1];switch(h[0]){case "line":h=M.split(",");h[0].endsWith("%")&&(E=h[0],m.Kc=Number.parseInt(E,10),h.length===2&&(U=h[1].trim()));break;case "position":h=M.split(",");n=h[0];m.uD=Number.parseInt(n,10);
h.length===2&&(L=h[1].trim());break;case "align":switch(M){case "start":m.textAlign=0;break;case "middle":m.textAlign=2;break;case "end":m.textAlign=1}}}E||U||(U="end");if(!n)switch(m.textAlign){case 0:m.uD=0;break;case 1:m.uD=100;break;case 2:m.uD=50}if(m.textAlign!=null){E=0;switch(U){case "center":E+=3;break;case "end":E+=6;break;default:E+=0}switch(L){case "line-left":E+=0;break;case "center":E+=1;break;case "line-right":E+=2;break;default:switch(m.textAlign){case 0:E+=0;break;case 2:E+=1;break;
case 1:E+=2}}U=E<0||E>8?7:E;m.Gw=U}Y=Y.substring(GX.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");L=m;m=Y;Y={};if(m.indexOf("<")<0&&m.indexOf("&")<0)I=sRX(F,A,5,L),A=new pE(F,A,5,I.id,m,!1,g.o1(Y)?void 0:Y),x.push(I),x.push(A),I.Z.push(A);else for(U=m.split(yTL),U.length===1?(m=5,L=sRX(F,A,m,L)):(E=m=6,L=Object.assign({gg:32},L),L=new WC(F,A,E,"_"+Q$++,L)),x.push(L),E=F,n=0;n<U.length;n++)if(h=U[n],n%2===0){M=g.JK(`<html>${h}</html>`);let p;M.getElementsByTagName("parsererror").length?(p=M.createElement("span"),
p.appendChild(M.createTextNode(h))):p=M.firstChild;DQf(this,E,A-(E-F),m,L,n>0,p,Y,x)}else E=Ru(h)+I}GX.lastIndex=0}}return x}},cTL=/^NOTE/,zNt=/(?:\r\n|\r|\n){2,}/,GX=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),yTL=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");var uEm=class extends g.G9{constructor(t,r){super();this.U=t;this.e8=r;this.Z=null;this.HE=this.U.bl();this.logger=new g.H6("caps")}clear(){this.Z&&this.Z.dispose();this.Z=null}reset(){this.Z&&this.Z.reset()}DE(){super.DE();this.clear()}};var $w={windowColor:"#080808",windowOpacity:0,textAlign:2,Gw:7,uD:50,Kc:100,isDefault:!0,ZP:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.bd("captions",class extends g.OS{constructor(t){super(t);this.U=t;this.sC=[];this.MS={};this.OC={};this.K=!1;this.D="NONE";this.B=this.G=this.iV=this.EC=this.GX=null;this.QL={mZ:()=>{this.mZ()},
qF:(Y,I,m,F,A=0)=>{const h=Number(this.videoData.X().BE().Z.cN(g.CIB)??0);A>0&&h>0&&this.videoData.lengthSeconds>0&&A/this.videoData.lengthSeconds>h?this.U.ZE("tts",{dropcap:A}):this.qF(Y,I,m,F)}};
this.Z=null;this.e8=this.U.X();this.videoData=this.U.getVideoData();this.tH=this.U.mf();this.J={ZP:{}};this.Y={ZP:{}};this.videoData.O$()?this.D="OFFLINE":g.gtH(this.videoData,this.U)?this.D="HLS":QRf(this.videoData,this.U)?this.D="SABR_LIVE":g.PxW(this.videoData,this.U)?this.D="LIVE":this.videoData.captionTracks.length?this.D="INNERTUBE":this.videoData.RK&&(this.D="TTS");this.rU=this.e8.controlsType==="3";this.HN=new uEm(this.U,this.e8);this.uV=new g.pG(this);this.L=new g.l({A:"div",O:"ytp-caption-window-container",
V:{id:"ytp-caption-window-container"}});this.N={top:0,right:0,bottom:0,left:0,width:1,height:1};let r=null;const x=g.Ob("yt-html5-player-modules::subtitlesModuleData");x&&(r=new g.WW(x));this.storage=r;this.oO=!!t.Th()?.WN();this.W=KVy(this);this.WN=!this.W&&this.rU&&this.oO&&(this.D==="LIVE"||this.D==="SABR_LIVE");g.Q(this,this.HN);this.W?this.PN=this.RO=null:(this.RO=new g.eL(this.ZG,void 0,this),g.Q(this,this.RO),this.PN=new g.B7(this.oK,2E3,this),g.Q(this,this.PN));g.Q(this,this.uV);g.$I(this.player,
this.L.element,4);g.Q(this,this.L);this.W||this.uV.S(t,"resize",this.hH);(this.dU=g.Ls(this.e8)&&!g.Bp()&&!this.U.isFullscreen()&&!this.W&&!this.WN)&&this.uV.S(t,"resize",this.RK);this.uV.S(t,"onPlaybackAudioChange",this.zf);this.uV.S(t,g.DK("captions"),Y=>{this.onCueRangeEnter(Y)});
this.uV.S(t,g.Xs("captions"),Y=>{this.onCueRangeExit(Y)});
KE(this,jj()||{});g.ca(this.player,"onCaptionsModuleAvailable");this.D==="HLS"&&this.W&&(t=this.U.Th().WE(),this.oO&&this.uV.S(t.textTracks,"addtrack",this.O$))}DE(){if(this.W||this.WN){const t=this.U.Th();t&&!t.f8()&&t.K()}else V$(this,!1);super.DE()}e7(){return this.e8.C("html5_honor_caption_availabilities_in_audio_track")&&this.D!=="LIVE"&&this.D!=="SABR_LIVE"}Eq(){if(this.rU)return this.W||this.WN;if(this.D==="HLS")return this.W;var t=this.getAudioTrack();if(this.e7()){if(!t.captionTracks.length)return!1;
if(!this.B)return!0}t=CE(t,g.JW(this.e8));return t==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:t==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?OM(this):ou(this)||OM(this)?!0:Ozs(this)}load(){super.load();this.G=this.getAudioTrack();if(this.B)this.Z&&(this.HN.clear(),this.W?bzt(this,!0):this.player.getPresentingPlayerType()!==3&&this.B.W(this.Z,"json3",this.QL),this.D!=="HLS"&&this.W||this.WN||by(this)||g.ca(this.player,"captionschanged",g.bP(this.Z)));else{let t;this.D==="OFFLINE"?t=new MrN(this.player,this.videoData,
this.getAudioTrack()):this.D==="SABR_LIVE"?t=new djw(this.videoData.Z,this.player):this.D==="HLS"?t=new GDt(this.player):this.D==="LIVE"?t=new rTy(this.videoData.Z,this.player):this.D==="INNERTUBE"?t=new g.eE(this.player,this.videoData,this.getAudioTrack()):t=new g.vG(this.player,this.videoData.RK,this.videoData.videoId,g.E3n(this.videoData),this.videoData.Aw,this.videoData.eventId);this.B=t;g.Q(this,this.B);this.B.J(this.QL)}}unload(){this.W&&this.Z?bzt(this,!1):(this.PN&&this.PN.ww(),this.player.Oh("captions"),
this.sC=[],this.B&&this.B.D(),this.HN.clear(),this.iV&&this.player.iZ(this.iV),this.hH());super.unload();this.player.V3();g.ca(this.player,"captionschanged",{})}create(){this.Eq()&&this.load();var t;a:{if(this.e8.C("web_player_nitrate_promo_tooltip")&&this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.enableTouchCaptionsNitrate&&(t=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks))for(const r of t)if(r.kind==="asr"&&r.languageCode===
"en"){t=!0;break a}t=!1}t&&this.U.publish("showpromotooltip",this.L.element)}mZ(){var t=CE(this.player.getAudioTrack(),g.JW(this.e8));var r=t==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?vC(this,this.K):t==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&OM(this)?ej(this):ou(this)||this.K||Ozs(this)?vC(this,this.K):OM(this)?ej(this):null;if(this.D!=="HLS"&&this.W||this.WN){const x=g.ZX(this.B.Z,!0);t=[];for(let Y=0;Y<x.length;Y++){const I=x[Y],m=g.AF("TRACK");m.setAttribute("kind","subtitles");m.setAttribute("label",
g.Oz(I));m.setAttribute("srclang",g.em(I));m.setAttribute("id",I.toString());this.WN||m.setAttribute("src",this.B.Y(I,"vtt"));I===r&&m.setAttribute("default","1");t.push(m)}r=this.U.Th();r.iV(t);t=r.WE();this.oO&&this.uV.S(t.textTracks,"change",this.IK)}else!this.Z&&r&&HC(this,r),g.ca(this.player,"onCaptionsTrackListChanged"),g.y7(this.player,"onApiChange")}getTrackById(t){const r=g.ZX(this.B.Z,!0);for(let x=0;x<r.length;x++)if(r[x].toString()===t)return r[x];return null}IK(){const t=this.U.Th().WE().textTracks;
let r=null;for(let x=0;x<t.length;x++)t[x].mode==="showing"&&(r=this.getTrackById(t[x].id));(this.loaded?this.Z:null)!==r&&HC(this,r,!0)}O$(){this.B?.J(this.QL)}tB(){!this.Z&&this.W||this.unload()}qF(t,r,x,Y){if(t){au(this,this.Z??void 0);this.B.N()&&(this.sC=[],this.U.Oh("captions"),Mo(this.RO),this.HN.reset());a:{var I=this.HN;Y=Y||0;x=fQ$(I,t,x||0);t=[];try{for(const f of x){const X=f.trackData,R=f.q2,O=I.e8.C("safari_live_drm_captions_fix");if(typeof X!=="string"){x=t;var m=x.concat;if(O&&q_L(X))var F=
Rns(I,X,R);else{var A=I,h=r,E=X,U=R,n=Y;if(!cUt(E))throw Error("Invalid binary caption track data");A.Z||(A.Z=new iof(n,h));F=A.Z.D(E,U)}var L=m.call(x,F)}else{if(X.substring(0,6)==="WEBVTT")var M=t.concat(Rns(I,X,R));else{x=t;var z=x.concat;b:{h=I;A=r;if(X[0]==="{")try{h.Z||(h.Z=new Lgm($Q8(A)));var p=h.Z.D(X,R);break b}catch(op){g.N(op);p=[];break b}const mW=g.JK(X);if(!mW||!mW.firstChild){const op=Error("Invalid caption track data");op.params=X;throw op;}if(mW.firstChild.tagName==="timedtext"){if(Number(mW.firstChild.getAttribute("format"))===
3){E=mW;h.Z||(h.Z=new Ujm($Q8(A)));p=h.Z.D(E,R);break b}const op=Error("Unsupported subtitles format in web player (Format2)");op.params=X;throw op;}if(mW.firstChild.tagName==="transcript"){const op=Error("Unsupported subtitles format in web player (Format1)");op.params=X;throw op;}const F6=Error("Invalid caption track data");F6.params=X;throw F6;}M=z.call(x,p)}L=M}t=L}var q=t;break a}catch(f){g.Sl(I.logger,187101178,`Captions parsing failed: ${f.message}. `);I.clear();q=[];break a}q=void 0}r=q;r.length>
0&&(q=this.Z,this.BJ(q,!!q,by(this)?"g":this.K?"m":"s"));this.player.iZ(r,void 0,this.D==="LIVE"||this.D==="SABR_LIVE");!this.K||this.WN||by(this)||g.zr(this.e8)||g.ns(this.e8)||g.Si(this.e8)||this.e8.MS==="shortspage"||this.player.isInline()||(this.PN.ww(),r=LV$({Gw:0,uD:5,Kc:5,sO:2,textAlign:0,Li:0,lang:"en"}),this.EC=[r],q=["Click "," for settings"],this.GX||(I=new g.b1(g.gi()),g.Q(this,I),this.GX=I.element),I=r.end-r.start,(L=g.Oz(this.Z))&&this.EC.push(new pE(r.start,I,0,r.id,L)),this.EC.push(new pE(r.start,
I,0,r.id,q[0]),new pE(r.start,I,0,r.id,this.GX,!0),new pE(r.start,I,0,r.id,q[1],!0)),this.player.iZ(this.EC),this.PN.bf());!this.K||this.WN||by(this)||(g.JW(this.e8)?No(this,!0):BC(this,!0),this.G&&(this.G.W=this.Z),this.player.V3());this.K=!1}}onCueRangeEnter(t){this.sC.push(t);Mo(this.RO)}onCueRangeExit(t){g.F$(this.sC,t);this.B instanceof rTy&&this.B.MS&&this.player.z8([t]);Mo(this.RO)}getCaptionWindowContainerId(){return this.L.element.id}oK(){Vvt(this,this.EC);this.EC=null}ZG(){if(!this.dU||
!this.W){this.RO.stop();g.Om(this.OC);this.sC.sort(g.sG);var t=this.sC;if(this.iV){const r=g.vB(t,function(x){return this.iV.indexOf(x)===-1},this);
r.length&&(t=r)}for(const r of t)r instanceof WC?NYL(this,r):BYN(this,r);for(const [r,x]of Object.entries(this.MS)){const Y=r,I=x;this.OC[Y]?(I.element.parentNode||(I instanceof S_D||I instanceof Hzs||g.PD(this.MS,(m,F)=>{F!==Y&&m.B.params.Gw===I.B.params.Gw&&m.B.params.uD===I.B.params.uD&&m.B.params.Kc===I.B.params.Kc&&(m.dispose(),delete this.MS[F]);return F===Y},this),this.L.element.appendChild(I.element)),I.L(this.OC[Y])):(I.dispose(),delete this.MS[Y])}}}wh(){KE(this,{},!0);
g.ca(this.player,"captionssettingschanged")}zq(){var t=$w.ZP;t={background:t.background,backgroundOpacity:t.backgroundOpacity,charEdgeStyle:t.charEdgeStyle,color:t.color,fontFamily:t.fontFamily,fontSizeIncrement:t.fontSizeIncrement,fontStyle:t.bold&&t.italic?3:t.bold?1:t.italic?2:0,textOpacity:t.textOpacity,windowColor:$w.windowColor,windowOpacity:$w.windowOpacity};const r=jj()||{};r.background!=null&&(t.background=r.background);r.backgroundOverride!=null&&(t.backgroundOverride=r.backgroundOverride);
r.backgroundOpacity!=null&&(t.backgroundOpacity=r.backgroundOpacity);r.backgroundOpacityOverride!=null&&(t.backgroundOpacityOverride=r.backgroundOpacityOverride);r.charEdgeStyle!=null&&(t.charEdgeStyle=r.charEdgeStyle);r.charEdgeStyleOverride!=null&&(t.charEdgeStyleOverride=r.charEdgeStyleOverride);r.color!=null&&(t.color=r.color);r.colorOverride!=null&&(t.colorOverride=r.colorOverride);r.fontFamily!=null&&(t.fontFamily=r.fontFamily);r.fontFamilyOverride!=null&&(t.fontFamilyOverride=r.fontFamilyOverride);
r.fontSizeIncrement!=null&&(t.fontSizeIncrement=r.fontSizeIncrement);r.fontSizeIncrementOverride!=null&&(t.fontSizeIncrementOverride=r.fontSizeIncrementOverride);r.fontStyle!=null&&(t.fontStyle=r.fontStyle);r.fontStyleOverride!=null&&(t.fontStyleOverride=r.fontStyleOverride);r.textOpacity!=null&&(t.textOpacity=r.textOpacity);r.textOpacityOverride!=null&&(t.textOpacityOverride=r.textOpacityOverride);r.windowColor!=null&&(t.windowColor=r.windowColor);r.windowColorOverride!=null&&(t.windowColorOverride=
r.windowColorOverride);r.windowOpacity!=null&&(t.windowOpacity=r.windowOpacity);r.windowOpacityOverride!=null&&(t.windowOpacityOverride=r.windowOpacityOverride);return t}oa(t,r){const x={};Object.assign(x,jj());Object.assign(x,t);KE(this,x,r);g.ca(this.player,"captionssettingschanged")}hH(){!this.W&&this.loaded&&(g.Qy(this.MS,function(t,r){t.dispose();delete this.MS[r]},this),this.ZG())}xN(t,r){switch(t){case "fontSize":if(isNaN(r))break;
t=g.Qv(r,-2,4);this.oa({fontSizeIncrement:t});return t;case "reload":r&&!this.W&&HC(this,this.Z,!0);break;case "stickyLoading":r!==void 0&&this.e8.L&&(g.JW(this.e8)?No(this,!!r):BC(this,!!r));break;case "track":return TYs(this,r);case "tracklist":return this.B?g.N4(g.ZX(this.B.Z,!(!r||!r.includeAsr)),x=>g.bP(x)):[];
case "translationLanguages":return this.B?this.B.G.map(x=>Object.assign({},x)):[];
case "sampleSubtitles":this.W||r===void 0||V$(this,!!r);break;case "sampleSubtitlesCustomized":this.W||V$(this,!!r,r);break;case "recommendedTranslationLanguages":return g.p5();case "defaultTranslationSourceTrackIndices":return this.B?this.B.uV:[]}}getOptions(){const t="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.e8.L&&t.push("stickyLoading");return t}L$(){let t=this.Z;if(this.U.BX("captions")){if(this.e8.C("html5_modify_caption_vss_logging"))return(t=this.videoData.BP??
null)?{cc:g.wtT(t)}:{};if(t){let r=t.vssId;t.translationLanguage&&r&&(r=`t${r}.${g.em(t)}`);return{cc:r}}}return{}}z$(){this.isSubtitlesOn()?(g.JW(this.e8)?No(this,!1):BC(this,!1),au(this),HC(this,null,!0)):this.C7()}C7(){const t=by(this)||!this.Z?vC(this,!0):this.Z;t&&this.Xy(t.vssId,"m");this.isSubtitlesOn()||HC(this,by(this)||!this.Z?vC(this,!0):this.Z,!0)}isSubtitlesOn(){return!!this.loaded&&!!this.Z&&!by(this)}zf(){const t=by(this);OM(this,t)?HC(this,this.getAudioTrack().Z,!1):this.videoData.captionTracks.length&&
(this.loaded&&this.unload(),this.e7()&&(this.K=!1,this.Z=null,this.B&&(this.B.dispose(),this.B=null)),this.Eq()&&(t?HC(this,vC(this,!1),!1):this.load()))}y5(t){t&&(this.N={top:t.top,right:t.right,bottom:t.bottom,left:t.left,width:1-t.left-t.right,height:1-t.top-t.bottom},this.L.element.style.top=`${this.N.top*100}%`,this.L.element.style.left=`${this.N.left*100}%`,this.L.element.style.width=`${this.N.width*100}%`,this.L.element.style.height=`${this.N.height*100}%`,this.L.element.style.position="absolute",
t=aQe(this))&&(this.L.element.style.width=`${t.width}px`,this.L.element.style.height=`${t.height}px`)}onVideoDataChange(t,r){t==="newdata"&&(this.videoData=r,this.loaded&&this.unload(),this.K=!1,this.Z=null,this.B&&(this.B.dispose(),this.B=null,g.ca(this.player,"captionschanged",{})),this.Eq()&&this.load())}getAudioTrack(){return this.player.getAudioTrack()}RK(){const t=this.U.Th();t&&!t.f8()&&t.K();this.U.isFullscreen()?(this.W=this.rU=!0,this.loaded&&this.mZ()):(this.rU=this.e8.controlsType==="3",
this.W=KVy(this));HC(this,this.Z)}zX(){const t=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;t&&g.iC(this.player,"innertubeCommand",t)}BJ(t,r,x){const Y=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm;let I="";t&&(I=t.vssId,I=I.replace(Y,""));let m="";t&&t.getId()&&(m=t.getId()||"");t&&t.getXtags()&&(t=t.getXtags(),t=t.replace(Y,""),m=m.concat(`;${t}`));this.D==="HLS"&&(m="");this.U.BJ(r?I:"",r?m:"",x)}Xy(t,r){t=(t||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,
"");t.length>0&&this.U.Xy(t,r)}});})(_yt_player);
