(function(g){var window=this;'use strict';var AO=function(t){t.publish("autonavvisibility")},NPL=function(t,r){g.iC(t,"onAutonavCoundownStarted",r)},hO=function(t){return t.isBackground()&&t.Rh()},BPe=function(t,r){r=r.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.nextButton?.buttonRenderer;
t.N=r?.navigationEndpoint;r=r?.trackingParams;t.playButton&&r&&t.U.setTrackingParams(t.playButton.element,r)},nj=function(t){const r=EI(t);
var x=Math,Y=x.min;var I=t.K?Date.now()-t.K:0;x=Y.call(x,I,r);UI(t,Math.ceil((r-x)/1E3));r-x<=500&&t.Z()?t.select(!0):t.Z()&&t.G.start()},Lj=function(t){var r=t.U.mR(!0,t.U.isFullscreen());
g.D(t.container.element,"ytp-autonav-endscreen-small-mode",t.X4(r));g.D(t.container.element,"ytp-autonav-endscreen-is-premium",!!t.suggestion&&!!t.suggestion.ux);g.D(t.U.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!t.U.Uc());g.D(t.U.getRootNode(),"countdown-running",t.Z());g.D(t.container.element,"ytp-player-content",t.U.Uc());g.Va(t.overlay.element,{width:`${r.width}px`});if(!t.Z()){t.U.Uc()?UI(t,Math.round(EI(t)/1E3)):UI(t);r=!!t.suggestion&&!!t.suggestion.Ff;const x=t.U.Uc()||!r;g.D(t.container.element,
"ytp-autonav-endscreen-upnext-alternative-header-only",!x&&r);g.D(t.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",x&&!r);t.Y.Gf(t.U.Uc());g.D(t.element,"ytp-enable-w2w-color-transitions",!!t.U.getVideoData()?.watchToWatchTransitionRenderer)}},UI=function(t,r=-1){t=t.W.JH("ytp-autonav-endscreen-upnext-header");
g.UR(t);if(r>=0){r=String(r);const x="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],Y="Up next in $SECONDS".indexOf(x);if(Y>=0){t.appendChild(g.hF("Up next in $SECONDS".slice(0,Y)));const I=g.AF("span");g.l9(I,"ytp-autonav-endscreen-upnext-header-countdown-number");g.CD(I,r);t.appendChild(I);t.appendChild(g.hF("Up next in $SECONDS".slice(Y+x.length)));return}}g.CD(t,"Up next")},EI=function(t){return t.U.isFullscreen()?(t=t.U.getVideoData()?.o1,t===-1||t===void 0?8E3:t):t.U.Re()>=0?t.U.Re():
g.M2(t.U.X().experiments,"autoplay_time")||1E4},Mb=function(t,r){r=adZ(t,r);
var x=Math,Y=x.min;var I=(0,g.e)()-t.K;x=Y.call(x,I,r);r=r===0?1:Math.min(x/r,1);t.sC.setAttribute("stroke-dashoffset",`${-211*(r+1)}`);r>=1&&t.Z()&&t.api.getPresentingPlayerType()!==3?t.select(!0):t.Z()&&t.W.start()},adZ=function(t,r){return r?r:t.api.isFullscreen()?(t=t.api.getVideoData()?.o1,t===-1||t===void 0?8E3:t):t.api.Re()>=0?t.api.Re():g.M2(t.api.X().experiments,"autoplay_time")||1E4},Cj=function(t){const r=t.Uc();
r!==t.K&&(t.K=r,AO(t.player),t.K?(t.B!==t.Z&&t.B.hide(),t.table.hide()):(t.B!==t.Z&&t.B.show(),t.table.show()))},i4=function(t){return g.KM(t.player)&&t.W()&&!t.J},jp=function(t){const r=t.Uc();
r!==t.G&&(t.G=r,AO(t.player))},dG=function(t){return g.KM(t.player)&&t.W()&&!t.Y},z7=function(t){const r=t.Uc();
r!==t.MS&&(t.MS=r,AO(t.player))},Hoe=function(t){t=t.X();
return t.j0&&!t.Oc&&!t.disableOrganicUi},S9t=function(t){const r=t.player.getVideoData();
if(!r||t.Z===r.eX&&t.B===r.dU)return!1;t.Z=r.eX;t.B=r.dU;return!0},TPX=function(t){t.player.Oh("endscreen");
var r=t.player.getVideoData();r=new g.aK(Math.max((r.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});const x=new g.aK(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});t.player.iZ([r,x])};
g.jE.prototype.Re=g.xh(9,function(){return this.app.Re()});
g.Im.prototype.Re=g.xh(8,function(){return this.getVideoData().J3});
g.iI.prototype.U4=g.xh(7,function(t){this.sD().U4(t)});
g.fl.prototype.U4=g.xh(6,function(t){this.NU!==t&&(this.NU=t,this.Tc())});
var ldt=class extends g.l{constructor(t){const r=t.X(),x=r.W;super({A:"a",O:"ytp-autonav-suggestion-card",V:{href:"{{url}}",target:x?r.G:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},j:[{A:"div",K8:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],V:{style:"{{background}}"},j:[{A:"div",V:{"aria-label":"{{timestamp}}"},K8:["ytp-autonav-timestamp"],BN:"{{duration}}"},
{A:"div",K8:["ytp-autonav-live-stamp"],BN:"Live"},{A:"div",K8:["ytp-autonav-upcoming-stamp"],BN:"Upcoming"},{A:"div",O:"ytp-autonav-list-overlay",j:[{A:"div",O:"ytp-autonav-mix-text",BN:"Mix"},{A:"div",O:"ytp-autonav-mix-icon"}]}]},{A:"div",K8:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],BN:"{{title}}"},{A:"div",K8:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],BN:"{{author}}"},{A:"div",K8:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],
BN:"{{views_and_publish_time}}"}]});this.U=t;this.suggestion=null;this.Z=x;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)}select(){this.U.CQ(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.LX||void 0)&&this.U.logClick(this.element)}onClick(t){g.lC(t,this.U,this.Z,this.suggestion.sessionData||void 0)&&this.select()}onKeyPress(t){switch(t.keyCode){case 13:case 32:t.defaultPrevented||(this.select(),t.preventDefault())}}};var cn=class extends g.l{constructor(t,r=!1){super({A:"div",O:"ytp-autonav-endscreen-countdown-overlay"});this.PN=r;this.cancelCommand=this.N=void 0;this.K=0;this.container=new g.l({A:"div",O:"ytp-autonav-endscreen-countdown-container"});g.Q(this,this.container);this.container.C8(this.element);r=t.X();const x=r.W;this.U=t;this.suggestion=null;this.onVideoDataChange("newdata",this.U.getVideoData());this.S(t,"videodatachange",this.onVideoDataChange);this.W=new g.l({A:"div",O:"ytp-autonav-endscreen-upnext-container",
V:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},j:[{A:"div",O:"ytp-autonav-endscreen-upnext-header"},{A:"div",O:"ytp-autonav-endscreen-upnext-alternative-header",BN:"{{autoplayAlternativeHeader}}"},{A:"a",O:"ytp-autonav-endscreen-link-container",V:{href:"{{url}}",target:x?r.G:""},j:[{A:"div",O:"ytp-autonav-endscreen-upnext-thumbnail",V:{style:"{{background}}"},j:[{A:"div",V:{"aria-label":"{{timestamp}}"},
K8:["ytp-autonav-timestamp"],BN:"{{duration}}"},{A:"div",K8:["ytp-autonav-live-stamp"],BN:"Live"},{A:"div",K8:["ytp-autonav-upcoming-stamp"],BN:"Upcoming"}]},{A:"div",O:"ytp-autonav-endscreen-video-info",j:[{A:"div",O:"ytp-autonav-endscreen-premium-badge"},{A:"div",O:"ytp-autonav-endscreen-upnext-title",BN:"{{title}}"},{A:"div",O:"ytp-autonav-endscreen-upnext-author",BN:"{{author}}"},{A:"div",O:"ytp-autonav-view-and-date",BN:"{{views_and_publish_time}}"},{A:"div",O:"ytp-autonav-author-and-view",BN:"{{author_and_views}}"}]}]}]});
g.Q(this,this.W);this.W.C8(this.container.element);x||this.S(this.W.JH("ytp-autonav-endscreen-link-container"),"click",this.uV);this.U.createClientVe(this.container.element,this,115127);this.U.createClientVe(this.W.JH("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.l({A:"div",O:"ytp-autonav-overlay"});g.Q(this,this.overlay);this.overlay.C8(this.container.element);this.Y=new g.l({A:"div",O:"ytp-autonav-endscreen-button-container"});g.Q(this,this.Y);this.Y.C8(this.container.element);
this.cancelButton=new g.l({A:"button",K8:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button","ytp-autonav-endscreen-upnext-button-rounded"],V:{"aria-label":"Cancel autoplay"},BN:"Cancel"});g.Q(this,this.cancelButton);this.cancelButton.C8(this.Y.element);this.cancelButton.listen("click",this.sC,this);this.U.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.l({A:"a",K8:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
"ytp-autonav-endscreen-upnext-button-rounded"],V:{href:"{{url}}",role:"button","aria-label":"Play next video"},BN:"Play Now"});g.Q(this,this.playButton);this.playButton.C8(this.Y.element);this.playButton.listen("click",this.uV,this);this.U.createServerVe(this.playButton.element,this.playButton,!0);(r=this.U.getVideoData())&&BPe(this,r);this.G=new g.B7(()=>{nj(this)},500);
g.Q(this,this.G);this.MS();this.S(t,"autonavvisibility",this.MS);this.U.C("web_autonav_color_transition")&&(this.S(t,"autonavchange",this.WN),this.S(t,"onAutonavCoundownStarted",this.RO))}L(t){this.suggestion!==t&&(this.suggestion=t,g.PT(this.W,t),this.playButton.updateValue("url",this.suggestion.CA()),Lj(this))}Z(){return this.K>0}J(){this.Z()||(this.K=Date.now(),nj(this),NPL(this.U,EI(this)),g.D(this.U.getRootNode(),"countdown-running",this.Z()))}D(){this.B();nj(this);const t=this.W.JH("ytp-autonav-endscreen-upnext-header");
t&&g.CD(t,"Up next")}B(){this.Z()&&(this.G.stop(),this.K=0)}select(t=!1){this.U.nextVideo(!1,t);this.B()}uV(t){g.lC(t,this.U)&&(t.currentTarget===this.playButton.element?this.U.logClick(this.playButton.element):t.currentTarget===this.W.JH("ytp-autonav-endscreen-link-container")&&(t=this.W.JH("ytp-autonav-endscreen-link-container"),this.U.logVisibility(t,!0),this.U.logClick(t)),this.N?(g.iC(this.U,"innertubeCommand",this.N),this.B()):this.select())}sC(){this.U.logClick(this.cancelButton.element);g.q_(this.U,
!0);this.cancelCommand&&g.iC(this.U,"innertubeCommand",this.cancelCommand)}onVideoDataChange(t,r){BPe(this,r);this.cancelCommand=r.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.cancelButton?.buttonRenderer?.command}RO(t){if(this.U.getVideoData()?.watchToWatchTransitionRenderer){var r=this.U.getVideoData().watchToWatchTransitionRenderer;const x=r?.fromColorPaletteDark,Y=r?.toColorPaletteDark;x&&Y&&(r=this.element,r.style.setProperty("--w2w-start-background-color",
g.TP(x.surgeColor)),r.style.setProperty("--w2w-start-primary-text-color",g.TP(x.primaryTitleColor)),r.style.setProperty("--w2w-start-secondary-text-color",g.TP(x.secondaryTitleColor)),r.style.setProperty("--w2w-end-background-color",g.TP(Y.surgeColor)),r.style.setProperty("--w2w-end-primary-text-color",g.TP(Y.primaryTitleColor)),r.style.setProperty("--w2w-end-secondary-text-color",g.TP(Y.secondaryTitleColor)),r.style.setProperty("--w2w-animation-duration",`${t}ms`));g.D(this.element,"ytp-w2w-animate",
!0)}}WN(t){this.U.C("web_autonav_color_transition")&&t!==2&&g.D(this.element,"ytp-w2w-animate",!1)}MS(){const t=this.U.Uc();this.PN&&this.DG!==t&&this.Gf(t);Lj(this);this.U.logVisibility(this.container.element,t);this.U.logVisibility(this.cancelButton.element,t);this.U.logVisibility(this.W.JH("ytp-autonav-endscreen-link-container"),t);this.U.logVisibility(this.playButton.element,t)}X4(t){return t.width<400||t.height<459}};var y5=class extends g.l{constructor(t,r){super({A:"div",K8:["html5-endscreen","ytp-player-content",r||"base-endscreen"]});this.created=!1;this.player=t}create(){this.created=!0}destroy(){this.created=!1}W(){return!1}Uc(){return!1}N(){return!1}};var u4=class extends g.l{constructor(t){super({A:"div",K8:["ytp-upnext","ytp-player-content"],V:{"aria-label":"{{aria_label}}"},j:[{A:"div",O:"ytp-cued-thumbnail-overlay-image",V:{style:"{{background}}"}},{A:"span",O:"ytp-upnext-top",j:[{A:"span",O:"ytp-upnext-header",BN:"Up Next"},{A:"span",O:"ytp-upnext-title",BN:"{{title}}"},{A:"span",O:"ytp-upnext-author",BN:"{{author}}"}]},{A:"a",O:"ytp-upnext-autoplay-icon",V:{role:"button",href:"{{url}}","aria-label":"Play next video"},j:[{A:"svg",V:{height:"100%",
version:"1.1",viewBox:"0 0 72 72",width:"100%"},j:[{A:"circle",O:"ytp-svg-autoplay-circle",V:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{A:"circle",O:"ytp-svg-autoplay-ring",V:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{A:"path",O:"ytp-svg-fill",V:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{A:"span",O:"ytp-upnext-bottom",j:[{A:"span",O:"ytp-upnext-cancel"},
{A:"span",O:"ytp-upnext-paused",BN:"Autoplay is paused"}]}]});this.api=t;this.cancelButton=null;this.sC=this.JH("ytp-svg-autoplay-ring");this.G=this.notification=this.W=this.suggestion=null;this.N=new g.B7(this.Y,5E3,this);this.K=0;var r=this.JH("ytp-upnext-cancel");this.cancelButton=new g.l({A:"button",K8:["ytp-upnext-cancel-button","ytp-button"],V:{tabindex:"0","aria-label":"Cancel autoplay"},BN:"Cancel"});g.Q(this,this.cancelButton);this.cancelButton.listen("click",this.uV,this);this.cancelButton.C8(r);
this.cancelButton&&this.api.createClientVe(this.cancelButton.element,this,115129);g.Q(this,this.N);this.api.createClientVe(this.element,this,18788);r=this.JH("ytp-upnext-autoplay-icon");this.S(r,"click",this.WN);this.api.createClientVe(r,this,115130);this.MS();this.S(t,"autonavvisibility",this.MS);this.S(t,"mdxnowautoplaying",this.RO);this.S(t,"mdxautoplaycanceled",this.PN);g.D(this.element,"ytp-upnext-mobile",this.api.X().B)}Y(){this.notification&&(this.N.stop(),this.LU(this.G),this.G=null,this.notification.close(),
this.notification=null)}L(t){this.suggestion=t;g.PT(this,t,"hqdefault.jpg")}MS(){this.Gf(this.api.Uc());this.api.logVisibility(this.element,this.api.Uc());this.api.logVisibility(this.JH("ytp-upnext-autoplay-icon"),this.api.Uc());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.Uc())}EC(){window.focus();this.Y()}J(t){this.Z()||(g.FZ("a11y-announce",`${"Up Next"} ${this.suggestion.title}`),this.K=(0,g.e)(),this.W=new g.B7(()=>{Mb(this,t)},25),Mb(this,t),NPL(this.api,adZ(this,
t)));
g.rL(this.element,"ytp-upnext-autoplay-paused")}hide(){super.hide()}Z(){return!!this.W}D(){this.B();this.K=(0,g.e)();Mb(this);g.wn(this.element,"ytp-upnext-autoplay-paused")}B(){this.Z()&&(this.W.dispose(),this.W=null)}select(t=!1){if(this.api.X().C("autonav_notifications")&&t&&window.Notification&&typeof document.hasFocus==="function"){const r=Notification.permission;r==="default"?Notification.requestPermission():r!=="granted"||document.hasFocus()||(this.Y(),this.notification=new Notification("Up Next",
{body:this.suggestion.title,icon:this.suggestion.P_()}),this.G=this.S(this.notification,"click",this.EC),this.N.start())}this.B();this.api.nextVideo(!1,t)}WN(t){!g.Mr(this.cancelButton.element,t.target)&&g.lC(t,this.api)&&(this.api.Uc()&&this.api.logClick(this.JH("ytp-upnext-autoplay-icon")),this.select())}uV(){this.api.Uc()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.q_(this.api,!0)}RO(t){this.api.getPresentingPlayerType();this.show();this.J(t)}PN(){this.api.getPresentingPlayerType();
this.B();this.hide()}DE(){this.B();this.Y();super.DE()}};var wre=class extends y5{constructor(t){super(t,"autonav-endscreen");this.overlay=this.videoData=null;this.table=new g.l({A:"div",O:"ytp-suggestion-panel",j:[{A:"div",K8:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],BN:"More videos"}]});this.G=new g.l({A:"div",O:"ytp-suggestions-container"});this.videos=[];this.D=null;this.K=this.L=!1;this.B=new cn(this.player);g.Q(this,this.B);this.B.C8(this.element);t.getVideoData().dU?this.Z=this.B:(this.Z=new u4(t),g.$I(this.player,
this.Z.element,4),g.Q(this,this.Z));this.overlay=new g.l({A:"div",O:"ytp-autonav-overlay-cancelled-state"});g.Q(this,this.overlay);this.overlay.C8(this.element);this.J=new g.pG(this);g.Q(this,this.J);g.Q(this,this.table);this.table.C8(this.element);this.table.show();g.Q(this,this.G);this.G.C8(this.table.element);this.hide()}create(){super.create();this.J.S(this.player,"appresize",this.Y);this.J.S(this.player,"onVideoAreaChange",this.Y);this.J.S(this.player,"videodatachange",this.onVideoDataChange);
this.J.S(this.player,"autonavchange",this.MS);this.J.S(this.player,"onAutonavCancelled",this.uV);this.onVideoDataChange()}show(){super.show();(this.L||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.q_(this.player,!1);g.KM(this.player)&&this.W()&&!this.D?(Cj(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||hO(this.player.Us())&&this.player.C("web_player_pip_logging_fix")?this.Z.select(!0):this.Z.J():this.videoData.autonavState===3&&this.Z.D()):(g.q_(this.player,
!0),Cj(this));this.Y()}hide(){super.hide();this.Z.D();Cj(this)}Y(){var t=this.player.mR(!0,this.player.isFullscreen());Cj(this);Lj(this.B);g.D(this.element,"ytp-autonav-cancelled-small-mode",this.X4(t));g.D(this.element,"ytp-autonav-cancelled-tiny-mode",this.oN(t));g.D(this.element,"ytp-autonav-cancelled-mini-mode",t.width<=400||t.height<=360);this.overlay&&g.Va(this.overlay.element,{width:`${t.width}px`});if(!this.K)for(t=0;t<this.videos.length;t++)g.D(this.videos[t].element,"ytp-suggestion-card-with-margin",
t%2===1)}onVideoDataChange(){var t=this.player.getVideoData();if(this.videoData!==t&&t){this.videoData=t;t=this.videoData.suggestions;var r=this.videoData.G();r&&(this.Z.L(r),this.Z!==this.B&&this.B.L(r));if(t&&t.length)for(let Y=0;Y<Gif.length;++Y){var x=Gif[Y];t&&t[x]&&(this.videos[Y]=new ldt(this.player),r=this.videos[Y],x=t[x],r.suggestion!==x&&(r.suggestion=x,g.PT(r,x)),g.Q(this,this.videos[Y]),this.videos[Y].C8(this.G.element))}this.Y()}}MS(t){t===1?(this.L=!1,this.D=this.videoData.clientPlaybackNonce,
this.Z.B(),this.DG&&this.Y()):(this.L=!0,this.Uc()&&(t===2?this.Z.J():t===3&&this.Z.D()))}uV(t){t?this.MS(1):(this.D=null,this.L=!1)}W(){return this.videoData.autonavState!==1}X4(t){return(t.width<910||t.height<459)&&!this.oN(t)&&!(t.width<=400||t.height<=360)}oN(t){return t.width<800&&!(t.width<=400||t.height<=360)}Uc(){return this.DG&&g.KM(this.player)&&this.W()&&!this.D}},Gif=[1,3,2,4];var t4f=class extends y5{constructor(t){super(t,"videowall-endscreen");this.U=t;this.stills=[];this.J=this.videoData=null;this.Y=this.G=!1;this.MS=null;g.wn(this.element,"modern-videowall-endscreen");this.B=new g.pG(this);g.Q(this,this.B);this.K=new g.B7(()=>{g.wn(this.element,"ytp-show-tiles")},0);
g.Q(this,this.K);this.table=new g.b1({A:"div",O:"ytp-modern-endscreen-content"});g.Q(this,this.table);this.table.C8(this.element);t.getVideoData().dU?this.Z=new cn(t,!0):this.Z=new u4(t);g.Q(this,this.Z);g.$I(this.player,this.Z.element,4);t.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var t=this.player.getVideoData();t&&(this.videoData=t);this.D();this.B.S(this.player,"appresize",this.D);this.B.S(this.player,"onVideoAreaChange",this.D);this.B.S(this.player,"videodatachange",
this.onVideoDataChange);this.B.S(this.player,"autonavchange",this.L);this.B.S(this.player,"onAutonavCancelled",this.uV);t=this.videoData.autonavState;t!==this.MS&&this.L(t);this.B.S(this.element,"transitionend",this.WN)}destroy(){this.B.B();g.lB(this.stills);this.stills=[];super.destroy();g.rL(this.element,"ytp-show-tiles");this.K.stop();this.MS=this.videoData.autonavState}W(){return this.videoData.autonavState!==1}show(){const t=this.DG;super.show();g.rL(this.element,"ytp-show-tiles");this.player.X().B?
g.a3(this.K):this.K.start();(this.Y||this.J&&this.J!==this.videoData.clientPlaybackNonce)&&g.q_(this.player,!1);i4(this)?(jp(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||hO(this.player.Us())&&this.player.C("web_player_pip_logging_fix")?this.Z.select(!0):this.Z.J():this.videoData.autonavState===3&&this.Z.D()):(g.q_(this.player,!0),jp(this));t!==this.DG&&this.player.logVisibility(this.element,!0)}hide(){const t=this.DG;super.hide();this.Z.D();jp(this);t!==this.DG&&this.player.logVisibility(this.element,
!1)}WN(t){t.target===this.element&&this.D()}D(){const t=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.G()];if(t.length){var r=this.U.mR(!0,this.U.isFullscreen()),x=Math.floor((r.width-64+16)/(g.Qv(r.width*.27,250,450)+16));r=Math.min(3,Math.floor((r.height-64)/((r.width-64-(x-1)*16)/x*.5625+70)));g.xT(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);g.wn(this.element,`ytp-modern-endscreen-limit-rows-${r}`);
g.D(this.element,"ytp-modern-endscreen-single-item",x===1);g.D(this.element,"ytp-modern-endscreen-row-0",r===0);x=this.table.element;x.ariaLive="polite";this.Z.L(this.videoData.G());this.Z instanceof cn&&Lj(this.Z);g.D(this.element,"ytp-endscreen-takeover",i4(this));jp(this);r=0;x.ariaBusy="true";var Y=t.length;for(let I=0;I<Y;I++){const m=I%Y;let F=this.stills[I];F||(F=new g.dN$(this.player),this.stills[I]=F,x.appendChild(F.element));g.EtH(F,t[m]);r++}this.stills.length=r}}onVideoDataChange(){const t=
this.player.getVideoData({playerType:1});this.videoData!==t&&(t?.G()?(this.videoData=t,this.D()):this.player.ZE("missg",{vid:t?.videoId||"",cpn:t?.clientPlaybackNonce||""}))}N(){return this.Z.Z()}L(t){t===1?(this.Y=!1,this.J=this.videoData.clientPlaybackNonce,this.Z.B(),this.DG&&this.D()):(this.Y=!0,this.DG&&i4(this)&&(t===2?this.Z.J():t===3&&this.Z.D()))}uV(t){if(t){for(t=0;t<this.stills.length;t++)this.U.logVisibility(this.stills[t].element,!0);this.L(1)}else this.J=null,this.Y=!1;this.D()}Uc(){return this.DG&&
i4(this)}};var rnm=class extends y5{constructor(t){super(t,"subscribecard-endscreen");this.Z=new g.l({A:"div",O:"ytp-subscribe-card",j:[{A:"img",O:"ytp-author-image",V:{src:"{{profilePicture}}"}},{A:"div",O:"ytp-subscribe-card-right",j:[{A:"div",O:"ytp-author-name",BN:"{{author}}"},{A:"div",O:"html5-subscribe-button-container"}]}]});g.Q(this,this.Z);this.Z.C8(this.element);const r=t.getVideoData();this.subscribeButton=new g.up("Subscribe",null,"Unsubscribe",null,!0,!1,r.yC,r.subscribed,"trailer-endscreen",null,
t,!1);g.Q(this,this.subscribeButton);this.subscribeButton.C8(this.Z.JH("html5-subscribe-button-container"));this.S(t,"videodatachange",this.wU);this.wU();this.hide()}wU(){const t=this.player.getVideoData();this.Z.update({profilePicture:t.profilePicture,author:t.author});this.subscribeButton.channelId=t.yC;var r=this.subscribeButton;t.subscribed?r.Z():r.B()}};var xOs=class extends g.l{constructor(t){const r=t.X(),x=g.zW||g.qG?{style:"will-change: opacity"}:void 0,Y=r.W,I=["ytp-videowall-still"];r.B&&I.push("ytp-videowall-show-text");super({A:"a",K8:I,V:{href:"{{url}}",target:Y?r.G:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},j:[{A:"div",O:"ytp-videowall-still-image",V:{style:"{{background}}"}},{A:"span",O:"ytp-videowall-still-info",V:{"aria-hidden":"true"},j:[{A:"span",O:"ytp-videowall-still-info-bg",
j:[{A:"span",O:"ytp-videowall-still-info-content",V:x,j:[{A:"span",O:"ytp-videowall-still-info-title",BN:"{{title}}"},{A:"span",O:"ytp-videowall-still-info-author",BN:"{{author_and_views}}"},{A:"span",O:"ytp-videowall-still-info-live",BN:"Live"},{A:"span",O:"ytp-videowall-still-info-duration",BN:"{{duration}}"}]}]}]},{A:"span",K8:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],V:{"aria-hidden":"true"},j:[{A:"span",O:"ytp-videowall-still-listlabel-icon"},"Playlist",{A:"span",
O:"ytp-videowall-still-listlabel-length",j:[" (",{A:"span",BN:"{{playlist_length}}"},")"]}]},{A:"span",K8:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],V:{"aria-hidden":"true"},j:[{A:"span",O:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{A:"span",O:"ytp-videowall-still-listlabel-length",BN:" (50+)"}]}]});this.suggestion=null;this.B=Y;this.api=t;this.Z=new g.pG(this);g.Q(this,this.Z);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.Z.S(t,"videodatachange",
this.onVideoDataChange);t.createServerVe(this.element,this);this.onVideoDataChange()}select(){this.api.CQ(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.LX||void 0)&&this.api.logClick(this.element)}onClick(t){if(g.Z5(this.api.X())&&this.api.C("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);let r=this.suggestion.CA();const x={};g.fM(this.api,x);r=g.Md(r,x);g.Gx(r,this.api,t)}else g.lC(t,this.api,
this.B,this.suggestion.sessionData||void 0)&&this.select()}onKeyPress(t){switch(t.keyCode){case 13:case 32:t.defaultPrevented||(this.select(),t.preventDefault())}}onVideoDataChange(){const t=this.api.getVideoData(),r=this.api.X();this.B=t.uK?!1:r.W}};var YW1=class extends y5{constructor(t){super(t,"videowall-endscreen");this.U=t;this.J=0;this.stills=[];this.Y=this.videoData=null;this.K=this.MS=!1;this.uV=null;this.D=new g.pG(this);g.Q(this,this.D);this.L=new g.B7(()=>{g.wn(this.element,"ytp-show-tiles")},0);
g.Q(this,this.L);var r=new g.l({A:"button",K8:["ytp-button","ytp-endscreen-previous"],V:{"aria-label":"Previous"},j:[g.Cr()]});g.Q(this,r);r.C8(this.element);r.listen("click",this.RO,this);this.table=new g.b1({A:"div",O:"ytp-endscreen-content"});g.Q(this,this.table);this.table.C8(this.element);r=new g.l({A:"button",K8:["ytp-button","ytp-endscreen-next"],V:{"aria-label":"Next"},j:[g.il()]});g.Q(this,r);r.C8(this.element);r.listen("click",this.sC,this);t.getVideoData().dU?this.Z=new cn(t,!0):this.Z=
new u4(t);g.Q(this,this.Z);g.$I(this.player,this.Z.element,4);t.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var t=this.player.getVideoData();t&&(this.videoData=t);this.B();this.D.S(this.player,"appresize",this.B);this.D.S(this.player,"onVideoAreaChange",this.B);this.D.S(this.player,"videodatachange",this.onVideoDataChange);this.D.S(this.player,"autonavchange",this.G);this.D.S(this.player,"onAutonavCancelled",this.WN);t=this.videoData.autonavState;t!==this.uV&&this.G(t);
this.D.S(this.element,"transitionend",this.PN)}destroy(){this.D.B();g.lB(this.stills);this.stills=[];super.destroy();g.rL(this.element,"ytp-show-tiles");this.L.stop();this.uV=this.videoData.autonavState}W(){return this.videoData.autonavState!==1}show(){const t=this.DG;super.show();g.rL(this.element,"ytp-show-tiles");this.player.X().B?g.a3(this.L):this.L.start();(this.K||this.Y&&this.Y!==this.videoData.clientPlaybackNonce)&&g.q_(this.player,!1);dG(this)?(z7(this),this.videoData.autonavState===2?this.player.getVisibilityState()===
3||hO(this.player.Us())&&this.player.C("web_player_pip_logging_fix")?this.Z.select(!0):this.Z.J():this.videoData.autonavState===3&&this.Z.D()):(g.q_(this.player,!0),z7(this));t!==this.DG&&this.player.logVisibility(this.element,!0)}hide(){const t=this.DG;super.hide();this.Z.D();z7(this);t!==this.DG&&this.player.logVisibility(this.element,!1)}PN(t){t.target===this.element&&this.B()}B(){var t=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.G()];if(t.length){g.wn(this.element,
"ytp-endscreen-paginate");var r=this.U.mR(!0,this.U.isFullscreen()),x=g.Zc(this.U);x&&(x=x.gH()?48:32,r.width-=x*2);var Y=r.width/r.height,I=96/54,m=x=2,F=Math.max(r.width/96,2),A=Math.max(r.height/54,2),h=t.length;var E=h*4;for(E-=4;E>0&&(x<F||m<A);){var U=x/2,n=m/2,L=x<=F-2&&E>=n*4,M=m<=A-2&&E>=U*4;if((U+1)/n*I/Y>Y/(U/(n+1)*I)&&M)E-=U*4,m+=2;else if(L)E-=n*4,x+=2;else if(M)E-=U*4,m+=2;else break}I=!1;E>=12&&h*4-E<=6&&(m>=4||x>=4)&&(I=!0);E=x*96;F=m*54;Y=E/F<Y?r.height/F:r.width/E;Y=Math.min(Y,2);
E=Math.floor(Math.min(r.width,E*Y));F=Math.floor(Math.min(r.height,F*Y));r=this.table.element;r.ariaLive="polite";g.t4(r,E,F);g.Va(r,{marginLeft:`${E/-2}px`,marginTop:`${F/-2}px`});this.Z.L(this.videoData.G());this.Z instanceof cn&&Lj(this.Z);g.D(this.element,"ytp-endscreen-takeover",dG(this));z7(this);E+=4;F+=4;Y=0;r.ariaBusy="true";for(A=0;A<x;A++)for(U=0;U<m;U++)if(L=Y,M=0,I&&A>=x-2&&U>=m-2?M=1:U%2===0&&A%2===0&&(U<2&&A<2?U===0&&A===0&&(M=2):M=2),L=g.Py(L+this.J,h),M!==0){n=this.stills[Y];n||(n=
new xOs(this.player),this.stills[Y]=n,r.appendChild(n.element));var z=Math.floor(F*U/m);const p=Math.floor(E*A/x),q=Math.floor(F*(U+M)/m)-z-4,f=Math.floor(E*(A+M)/x)-p-4;g.as(n.element,p,z);g.t4(n.element,f,q);g.Va(n.element,"transitionDelay",(U+A)/20+"s");g.D(n.element,"ytp-videowall-still-mini",M===1);g.D(n.element,"ytp-videowall-still-large",M>2);M=Math.max(f,q);g.D(n.element,"ytp-videowall-still-round-large",M>=256);g.D(n.element,"ytp-videowall-still-round-medium",M>96&&M<256);g.D(n.element,"ytp-videowall-still-round-small",
M<=96);L=t[L];n.suggestion!==L&&(n.suggestion=L,M=n.api.X(),z=g.Gg(n.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.PT(n,L,z),g.Z5(M)&&!n.api.C("web_player_log_click_before_generating_ve_conversion_params")&&(M=L.CA(),z={},g.zx(n.api,"addEmbedsConversionTrackingParams",[z]),M=g.Md(M,z),n.updateValue("url",M)),(L=(L=L.sessionData)&&L.itct)&&n.api.setTrackingParams(n.element,L));Y++}r.ariaBusy="false";g.D(this.element,"ytp-endscreen-paginate",Y<h);for(t=this.stills.length-1;t>=
Y;t--)x=this.stills[t],g.LD(x.element),g.T9(x);this.stills.length=Y}}onVideoDataChange(){const t=this.player.getVideoData({playerType:1});this.videoData!==t&&(t?.G()?(this.J=0,this.videoData=t,this.B()):this.player.ZE("missg",{vid:t?.videoId||"",cpn:t?.clientPlaybackNonce||""}))}sC(){this.J+=this.stills.length;this.B()}RO(){this.J-=this.stills.length;this.B()}N(){return this.Z.Z()}G(t){t===1?(this.K=!1,this.Y=this.videoData.clientPlaybackNonce,this.Z.B(),this.DG&&this.B()):(this.K=!0,this.DG&&dG(this)&&
(t===2?this.Z.J():t===3&&this.Z.D()))}WN(t){if(t){for(t=0;t<this.stills.length;t++)this.U.logVisibility(this.stills[t].element,!0);this.G(1)}else this.Y=null,this.K=!1;this.B()}Uc(){return this.DG&&dG(this)}};var I_m=class extends g.l{constructor(t){super({A:"button",K8:["ytp-watch-on-youtube-button","ytp-button"],BN:"{{content}}"});this.U=t;this.buttonType=this.buttonType=1;this.Z();this.buttonType===2&&g.wn(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.Z);this.Gf(!0)}Z(){let t,r;switch(this.buttonType){case 1:t="Watch again on YouTube";r=156915;break;case 2:t="Continue watching on YouTube";r=156942;break;default:t="Continue watching on YouTube",
r=156942}this.update({content:t});this.U.hasVe(this.element)&&this.U.destroyVe(this.element);this.U.createClientVe(this.element,this,r)}onClick(t){this.U.C("web_player_log_click_before_generating_ve_conversion_params")&&this.U.logClick(this.element);g.Gx(this.getVideoUrl(),this.U,t);this.U.C("web_player_log_click_before_generating_ve_conversion_params")||this.U.logClick(this.element)}getVideoUrl(){var t=!0;switch(this.buttonType){case 1:t=!0;break;case 2:t=!1}t=this.U.getVideoUrl(t,!1,!1,!0);const r=
this.U.X();if(g.Z5(r)){const x={};g.Z5(r)&&g.zx(this.U,"addEmbedsConversionTrackingParams",[x]);t=g.Md(t,x)}return t}logVisibility(){this.U.logVisibility(this.element,this.DG&&this.iV)}show(){super.show();this.logVisibility()}hide(){super.hide();this.logVisibility()}Zp(t){super.Zp(t);this.logVisibility()}};var mOt=class extends y5{constructor(t){super(t,"watch-again-on-youtube-endscreen");this.watchButton=new I_m(t);g.Q(this,this.watchButton);this.watchButton.C8(this.element);g.vyi(t)&&(this.Z=new g.Gqf(t),g.Q(this,this.Z),this.B=new g.l({A:"div",K8:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],V:{tabIndex:"-1"},j:[this.Z]}),g.Q(this,this.B),this.Z.C8(this.B.element),this.B.C8(this.element));t.createClientVe(this.element,this,156914);this.hide()}hasSuggestions(){return this.Z?.hasSuggestions()}show(){if(this.player.getPlayerState()!==
3){super.show();const r=this.B;if(r){var t=this.Z.hasSuggestions();g.D(this.element,"ytp-shorts-branded-ui",t);t?r.show():r.hide()}g.Zc(this.player)?.U4(!0);this.player.logVisibility(this.element,!0);this.watchButton.Zp(!0)}}hide(){super.hide();g.Zc(this.player)?.U4(!1);this.player.logVisibility(this.element,!1);this.watchButton.Zp(!1)}};g.bd("endscreen",class extends g.OS{constructor(t){super(t);this.endScreen=null;this.Z=this.B=this.D=!1;this.listeners=new g.pG(this);g.Q(this,this.listeners);const r=t.X();t.isEmbedsShortsMode()?this.endScreen=new mOt(t):Hoe(t)?(this.D=!0,S9t(this),this.Z?this.endScreen=new wre(t):r.C("delhi_modern_endscreen")?this.endScreen=new t4f(t):this.endScreen=new YW1(t)):r.Oc?this.endScreen=new rnm(t):this.endScreen=new y5(t);g.Q(this,this.endScreen);g.$I(t,this.endScreen.element,4);TPX(this);this.listeners.S(t,
"videodatachange",this.onVideoDataChange,this);this.listeners.S(t,g.DK("endscreen"),x=>{this.onCueRangeEnter(x)});
this.listeners.S(t,g.Xs("endscreen"),x=>{this.onCueRangeExit(x)})}Eq(){var t=this.player.getVideoData();
const r=t.mutedAutoplay&&(t.limitedPlaybackDurationInSeconds>0||t.endSeconds>0||t.mutedAutoplayDurationMode!==2);if(this.player.isEmbedsShortsMode()&&!r)return!0;var x=!(!t?.G()&&!t?.suggestions?.length);x=!Hoe(this.player)||x;t=t.Lt;const Y=this.player.Rk();return x&&!t&&!Y&&!r}Uc(){return this.endScreen.Uc()}AJ(){return this.Uc()?this.endScreen.N():!1}DE(){this.player.Oh("endscreen");super.DE()}load(){{const x=this.player.getVideoData(),Y=x.transitionEndpointAtEndOfStream;if(Y&&Y.videoId){var t=
this.player.PE().Ri.get("heartbeat");var r=x.G();!r||Y.videoId!==r.videoId||x.Ps?(this.player.CQ(Y.videoId,void 0,void 0,!0,!0,Y),t&&t.Ze("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),t=!0):t=!1}else t=!1}t||(super.load(),this.endScreen.show())}unload(){super.unload();this.endScreen.hide();this.endScreen.destroy()}onCueRangeEnter(t){this.Eq()&&(this.endScreen.created||this.endScreen.create(),t.getId()==="load"&&this.load())}onCueRangeExit(t){t.getId()===
"load"&&this.loaded&&this.unload()}onVideoDataChange(){TPX(this);this.D&&S9t(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.Z?this.endScreen=new wre(this.player):this.endScreen=new YW1(this.player),g.Q(this,this.endScreen),g.$I(this.player,this.endScreen.element,4))}});})(_yt_player);
